"""Server-side automation engine.

Rules react to platform EVENTS (an alert opening, a ticket being created, an SLA
breach) and take SAFE, in-platform ACTIONS — open a ticket, assign it, raise a
notification, set priority, add an internal note, acknowledge an alert. Nothing
here runs code on an endpoint or reaches outside OpsPilot; the agent stays
telemetry-only. Every rule that fires is recorded in `automation_runs` and the
audit log, so there's always an answer to "why did the system do that?".

Entry point: dispatch(db, trigger, context). Event sources build a context with
build_alert_context() / build_ticket_context() and call dispatch after their own
commit.
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy.orm import Session

from ..models import (
    ACTION_ACK_ALERT, ACTION_ADD_NOTE, ACTION_ASSIGN, ACTION_CREATE_TICKET,
    ACTION_LINKEDIN_POST, ACTION_NOTIFY, ACTION_SEND_EMAIL, ACTION_SET_PRIORITY,
    Alert, AlertStatus, AutomationRule, AutomationRun, Device, Notification,
    PRIORITIES, STAFF_ROLES, SupportTicket, TicketComment, TicketStatus,
    TRIGGER_SCHEDULE, User,
)
from . import audit, sla


def _now() -> datetime:
    return datetime.now(timezone.utc)


# --------------------------------------------------------------------------- #
# Context builders (kept here so event sources stay terse)
# --------------------------------------------------------------------------- #
def build_alert_context(alert: Alert, device: Device | None) -> dict:
    return {
        "client_id": alert.client_id, "alert": alert, "device": device,
        "alert_id": alert.id, "kind": alert.kind, "severity": alert.severity.value,
        "hostname": device.hostname if device else None,
    }


def build_ticket_context(ticket: SupportTicket) -> dict:
    return {
        "client_id": ticket.client_id, "ticket": ticket, "ticket_id": ticket.id,
        "priority": ticket.priority, "subject": ticket.subject,
        "status": ticket.status.value,
    }


# --------------------------------------------------------------------------- #
# Matching
# --------------------------------------------------------------------------- #
def _matches(conditions: dict, ctx: dict) -> bool:
    """Every condition key must equal the matching context value (string-lenient
    so JSON numbers compare cleanly)."""
    if not conditions:
        return True
    for k, v in conditions.items():
        cv = ctx.get(k)
        if cv != v and str(cv) != str(v):
            return False
    return True


# --------------------------------------------------------------------------- #
# Actions — each returns a short human summary string
# --------------------------------------------------------------------------- #
def _least_loaded_staff(db: Session) -> User | None:
    staff = db.query(User).filter(User.role.in_(list(STAFF_ROLES)), User.is_active.is_(True)).all()
    if not staff:
        return None
    open_states = [TicketStatus.OPEN, TicketStatus.IN_PROGRESS]
    return min(staff, key=lambda s: db.query(SupportTicket).filter(
        SupportTicket.assigned_to_user_id == s.id,
        SupportTicket.status.in_(open_states)).count())


def _act_create_ticket(db: Session, action: dict, ctx: dict) -> str:
    alert = ctx.get("alert")
    if alert is None:
        return "create_ticket skipped (no alert in context)"
    subject = (action.get("subject")
               or f"[Auto] {alert.kind} on {ctx.get('hostname') or 'device'}")
    priority = action.get("priority") or ("urgent" if ctx.get("severity") == "critical" else "normal")
    if priority not in PRIORITIES:
        priority = "normal"
    t = SupportTicket(client_id=alert.client_id, subject=subject[:200],
                      body=f"Auto-generated by automation from alert: {alert.message}",
                      priority=priority, created_at=_now())
    sla.stamp_due_dates(db, t)
    db.add(t)
    db.flush()  # get an id for the summary without committing
    return f"opened ticket #{t.id} ({priority})"


def _act_ack_alert(db: Session, action: dict, ctx: dict) -> str:
    alert = ctx.get("alert")
    if alert is None or alert.status == AlertStatus.RESOLVED:
        return "ack_alert skipped"
    alert.status = AlertStatus.ACKNOWLEDGED
    alert.acknowledged_at = _now()
    return f"acknowledged alert #{alert.id}"


def _act_notify(db: Session, action: dict, ctx: dict) -> str:
    msg = action.get("message") or _default_notify_message(ctx)
    severity = action.get("severity", ctx.get("severity", "info"))
    db.add(Notification(
        client_id=ctx.get("client_id"), target_user_id=action.get("user_id"),
        kind=action.get("kind", "automation"), severity=severity, message=msg[:1000],
    ))
    # Fan out to configured channels (email/Slack/Teams/webhook). Best-effort.
    from . import notifications as notif_svc
    sent = notif_svc.fanout(db, message=msg, severity=severity, client_id=ctx.get("client_id"))
    return f"raised notification (+{sent} channel(s))" if sent else "raised notification"


def _default_notify_message(ctx: dict) -> str:
    if ctx.get("alert") is not None:
        return f"{ctx.get('severity', 'info').upper()} alert: {ctx['alert'].message}" + (
            f" on {ctx['hostname']}" if ctx.get("hostname") else "")
    if ctx.get("ticket") is not None:
        return f"Ticket #{ctx.get('ticket_id')}: {ctx.get('subject')}"
    return "Automation notification"


def _act_assign(db: Session, action: dict, ctx: dict) -> str:
    ticket = ctx.get("ticket")
    if ticket is None:
        return "assign skipped (no ticket in context)"
    if action.get("auto"):
        target = _least_loaded_staff(db)
        if not target:
            return "assign skipped (no staff available)"
    else:
        uid = action.get("user_id")
        target = db.get(User, uid) if uid else None
        if not target or target.role not in STAFF_ROLES:
            return "assign skipped (invalid assignee)"
    ticket.assigned_to_user_id = target.id
    return f"assigned ticket #{ticket.id} to {target.email}"


def _act_set_priority(db: Session, action: dict, ctx: dict) -> str:
    ticket = ctx.get("ticket")
    pri = action.get("priority")
    if ticket is None or pri not in PRIORITIES:
        return "set_priority skipped"
    ticket.priority = pri
    sla.stamp_due_dates(db, ticket)
    return f"set ticket #{ticket.id} priority={pri}"


def _act_add_note(db: Session, action: dict, ctx: dict) -> str:
    ticket = ctx.get("ticket")
    if ticket is None:
        return "add_note skipped (no ticket in context)"
    body = action.get("body") or "Automation note."
    db.add(TicketComment(ticket_id=ticket.id, author_email="automation@system",
                         author_role="system", body=body[:2000], internal=True))
    return f"added internal note to ticket #{ticket.id}"


# --------------------------------------------------------------------------- #
# Outbound-comms actions — reach a configured integration (never a device).
# They no-op gracefully (returning a "skipped: …" summary, not an error) when the
# integration isn't set up, so a rule is safe to define before you connect it.
# --------------------------------------------------------------------------- #
def _interpolate(text: str, ctx: dict) -> str:
    """Fill {hostname}/{client}/{message}/{subject}/{severity} from the context."""
    if not text:
        return text
    rep = {
        "{hostname}": str(ctx.get("hostname") or ""),
        "{message}": str(ctx.get("message") or ""),
        "{subject}": str(ctx.get("subject") or ""),
        "{severity}": str(ctx.get("severity") or ""),
        "{kind}": str(ctx.get("kind") or ""),
    }
    for k, v in rep.items():
        text = text.replace(k, v)
    return text


def _act_send_email(db: Session, action: dict, ctx: dict) -> str:
    to = action.get("to")
    if not to:
        return "send_email skipped (no 'to' configured)"
    from . import m365, secure_config
    conn = secure_config.get_platform(db, "m365_mailbox")
    cfg = (conn.config if conn else None) or {}
    if not secure_config.configured(cfg, ("tenant_id", "client_id", "client_secret")):
        return "send_email skipped (M365 mailbox not configured)"
    mailbox = cfg.get("mailbox")
    if not mailbox:
        return "send_email skipped (no default mailbox set)"
    subject = _interpolate(action.get("subject") or "Pulse automation", ctx)
    body = _interpolate(action.get("body") or _default_notify_message(ctx), ctx)
    try:
        graph = m365.GraphClient(
            str(secure_config.get_secret(cfg, "tenant_id") or cfg.get("tenant_id")),
            str(secure_config.get_secret(cfg, "client_id") or cfg.get("client_id")),
            str(secure_config.get_secret(cfg, "client_secret")))
        recipients = [a.strip() for a in str(to).split(",") if a.strip()]
        graph.send_mail(str(mailbox), recipients, subject, body, html=False)
    except m365.GraphError as e:
        return f"send_email failed: {e}"
    return f"emailed {to}"


def _act_linkedin_post(db: Session, action: dict, ctx: dict) -> str:
    text = _interpolate(action.get("text") or "", ctx)
    if not text.strip():
        return "linkedin_post skipped (no text configured)"
    from . import publishers, secure_config
    conn = secure_config.get_platform(db, "pub_linkedin")
    cfg = (conn.config if conn else None) or {}
    token = secure_config.get_secret(cfg, "access_token")
    urn = secure_config.get_secret(cfg, "person_urn") or cfg.get("person_urn")
    if not (token and urn):
        return "linkedin_post skipped (LinkedIn not configured)"
    try:
        pid = publishers.post_linkedin(str(token), str(urn), text, action.get("url") or "")
    except publishers.PublishError as e:
        return f"linkedin_post failed: {e}"
    return f"posted to LinkedIn ({pid})"


_HANDLERS = {
    ACTION_CREATE_TICKET: _act_create_ticket,
    ACTION_ACK_ALERT: _act_ack_alert,
    ACTION_NOTIFY: _act_notify,
    ACTION_ASSIGN: _act_assign,
    ACTION_SET_PRIORITY: _act_set_priority,
    ACTION_ADD_NOTE: _act_add_note,
    ACTION_SEND_EMAIL: _act_send_email,
    ACTION_LINKEDIN_POST: _act_linkedin_post,
}


def _run_actions(db: Session, rule: AutomationRule, ctx: dict) -> tuple[bool, str]:
    parts: list[str] = []
    ok = True
    for action in (rule.actions or []):
        handler = _HANDLERS.get(action.get("type"))
        if not handler:
            parts.append(f"unknown action '{action.get('type')}'")
            ok = False
            continue
        try:
            parts.append(handler(db, action, ctx))
        except Exception as exc:  # one bad action shouldn't abort the rest
            parts.append(f"{action.get('type')} error: {exc}")
            ok = False
    return ok, "; ".join(parts) if parts else "no actions"


# --------------------------------------------------------------------------- #
# Dispatch
# --------------------------------------------------------------------------- #
def dispatch(db: Session, trigger: str, context: dict) -> list[dict]:
    """Run all enabled rules for `trigger` whose scope+conditions match. Commits
    its own work. Returns a list of {rule_id, rule_name, success, summary}."""
    # Fan the event out to external webhook subscribers (the integration bus).
    # Best-effort and isolated so a slow/failing endpoint never blocks automation.
    try:
        from . import events
        events.emit(db, trigger, context, client_id=context.get("client_id"))
    except Exception:
        pass

    rules = (db.query(AutomationRule)
             .filter(AutomationRule.trigger == trigger, AutomationRule.enabled.is_(True))
             .all())
    results: list[dict] = []
    for rule in rules:
        # Scope: a rule with a client_id only fires for that client's events.
        if rule.client_id is not None and rule.client_id != context.get("client_id"):
            continue
        if not _matches(rule.conditions or {}, context):
            continue
        ok, summary = _run_actions(db, rule, context)
        rule.last_triggered_at = _now()
        rule.trigger_count = (rule.trigger_count or 0) + 1
        db.add(AutomationRun(rule_id=rule.id, rule_name=rule.name, trigger=trigger,
                             client_id=context.get("client_id"), success=ok, summary=summary))
        results.append({"rule_id": rule.id, "rule_name": rule.name, "success": ok, "summary": summary})

    if results:
        db.commit()
        # One audit entry per rule fired — automation actions are attributable.
        for r in results:
            audit.record(db, action="automation.run", actor_email="automation@system",
                         actor_role="system", target_type="automation_rule",
                         target_id=str(r["rule_id"]), client_id=context.get("client_id"),
                         detail=r["summary"][:500], success=r["success"])
    return results


# --------------------------------------------------------------------------- #
# Scheduled rules (trigger="schedule"). The schedule lives in `conditions`:
#   {"every":"hour"}                                  -> ~hourly
#   {"every":"day","at":"09:00","tz":"America/Chicago"}
#   {"every":"week","day":"mon","at":"09:00","tz":"America/Chicago"}
# Fired by the run-checks tick; dedup uses the rule's last_triggered_at.
# --------------------------------------------------------------------------- #
_WEEKDAYS = {"mon": 0, "tue": 1, "wed": 2, "thu": 3, "fri": 4, "sat": 5, "sun": 6}


def _aware(dt: datetime | None) -> datetime | None:
    if dt is not None and dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt


def schedule_due(cfg: dict, last: datetime | None, now: datetime) -> bool:
    """Pure: is a scheduled rule due to run at `now` given its last run?"""
    from datetime import timedelta
    try:
        from zoneinfo import ZoneInfo
        zone = ZoneInfo(cfg.get("tz") or "UTC")
    except Exception:  # noqa: BLE001
        zone = timezone.utc
    every = (cfg.get("every") or "day").lower()
    last = _aware(last)
    if every == "hour":
        return last is None or (now - last) >= timedelta(minutes=55)

    nowl = now.astimezone(zone)
    hh, mm = 9, 0
    at = cfg.get("at") or ""
    if ":" in at:
        try:
            hh, mm = int(at.split(":")[0]), int(at.split(":")[1])
        except ValueError:
            pass
    target = nowl.replace(hour=hh, minute=mm, second=0, microsecond=0)
    if nowl < target:
        return False                      # not yet time today
    if every == "week":
        want = _WEEKDAYS.get((cfg.get("day") or "mon")[:3].lower(), 0)
        if nowl.weekday() != want:
            return False
    if last is None:
        return True
    return last.astimezone(zone) < target  # haven't run since today's target time


def run_scheduled(db: Session, now: datetime | None = None) -> list[dict]:
    """Run every due scheduled rule. Commits. Returns the fired summaries."""
    now = now or _now()
    rules = (db.query(AutomationRule)
             .filter(AutomationRule.trigger == TRIGGER_SCHEDULE,
                     AutomationRule.enabled.is_(True)).all())
    fired: list[dict] = []
    for rule in rules:
        if not schedule_due(rule.conditions or {}, rule.last_triggered_at, now):
            continue
        ctx = {"client_id": rule.client_id, "scheduled": True,
               "subject": rule.name, "message": f"Scheduled: {rule.name}"}
        ok, summary = _run_actions(db, rule, ctx)
        rule.last_triggered_at = now
        rule.trigger_count = (rule.trigger_count or 0) + 1
        db.add(AutomationRun(rule_id=rule.id, rule_name=rule.name, trigger="schedule",
                             client_id=rule.client_id, success=ok, summary=summary))
        fired.append({"rule_id": rule.id, "rule_name": rule.name, "success": ok, "summary": summary})
    if fired:
        db.commit()
        for r in fired:
            audit.record(db, action="automation.scheduled", actor_email="automation@system",
                         actor_role="system", target_type="automation_rule",
                         target_id=str(r["rule_id"]), detail=r["summary"][:500], success=r["success"])
    return fired
