"""Server-side automation engine.

Rules react to platform EVENTS (an alert opening, a ticket being created, an SLA
breach) and take SAFE, in-platform ACTIONS — open a ticket, assign it, raise a
notification, set priority, add an internal note, acknowledge an alert. Nothing
here runs code on an endpoint or reaches outside OpsPilot; the agent stays
telemetry-only. Every rule that fires is recorded in `automation_runs` and the
audit log, so there's always an answer to "why did the system do that?".

Entry point: dispatch(db, trigger, context). Event sources build a context with
build_alert_context() / build_ticket_context() and call dispatch after their own
commit.
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy.orm import Session

from ..models import (
    ACTION_ACK_ALERT, ACTION_ADD_NOTE, ACTION_ASSIGN, ACTION_CREATE_TICKET,
    ACTION_NOTIFY, ACTION_SET_PRIORITY, Alert, AlertStatus, AutomationRule,
    AutomationRun, Device, Notification, PRIORITIES, STAFF_ROLES, SupportTicket,
    TicketComment, TicketStatus, User,
)
from . import audit, sla


def _now() -> datetime:
    return datetime.now(timezone.utc)


# --------------------------------------------------------------------------- #
# Context builders (kept here so event sources stay terse)
# --------------------------------------------------------------------------- #
def build_alert_context(alert: Alert, device: Device | None) -> dict:
    return {
        "client_id": alert.client_id, "alert": alert, "device": device,
        "alert_id": alert.id, "kind": alert.kind, "severity": alert.severity.value,
        "hostname": device.hostname if device else None,
    }


def build_ticket_context(ticket: SupportTicket) -> dict:
    return {
        "client_id": ticket.client_id, "ticket": ticket, "ticket_id": ticket.id,
        "priority": ticket.priority, "subject": ticket.subject,
        "status": ticket.status.value,
    }


# --------------------------------------------------------------------------- #
# Matching
# --------------------------------------------------------------------------- #
def _matches(conditions: dict, ctx: dict) -> bool:
    """Every condition key must equal the matching context value (string-lenient
    so JSON numbers compare cleanly)."""
    if not conditions:
        return True
    for k, v in conditions.items():
        cv = ctx.get(k)
        if cv != v and str(cv) != str(v):
            return False
    return True


# --------------------------------------------------------------------------- #
# Actions — each returns a short human summary string
# --------------------------------------------------------------------------- #
def _least_loaded_staff(db: Session) -> User | None:
    staff = db.query(User).filter(User.role.in_(list(STAFF_ROLES)), User.is_active.is_(True)).all()
    if not staff:
        return None
    open_states = [TicketStatus.OPEN, TicketStatus.IN_PROGRESS]
    return min(staff, key=lambda s: db.query(SupportTicket).filter(
        SupportTicket.assigned_to_user_id == s.id,
        SupportTicket.status.in_(open_states)).count())


def _act_create_ticket(db: Session, action: dict, ctx: dict) -> str:
    alert = ctx.get("alert")
    if alert is None:
        return "create_ticket skipped (no alert in context)"
    subject = (action.get("subject")
               or f"[Auto] {alert.kind} on {ctx.get('hostname') or 'device'}")
    priority = action.get("priority") or ("urgent" if ctx.get("severity") == "critical" else "normal")
    if priority not in PRIORITIES:
        priority = "normal"
    t = SupportTicket(client_id=alert.client_id, subject=subject[:200],
                      body=f"Auto-generated by automation from alert: {alert.message}",
                      priority=priority, created_at=_now())
    sla.stamp_due_dates(db, t)
    db.add(t)
    db.flush()  # get an id for the summary without committing
    return f"opened ticket #{t.id} ({priority})"


def _act_ack_alert(db: Session, action: dict, ctx: dict) -> str:
    alert = ctx.get("alert")
    if alert is None or alert.status == AlertStatus.RESOLVED:
        return "ack_alert skipped"
    alert.status = AlertStatus.ACKNOWLEDGED
    alert.acknowledged_at = _now()
    return f"acknowledged alert #{alert.id}"


def _act_notify(db: Session, action: dict, ctx: dict) -> str:
    msg = action.get("message") or _default_notify_message(ctx)
    severity = action.get("severity", ctx.get("severity", "info"))
    db.add(Notification(
        client_id=ctx.get("client_id"), target_user_id=action.get("user_id"),
        kind=action.get("kind", "automation"), severity=severity, message=msg[:1000],
    ))
    # Fan out to configured channels (email/Slack/Teams/webhook). Best-effort.
    from . import notifications as notif_svc
    sent = notif_svc.fanout(db, message=msg, severity=severity, client_id=ctx.get("client_id"))
    return f"raised notification (+{sent} channel(s))" if sent else "raised notification"


def _default_notify_message(ctx: dict) -> str:
    if ctx.get("alert") is not None:
        return f"{ctx.get('severity', 'info').upper()} alert: {ctx['alert'].message}" + (
            f" on {ctx['hostname']}" if ctx.get("hostname") else "")
    if ctx.get("ticket") is not None:
        return f"Ticket #{ctx.get('ticket_id')}: {ctx.get('subject')}"
    return "Automation notification"


def _act_assign(db: Session, action: dict, ctx: dict) -> str:
    ticket = ctx.get("ticket")
    if ticket is None:
        return "assign skipped (no ticket in context)"
    if action.get("auto"):
        target = _least_loaded_staff(db)
        if not target:
            return "assign skipped (no staff available)"
    else:
        uid = action.get("user_id")
        target = db.get(User, uid) if uid else None
        if not target or target.role not in STAFF_ROLES:
            return "assign skipped (invalid assignee)"
    ticket.assigned_to_user_id = target.id
    return f"assigned ticket #{ticket.id} to {target.email}"


def _act_set_priority(db: Session, action: dict, ctx: dict) -> str:
    ticket = ctx.get("ticket")
    pri = action.get("priority")
    if ticket is None or pri not in PRIORITIES:
        return "set_priority skipped"
    ticket.priority = pri
    sla.stamp_due_dates(db, ticket)
    return f"set ticket #{ticket.id} priority={pri}"


def _act_add_note(db: Session, action: dict, ctx: dict) -> str:
    ticket = ctx.get("ticket")
    if ticket is None:
        return "add_note skipped (no ticket in context)"
    body = action.get("body") or "Automation note."
    db.add(TicketComment(ticket_id=ticket.id, author_email="automation@system",
                         author_role="system", body=body[:2000], internal=True))
    return f"added internal note to ticket #{ticket.id}"


_HANDLERS = {
    ACTION_CREATE_TICKET: _act_create_ticket,
    ACTION_ACK_ALERT: _act_ack_alert,
    ACTION_NOTIFY: _act_notify,
    ACTION_ASSIGN: _act_assign,
    ACTION_SET_PRIORITY: _act_set_priority,
    ACTION_ADD_NOTE: _act_add_note,
}


def _run_actions(db: Session, rule: AutomationRule, ctx: dict) -> tuple[bool, str]:
    parts: list[str] = []
    ok = True
    for action in (rule.actions or []):
        handler = _HANDLERS.get(action.get("type"))
        if not handler:
            parts.append(f"unknown action '{action.get('type')}'")
            ok = False
            continue
        try:
            parts.append(handler(db, action, ctx))
        except Exception as exc:  # one bad action shouldn't abort the rest
            parts.append(f"{action.get('type')} error: {exc}")
            ok = False
    return ok, "; ".join(parts) if parts else "no actions"


# --------------------------------------------------------------------------- #
# Dispatch
# --------------------------------------------------------------------------- #
def dispatch(db: Session, trigger: str, context: dict) -> list[dict]:
    """Run all enabled rules for `trigger` whose scope+conditions match. Commits
    its own work. Returns a list of {rule_id, rule_name, success, summary}."""
    # Fan the event out to external webhook subscribers (the integration bus).
    # Best-effort and isolated so a slow/failing endpoint never blocks automation.
    try:
        from . import events
        events.emit(db, trigger, context, client_id=context.get("client_id"))
    except Exception:
        pass

    rules = (db.query(AutomationRule)
             .filter(AutomationRule.trigger == trigger, AutomationRule.enabled.is_(True))
             .all())
    results: list[dict] = []
    for rule in rules:
        # Scope: a rule with a client_id only fires for that client's events.
        if rule.client_id is not None and rule.client_id != context.get("client_id"):
            continue
        if not _matches(rule.conditions or {}, context):
            continue
        ok, summary = _run_actions(db, rule, context)
        rule.last_triggered_at = _now()
        rule.trigger_count = (rule.trigger_count or 0) + 1
        db.add(AutomationRun(rule_id=rule.id, rule_name=rule.name, trigger=trigger,
                             client_id=context.get("client_id"), success=ok, summary=summary))
        results.append({"rule_id": rule.id, "rule_name": rule.name, "success": ok, "summary": summary})

    if results:
        db.commit()
        # One audit entry per rule fired — automation actions are attributable.
        for r in results:
            audit.record(db, action="automation.run", actor_email="automation@system",
                         actor_role="system", target_type="automation_rule",
                         target_id=str(r["rule_id"]), client_id=context.get("client_id"),
                         detail=r["summary"][:500], success=r["success"])
    return results
