"""Library Forge content — operational sets: audit checklists, security
standards, training one-pagers, forms, runbooks, and client-facing service
descriptions. 66 documents, all data-driven through compact builders.
"""

CAT_CHK = ("CHK", "Audit & Assessment Checklists")
CAT_SEC2 = ("STD", "Security Standards")
CAT_TRN = ("TRN", "Security Awareness One-Pagers")
CAT_FRM = ("FRM", "Operational Forms")
CAT_SOP = ("SOP", "Runbooks & SOPs (Extended)")
CAT_AGR = ("SVC", "Client Service Descriptions")


def _chk(n, slug, title, summary, items):
    return {"id": f"BVT-CHK-{n}", "slug": slug, "title": title,
            "category": CAT_CHK[0], "category_label": CAT_CHK[1],
            "visibility": "internal", "kind": "checklist", "summary": summary,
            "sections": [
                {"h": "Checklist", "kind": "checks", "body": items},
                {"h": "Sign-off", "kind": "fills",
                 "body": ["Performed by:", "Client / site:", "Date:", "Notes / exceptions:"]}]}


CHECKLISTS = [
    ("220", "New_Client_Security_Audit", "New-Client Security Audit",
     "The first-visit audit that turns a prospect into a scoped, priced, defensible engagement.",
     ["Domain email authentication reviewed (SPF, DKIM, DMARC)", "MFA status on email/identity platform",
      "Admin account inventory - who has the keys", "Endpoint inventory with OS support status",
      "Patch level sample across workstations and servers", "Antivirus/EDR presence and management status",
      "Backup existence, destinations, and last verified restore", "Firewall model, firmware, and rule review",
      "Wi-Fi security (WPA2/3, guest separation, default creds)", "Server room / network closet physical access",
      "Shared credentials and password practices interview", "Departed-employee account check",
      "Cloud services in use (sanctioned and shadow)", "Compliance regime identification (HIPAA/4557/Safeguards)",
      "Cyber-insurance policy and its security requirements", "Findings ranked and priced into remediation proposal"]),
    ("221", "Microsoft_365_Hardening", "Microsoft 365 Hardening Checklist",
     "The tenant-hardening pass run at onboarding and re-verified quarterly.",
     ["Security defaults or conditional access enforced", "MFA registered for every licensed user",
      "Legacy authentication protocols blocked", "Admin roles reviewed; global admins minimized (2-4) with break-glass account",
      "Unified audit logging confirmed on", "Mailbox forwarding rules audited for exfiltration",
      "Anti-phishing, safe links, and safe attachments policies applied", "External sender tagging enabled",
      "SharePoint/OneDrive external sharing scoped", "DKIM enabled for all custom domains",
      "DMARC policy published and monitored", "Secure Score reviewed and improvement plan noted"]),
    ("222", "Firewall_Network_Review", "Firewall & Network Review Checklist",
     "Quarterly review of every managed edge device and network segment.",
     ["Firmware current and under support", "Admin access restricted to management VLAN + MFA where supported",
      "Default credentials eliminated", "Rule base reviewed - unused and any-any rules removed",
      "Geo-blocking and threat feeds active where licensed", "VPN configuration reviewed (protocols, users, MFA)",
      "Guest network isolated from production", "IoT devices segmented", "Logging shipped to retained storage",
      "Config backup exported and stored", "Open ports externally scanned and justified"]),
    ("223", "Backup_Verification", "Backup Verification & Restore-Test Checklist",
     "The monthly proof that backups are real: an actual restore, documented.",
     ["All protected systems present in backup jobs", "Job success rate reviewed for the period",
      "Alert on failure verified working", "Test restore performed of a file set", "Test restore of a full system/VM (quarterly)",
      "Restore timing recorded against the client RTO", "Offsite/immutable copy verified",
      "Encryption of backup data confirmed", "Retention matches the client policy", "Restore evidence filed in the client record"]),
    ("224", "Active_Directory_Review", "Active Directory / Entra Review Checklist",
     "Identity hygiene review: the accounts, groups, and privileges attackers hunt first.",
     ["Stale accounts (90+ days) disabled", "Service accounts inventoried with owners and rotation dates",
      "Domain/Global admins reviewed and minimized", "Privileged group nesting audited",
      "Password policy matches standard (length, breach-list, lockout)", "Kerberoastable/legacy-auth exposure checked",
      "GPO/Intune baseline drift reviewed", "Local admin rights inventoried and justified"]),
    ("225", "Employee_Offboarding_IT", "Employee Offboarding (IT) Checklist",
     "Same-day access termination, evidenced - the control auditors always ask about.",
     ["HR trigger received with last-day timestamp", "Identity account disabled (AD/Entra)",
      "MFA methods and app passwords revoked", "Email delegated or forwarded per manager request",
      "Shared/service credentials the person knew rotated", "VPN and remote access revoked",
      "SaaS and line-of-business app access removed", "Company equipment recovered on custody form",
      "Mobile device wiped or work profile removed", "Building/physical access returned", "Completion recorded with times"]),
    ("226", "Employee_Onboarding_IT", "Employee Onboarding (IT) Checklist",
     "Day-one productivity with least privilege from the start.",
     ["Identity created from role template (least privilege)", "MFA enrolled before first login",
      "Device imaged from hardened baseline with EDR", "Email, groups, and shares per role matrix",
      "Security training assigned in Cyber Academy", "Confidentiality/AUP acknowledgment signed",
      "Password manager provisioned", "Manager confirms access is sufficient and not excessive"]),
    ("227", "Patch_Compliance_Audit", "Patch Compliance Audit Checklist",
     "Monthly patch posture across the fleet with the exceptions documented.",
     ["RMM patch policy coverage - every endpoint enrolled", "OS patch compliance percentage recorded",
      "Third-party app patching status", "Failed-patch devices remediated or ticketed",
      "KEV-listed vulnerabilities checked against fleet", "Servers rebooted within maintenance windows",
      "Out-of-support systems listed with retirement plans", "Exception list reviewed and re-approved"]),
    ("228", "Email_Security_Audit", "Email Security Audit Checklist",
     "The channel where attacks actually arrive - audited end to end.",
     ["SPF record valid and single", "DKIM signing verified on all sending domains", "DMARC at quarantine/reject with reporting",
      "Inbound filtering policies reviewed", "External-sender banner active", "Auto-forwarding to external audited",
      "Transport rules reviewed for tampering", "Breached-credential check for tenant accounts",
      "Executive impersonation protection configured", "User-reported-phish workflow tested"]),
    ("229", "Endpoint_Hardening", "Endpoint Hardening Checklist",
     "The workstation baseline applied at deployment and verified by audit.",
     ["Disk encryption enforced and recovery keys escrowed", "Local admin removed from daily users",
      "EDR installed, healthy, reporting", "Screen lock at 15 minutes with password",
      "OS and firmware current", "Unsupported/unauthorized software removed", "USB storage policy applied",
      "Browser hardening and DNS filtering active", "Device enrolled in RMM and inventory tagged"]),
    ("230", "Network_Documentation", "Network Documentation Standard Checklist",
     "What complete client documentation looks like - audited quarterly.",
     ["Network diagram current (edge, switches, VLANs, Wi-Fi, servers)", "IP schema and DHCP scopes recorded",
      "Credential vault entries complete and tested", "ISP accounts and circuit IDs recorded",
      "Domain registrar and DNS host access documented", "License and warranty inventory current",
      "Vendor support contacts listed", "Runbook links attached to client record"]),
    ("231", "Physical_Security_Walkthrough", "Physical Security Walkthrough Checklist",
     "The on-site sweep for the controls no scanner can see.",
     ["Server/network equipment behind locked doors", "Visitor handling and escort practice observed",
      "Workstation screens locked when unattended", "Sensitive paper secured; clean-desk spot check",
      "Backup media/appliances physically secured", "Alarm and camera coverage of IT areas",
      "Key/badge inventory reconciled", "UPS units present, tested, not overloaded"]),
    ("232", "WiFi_Security_Audit", "Wi-Fi Security Audit Checklist",
     "Wireless posture: the perimeter that walks through walls.",
     ["Management access to APs secured and MFA'd where supported", "WPA2-Enterprise/WPA3 on corporate SSID",
      "Pre-shared keys rotated and complexity-checked", "Guest SSID isolated with no LAN reachability",
      "Rogue AP scan performed", "Coverage vs. bleed reviewed (power tuning)", "Firmware current",
      "IoT devices on dedicated SSID/VLAN"]),
    ("233", "MFA_Rollout", "MFA Rollout Checklist",
     "The highest-ROI project in security, executed without lockouts.",
     ["Scope: identity, email, VPN, remote access, finance, admin tools", "Method chosen (app push/TOTP/keys) with SMS as last resort",
      "Break-glass accounts excluded and vaulted", "Pilot group enrolled and issues cleared",
      "Staged enforcement dates communicated", "Enrollment status tracked to 100%",
      "Legacy protocols blocked after enforcement", "Helpdesk reset/re-enroll procedure documented"]),
    ("234", "Server_Decommission", "Server Decommission Checklist",
     "Retiring a server without orphaned dependencies or data leaks.",
     ["Dependency map reviewed (apps, shares, prints, DNS, scripts)", "Data migrated and verified",
      "Backups of final state retained per schedule", "Services/DNS records repointed", "Licenses reclaimed",
      "Monitoring/RMM/AV agents removed", "Disks sanitized per NIST 800-88 with certificate", "Asset record closed"]),
    ("235", "Vendor_Security_Review", "Vendor Security Review Checklist",
     "The supply-chain gate: run before any vendor touches client data.",
     ["Data accessed/stored by vendor classified", "Security attestations requested (SOC 2/ISO/assessment)",
      "Breach history searched", "MFA/SSO support confirmed", "Data location and encryption confirmed",
      "Contract includes security, breach-notice, and deletion terms (DPA where personal data)",
      "Offboarding/data-return path defined", "Renewal review date set"]),
    ("236", "Incident_Readiness_Drill", "Incident Readiness Drill Checklist",
     "The annual tabletop that proves the IR plan works before it's needed.",
     ["Scenario selected (ransomware/BEC/lost device)", "Participants and roles per the IRP",
      "Contact tree exercised (carrier, counsel, clients)", "Backup restore demonstrated during drill",
      "Notification clocks walked (Texas Sec. 521.053, HIPAA if applicable)", "Gaps captured with owners",
      "POA&M items opened", "Executive debrief delivered"]),
    ("237", "Annual_Policy_Review", "Annual Policy Review Checklist",
     "The governance heartbeat: every policy touched, dated, and re-approved yearly.",
     ["Library inventory reconciled against manifest", "Each policy reviewed by owner with change notes",
      "Regulatory changes swept (Texas, FTC, IRS, HIPAA)", "Version numbers and effective dates advanced",
      "Re-approval signatures captured", "Superseded versions archived", "Staff re-acknowledgment where material",
      "Client-shareable set republished to the portal"]),
]

STANDARDS = [
    ("240", "AI_Acceptable_Use_Standard", "AI Acceptable Use Standard",
     "Rules for using AI tools without leaking client data or shipping unreviewed output.",
     [("Approved tools", "Only company-approved AI services may process business data; client-identifiable data enters an AI tool only when the tool is under contract (DPA) and approved in writing."),
      ("Prohibited inputs", "Credentials, client PII/PHI, financials, and incident details never go into consumer AI tools."),
      ("Human review", "AI-drafted client deliverables, code, and legal text receive qualified human review before use."),
      ("Disclosure & records", "Material AI assistance in client work is disclosed when contract or professional duty requires; prompts containing business data are treated as records."),
      ("Shadow AI", "Unapproved AI browser extensions and plugins are treated as unauthorized software and removed.")]),
    ("241", "Encryption_Standard", "Encryption Standard",
     "Approved algorithms and required coverage - the one-page answer to 'is it encrypted?'",
     [("In transit", "TLS 1.2+ everywhere; TLS 1.3 preferred; plaintext protocols (FTP, telnet, HTTP for auth) prohibited."),
      ("At rest", "AES-256 (or platform equivalent) on laptops, portable media, backups, and cloud storage holding sensitive data; recovery keys escrowed in the credential vault."),
      ("Email", "Sensitive attachments go via encrypted portal or message encryption - never bare SMTP."),
      ("Key management", "Keys and recovery secrets live only in the managed vault, access-logged, rotated on personnel change."),
      ("Deprecated", "SSLv3/TLS1.0/1.1, SHA-1 certificates, WEP/WPA-TKIP, and proprietary 'encoding' are prohibited.")]),
    ("242", "Logging_Monitoring_Standard", "Logging & Monitoring Standard",
     "What gets logged, how long it lives, and what pages a human.",
     [("Sources", "Identity platforms, endpoints (EDR), firewalls, servers, backup jobs, and the OpsPilot portal audit log."),
      ("Retention", "Security logs retained a minimum of 12 months; incident-relevant logs preserved for the life of the matter."),
      ("Time", "All sources synchronize to authoritative NTP so timelines correlate."),
      ("Alerting", "Severity definitions route alerts: critical pages on-call immediately; high within 1 hour; the daily digest sweeps the rest."),
      ("Review", "Weekly triage of security events; monthly metric review in the portal; findings feed the POA&M.")]),
    ("243", "Password_Authentication_Standard", "Password & Authentication Standard",
     "The measurable rules behind 'strong passwords + MFA'.",
     [("Length first", "Minimum 14 characters for users, 20 for admins/service accounts; passphrases encouraged; complexity theater avoided."),
      ("Breached-password screening", "New and reset passwords screen against known-breach lists; matches are rejected."),
      ("MFA", "Required for email, identity, VPN, remote access, admin tools, and finance systems; app-based or hardware-key methods preferred over SMS."),
      ("Storage", "Passwords live only in the managed vault - never in spreadsheets, notes, or browsers on shared machines."),
      ("Rotation", "Rotate on compromise indicators and personnel change, not on arbitrary calendars; service accounts rotate at least annually."),
      ("Lockout", "10 failed attempts locks for 15 minutes with alerting on bursts.")]),
    ("244", "Secure_Configuration_Baseline", "Secure Configuration Baseline Standard",
     "The default state of every managed device - deviation is an exception with an owner.",
     [("Workstations", "Encrypted disk, standard-user daily accounts, EDR, screen lock, current OS, RMM-enrolled, hardening template applied."),
      ("Servers", "Role-minimal installs, patched, monitored, backed up, admin access via named accounts, RDP never exposed to the internet."),
      ("Network devices", "Unique credentials, current firmware, config backups, management on a dedicated VLAN, logging enabled."),
      ("SaaS tenants", "MFA enforced, audit logs on, least-privilege roles, external sharing scoped, offboarding integrated."),
      ("Exceptions", "Any deviation is documented in the risk register with a compensating control and review date.")]),
    ("245", "Data_Classification_Standard", "Data Classification & Handling Standard",
     "Four classes, unambiguous handling - so 'sensitive' stops being a vibe.",
     [("Public", "Approved for release (marketing, published posts). No handling restrictions."),
      ("Internal", "Business information not for release (procedures, pricing). Company systems only."),
      ("Confidential", "Client business data, contracts, credentials metadata. Encrypted at rest and in transit; need-to-know access; portal-based sharing."),
      ("Restricted", "Regulated data: PHI, taxpayer data, card data, credentials. All Confidential controls plus logging, minimal copies, named access, and certified destruction."),
      ("Labeling", "Documents carry their class in the footer; systems inherit the highest class they store.")]),
    ("246", "Email_Authentication_Standard", "Email Authentication Standard (SPF/DKIM/DMARC)",
     "The standard BVTech runs on its own domains and deploys for every client.",
     [("SPF", "Exactly one SPF record per domain, ending -all, listing only genuine senders; flattened when lookup limits threaten."),
      ("DKIM", "All outbound mail signed; selectors documented; keys 2048-bit; rotation on provider guidance."),
      ("DMARC", "Exactly one DMARC record; policy quarantine or reject (never long-term none); aggregate reports monitored; subdomain policy explicit."),
      ("Non-sending domains", "Parked domains get SPF '-all', an empty DKIM posture, and DMARC reject so they can't be spoofed."),
      ("Verification", "Authentication posture is checked at onboarding, quarterly, and automatically in the new-client audit.")]),
    ("247", "Remote_Access_Standard", "Remote Access Standard",
     "Every path into a managed network, enumerated and controlled.",
     [("Approved paths", "Company VPN with MFA, vendor-supported remote tools with per-session consent, and the RMM's audited remote control. Everything else - especially exposed RDP - is prohibited."),
      ("Device posture", "Remote access requires a managed, encrypted, EDR-protected device; personal devices use virtual desktop or web-only access."),
      ("Session controls", "Sessions log user, source, and duration; idle sessions terminate; vendor access is time-boxed and sponsored."),
      ("Home networks", "Technicians follow the remote-work standard: WPA2/3, updated router firmware, no shared household use of work devices."),
      ("Revocation", "Remote access dies with the account - offboarding removes VPN, RMM, and tool access same-day.")]),
]

TRAININGS = [
    ("250", "Phishing", "Spotting Phishing", "The five tells in every phish and the 30-second verification habit.",
     ["Urgency is the weapon: 'right now', 'before 5pm', 'don't tell anyone' - slow down exactly when pushed to hurry.",
      "Check the actual address, not the display name - one letter off is a different domain.",
      "Hover every link before clicking; mismatched destinations end the conversation.",
      "Unexpected attachments get verified by a second channel - call the sender on a number you already have.",
      "Report it: one click to your reporting button beats deleting it - it protects everyone else too."]),
    ("251", "Passwords_MFA", "Passwords & MFA", "Long beats complex, unique beats clever, MFA beats both.",
     ["Length is strength: a 4-word passphrase beats P@ssw0rd! every time.",
      "One account, one password - reuse is how one breach becomes ten.",
      "The password manager remembers so you don't have to; use it for everything.",
      "MFA prompts you didn't trigger are attacks: deny and report, never approve to make it stop.",
      "Never share a code with anyone - no legitimate caller will ever ask."]),
    ("252", "Ransomware", "Ransomware Basics", "How it gets in, what it looks like, and the first five minutes.",
     ["It arrives like any phish - one enabled macro or fake update is enough.",
      "Mass file renames, weird extensions, or a ransom note mean disconnect from the network - don't shut down, don't 'fix' it.",
      "Call the helpdesk immediately; minutes decide how far it spreads.",
      "Backups are the antidote - which is why attackers hunt them; ours are tested and offsite.",
      "Never negotiate or pay on your own; that decision involves counsel, carrier, and leadership."]),
    ("253", "BEC_Wire_Fraud", "Business Email Compromise & Wire Fraud", "The most expensive attack per incident - and the phone call that defeats it.",
     ["A changed bank account, a rushed invoice, an executive asking for gift cards: classic BEC.",
      "Verify EVERY payment-detail change by phone using a number you already had - never the one in the email.",
      "Check reply-to addresses; compromised threads look legitimate because they are - the account is stolen.",
      "Dual approval on payments above threshold is policy, not bureaucracy.",
      "Seconds matter after a bad transfer: report instantly - recalls sometimes work in the first hours."]),
    ("254", "Social_Engineering", "Social Engineering Beyond Email", "Phone, text, and walk-in attacks - same con, different channel.",
     ["'IT support' calling to fix a problem you didn't report isn't IT support.",
      "Smishing texts about packages and payroll aim at your phone because it has fewer defenses - same rules apply.",
      "Tailgating is friendly: hold the door for people you know; badge everyone else.",
      "QR codes are links wearing a costume - preview before opening.",
      "Verification isn't rudeness; real colleagues and vendors expect it."]),
    ("255", "Safe_Browsing", "Safe Browsing & Downloads", "The web habits that keep malware out of the building.",
     ["Download software only from vendor sites or the company portal - 'free download' aggregators bundle malware.",
      "Fake browser updates and 'your PC is infected' popups install exactly what they claim to fix - close and report.",
      "Search-ad results can impersonate real vendors; type known addresses or use bookmarks for sensitive logins.",
      "Extensions are software with full page access - install only what's approved.",
      "The padlock means encrypted, not honest - phishing sites use HTTPS too."]),
    ("256", "Mobile_Devices", "Mobile Device Security", "The office in your pocket, protected like one.",
     ["Screen lock + biometrics, always; a lost unlocked phone is a lost mailbox.",
      "Install updates when offered - mobile exploits are patched by them weekly.",
      "Apps come from official stores only, and even then check the publisher.",
      "Public USB charging can be data-hostile; carry your own charger or use a data blocker.",
      "Report lost/stolen devices immediately - remote wipe wins races."]),
    ("257", "Travel_Security", "Travel Security", "Working from anywhere without leaking from everywhere.",
     ["Public Wi-Fi is fine for coffee menus, not for client work - use the VPN or hotspot.",
      "Privacy screens defeat shoulder surfing on planes and in lobbies.",
      "Devices stay on your person or locked in the safe - never checked luggage or car seats.",
      "Border crossings with client data follow the travel-device procedure - ask before you fly.",
      "Assume hotel networks are hostile; the VPN isn't optional there."]),
    ("258", "Remote_Work", "Remote Work Security", "Home-office rules that keep client trust intact.",
     ["Work happens on work devices; family members and personal browsing stay off them.",
      "Home Wi-Fi: WPA2/3, a real router password, and current firmware - we'll help you check.",
      "Lock the screen when you walk away, even at home; kids and cats deploy surprising keystrokes.",
      "Sensitive calls happen where smart speakers and visitors can't listen.",
      "Company data lives in company systems - never on personal drives 'just to finish tonight'."]),
    ("259", "Data_Handling", "Handling Sensitive Data", "Classification in practice: what goes where, and what never leaves.",
     ["Know your classes: Public, Internal, Confidential, Restricted - when unsure, treat it one class higher.",
      "Client data moves through the portal or encrypted email - never personal accounts or USB sticks.",
      "Restricted data (PHI, taxpayer, card, credentials) gets logged access and minimal copies.",
      "Paper counts: sensitive printouts live in locked drawers and die in the shredder.",
      "Deleting isn't destroying - certified sanitization handles retired media."]),
    ("260", "Physical_Security", "Physical Security Habits", "The controls that work when the network isn't the target.",
     ["Badge in personally; everyone badges - politeness holds doors, policy checks badges.",
      "Clean desk at day's end: sensitive paper locked, screens locked, keys pocketed.",
      "Visitors are escorted, logged, and never left alone near equipment.",
      "Found USB drives go to IT unopened - curiosity is the exploit.",
      "Unfamiliar faces in secure areas get a friendly 'can I help you?' and a report."]),
    ("261", "Incident_Reporting", "Reporting Security Incidents", "The no-blame rule that makes everything else work.",
     ["If something feels wrong, report it - clicked links, odd prompts, missing devices, weird account behavior.",
      "Speed beats certainty: an early false alarm is free; a late real one is expensive.",
      "Reporting a mistake you made is protected here - hiding one isn't.",
      "Know the channel: helpdesk ticket, the security email, or a human - whatever is fastest right now.",
      "After reporting, preserve: don't delete emails, reinstall, or 'clean up' - evidence helps everyone."]),
]

FORMS = [
    ("262", "Visitor_Log", "Visitor Log", "form",
     ["Date:", "Visitor name:", "Company:", "Purpose:", "Escorted by:", "Time in:", "Time out:", "Badge #:"]),
    ("263", "Media_Destruction_Certificate", "Certificate of Media Destruction", "form",
     ["Client / owner:", "Media description & serials:", "Data classification:",
      "Destruction method (NIST 800-88):", "Performed by:", "Witnessed by:", "Date:", "Certificate #:"]),
    ("264", "Incident_Report_Form", "Security Incident Report Form", "form",
     ["Incident #:", "Reported by / date-time:", "Detected how:", "Systems & data affected:",
      "Classification (malware/BEC/loss/other):", "Actions taken & times:", "Client notified? when:",
      "Texas Sec. 521.053 assessment done:", "Incident commander:", "Status / closed date:"]),
    ("265", "Change_Request_Form", "Change Request Form", "form",
     ["Change #:", "Requested by:", "Systems affected:", "Description & reason:",
      "Risk & rollback plan:", "Maintenance window:", "Approved by:", "Implemented by / date:", "Verified by:"]),
    ("266", "Access_Request_Form", "Access Request Form", "form",
     ["Requested for:", "Role / manager:", "Systems & permission level:", "Business justification:",
      "Duration (permanent/temporary until):", "Approved by:", "Provisioned by / date:", "Review date:"]),
    ("267", "Policy_Exception_Request", "Policy Exception Request Form", "form",
     ["Exception #:", "Policy / standard affected:", "Requested by:", "Business justification:",
      "Risk introduced:", "Compensating controls:", "Expiration date:", "Approved by (Managing Partner):", "Risk register entry #:"]),
    ("268", "Equipment_Custody_Form", "Equipment Custody Form", "form",
     ["Employee:", "Asset tag / serial:", "Equipment description:", "Condition at issue:",
      "Issued by / date:", "Employee signature:", "Returned date / condition:", "Received by:"]),
    ("269", "Vendor_Intake_Form", "Vendor Security Intake Form", "form",
     ["Vendor name:", "Service provided:", "Data accessed/stored:", "Data location(s):",
      "Attestations provided (SOC2/ISO/other):", "MFA/SSO supported:", "DPA/BAA signed:",
      "Security contact:", "Review performed by / date:", "Approved:"]),
    ("270", "BYOD_Agreement_Form", "BYOD Acknowledgment & Agreement", "form",
     ["Employee:", "Device description:", "Work profile/MDM installed:", "Employee acknowledges: remote wipe of work data, "
      "encryption requirement, immediate loss reporting, removal on separation:", "Employee signature / date:", "Approved by:"]),
    ("271", "Termination_Access_Form", "Termination Access-Removal Record", "form",
     ["Employee:", "Last day / time:", "Identity disabled (by/time):", "MFA revoked:", "Email handled (delegate/forward):",
      "Shared credentials rotated:", "SaaS access removed:", "Equipment recovered:", "Completed by / date:"]),
]

RUNBOOKS = [
    ("280", "New_Workstation_Deployment", "New Workstation Deployment",
     ["Verify order against the client's standard hardware profile", "Image from the current hardened baseline",
      "Join identity platform and apply role group memberships", "Confirm disk encryption active; escrow recovery key",
      "Install EDR + RMM agents; verify check-in", "Apply printer/share mappings from the client runbook",
      "Migrate user data per checklist; verify counts", "Enroll user MFA at handoff; deliver quick-start sheet",
      "Tag asset, update inventory, attach custody form"]),
    ("281", "M365_Tenant_Onboarding", "Microsoft 365 Tenant Onboarding",
     ["Capture global admin access into the vault; create break-glass account", "Enforce MFA/conditional access per hardening checklist",
      "Block legacy auth; verify no failures for line-of-business apps", "Configure mail hygiene policies and external tagging",
      "Publish SPF; enable DKIM; set DMARC per the email standard", "Enable unified audit logging; connect alerting",
      "Baseline Secure Score; record improvement plan", "Document tenant in client record with license map"]),
    ("282", "Backup_Restore_Test", "Backup Restore Test (Quarterly)",
     ["Select restore scope: sampled files + one full system alternated quarterly", "Restore to isolated target - never overwrite production",
      "Verify integrity: open files, boot system, check application data", "Time the restore; compare against client RTO",
      "Record evidence (screenshots, timings) into the client record", "Ticket any failure as priority remediation",
      "Update the backup verification checklist and sign off"]),
    ("283", "Phishing_Triage", "Reported Phishing Triage",
     ["Acknowledge the reporter - fast, positive reinforcement", "Analyze headers, links, and attachments in the sandbox",
      "Search the tenant for other recipients of the same message", "Purge confirmed-malicious messages tenant-wide",
      "Check for clicks/credential entry; force resets and session revocation on hits", "Block sender/domain/URL as indicated",
      "Log outcome; escalate to incident if compromise indicated", "Feed lure into next awareness cycle"]),
    ("284", "VPN_User_Setup", "VPN User Setup",
     ["Verify access approval on file", "Create VPN account tied to identity (no shared accounts)",
      "Enforce MFA binding before first connection", "Issue client config via secure channel - never plain email",
      "Verify device posture: managed, encrypted, EDR", "Test tunnel and reachable-scope; confirm least privilege",
      "Record in access inventory with review date"]),
    ("285", "Printer_Deployment", "Printer / MFP Deployment",
     ["Change default admin credentials; record in vault", "Update firmware", "Static IP/reservation per schema",
      "Disable unused protocols and cloud features", "Configure scan-to destinations with least-privilege service account",
      "Deploy queue via management platform", "Verify hard-disk overwrite/encryption settings on MFPs",
      "Add to inventory and monitoring"]),
    ("286", "Email_Migration", "Email Migration (to M365)",
     ["Inventory mailboxes, aliases, groups, and mail flow oddities", "Pre-stage licensing and DNS cutover plan",
      "Sync/import mail with verification counts", "Cut MX in the planned window; monitor queues both sides",
      "Verify SPF/DKIM/DMARC for the new path", "Reconnect mobile devices and shared mailboxes",
      "Hypercare window with rapid-response contact", "Decommission legacy per server decommission checklist"]),
    ("287", "Workstation_Refresh_Cycle", "Workstation Refresh Cycle",
     ["Pull age/health report from RMM; flag 4-year-plus units", "Prioritize by failure risk and user impact",
      "Quote refresh batch with client budget owner", "Schedule deployments via the new-workstation runbook",
      "Sanitize and certify retired units (NIST 800-88)", "Update inventory and warranty records",
      "Report completion in the QBR"]),
    ("288", "NAS_Storage_Deployment", "NAS / Shared Storage Deployment",
     ["Update firmware before first data", "Disable default admin; create named admin in vault",
      "RAID level per capacity/redundancy target; document", "Bind shares to identity platform - no local-only users",
      "Least-privilege share/NTFS mapping from role matrix", "Enable snapshots; integrate into backup jobs",
      "Disable internet-exposed services (no vendor cloud relay unless approved)", "Add to monitoring and inventory"]),
    ("289", "Power_UPS_Maintenance", "UPS & Power Protection Maintenance",
     ["Inventory UPS units, ages, and load", "Self-test each unit; record runtime", "Replace batteries past service life",
      "Verify graceful-shutdown integration on protected servers", "Confirm network cards monitored",
      "Check load headroom after equipment changes", "Record next service date"]),
]

SERVICES = [
    ("290", "Managed_IT", "Managed IT Services",
     "Complete care of your technology: monitoring, patching, helpdesk, and on-site support under one predictable monthly agreement.",
     ["24/7 monitoring with proactive alerting on every covered device", "Patch management for OS and key applications",
      "Unlimited remote helpdesk during business hours; defined SLAs", "Hardened baseline configuration on every endpoint",
      "Asset inventory, warranty tracking, and lifecycle budgeting", "Quarterly business reviews with the posture scorecard"]),
    ("291", "Managed_Security", "Managed Security (MSSP)",
     "Detection and response on top of managed IT: EDR, email defense, and a tested incident plan with Texas notification clocks built in.",
     ["Managed EDR on every endpoint with 24/7 alert triage", "Email security: filtering, impersonation protection, DKIM/DMARC",
      "Security awareness training with quarterly phishing simulation", "Vulnerability visibility tied to the CISA KEV catalog",
      "Incident response retainer - the plan, the playbooks, the drill", "Compliance evidence pack aligned to NIST CSF 2.0"]),
    ("292", "Backup_DR", "Backup & Disaster Recovery",
     "The 3-2-1 discipline with proof: local speed, offsite safety, and restores we actually test.",
     ["Image-based server backup with local + offsite/immutable copies", "Workstation and M365 data protection options",
      "Documented RTO/RPO per system, agreed with you", "Quarterly restore tests with evidence in your record",
      "Ransomware-resilient retention and encryption", "Annual DR tabletop for covered environments"]),
    ("293", "M365_Management", "Microsoft 365 Management",
     "Your tenant, hardened and tended: identity, mail hygiene, and the settings breaches exploit.",
     ["Conditional access and enforced MFA", "Mail authentication done right: SPF, DKIM, DMARC",
      "License optimization and secure-score improvement", "Audit logging with alerting on high-risk events",
      "External sharing governance for SharePoint/OneDrive", "Tenant documentation and break-glass procedures"]),
    ("294", "Compliance_vCISO", "Compliance & vCISO Advisory",
     "The security leadership layer: policies, assessments, and audit-ready evidence without a full-time hire.",
     ["Adopted policy suite from this library, tailored to your firm", "Annual risk assessment and NIST-aligned self-assessment",
      "Vertical compliance programs: HIPAA, IRS 4557 WISP, FTC Safeguards", "POA&M management with quarterly review",
      "Vendor security reviews and DPA/BAA management", "Board/principal reporting as regulations require"]),
    ("295", "Network_Infrastructure", "Network & Infrastructure Services",
     "The wiring under everything: firewalls, switching, Wi-Fi, and servers designed, documented, and defended.",
     ["Managed firewall with segmented VLANs and logging", "Enterprise Wi-Fi with isolated guest and IoT",
      "Switching and cabling projects with as-built documentation", "Server and virtualization design and care",
      "UPS/power protection with maintenance cycle", "Full network documentation to our published standard"]),
    ("296", "Projects_Migrations", "Projects & Migrations",
     "Fixed-scope work done on runbooks, not improvisation: migrations, refreshes, and buildouts.",
     ["Email and file migrations with verified counts and hypercare", "Office moves and buildouts with cutover planning",
      "Workstation refresh programs with certified sanitization", "Server upgrades and cloud transitions",
      "Every project mapped to a statement of work with milestones", "Post-project documentation delivered into your record"]),
    ("297", "Cyber_Academy", "BVTech Cyber Academy",
     "Security awareness people actually complete: short monthly lessons, streaks and XP, phishing drills, and compliance reporting.",
     ["Monthly refreshed micro-lessons in the client portal", "Gamified completion: XP, streaks, leaderboards per team",
      "Quarterly phishing simulations with gentle remediation", "Manager dashboards and audit-ready completion reports",
      "New-hire onboarding track with policy acknowledgments", "Maps directly to training requirements in HIPAA/4557/Safeguards"]),
]


def build() -> list[dict]:
    docs: list[dict] = []
    for n, slug, title, summary, items in CHECKLISTS:
        docs.append(_chk(n, slug, title, summary, items))
    for n, slug, title, summary, clauses in STANDARDS:
        docs.append({"id": f"BVT-STD-{n}", "slug": slug, "title": title,
                     "category": CAT_SEC2[0], "category_label": CAT_SEC2[1],
                     "visibility": "internal", "kind": "policy", "summary": summary,
                     "sections": [
                         {"h": "Standard", "kind": "clauses", "body": clauses},
                         {"h": "Compliance", "kind": "para", "body":
                          "Deviations require a written exception (BVT-FRM-267) with compensating "
                          "controls and an expiration date. This standard is reviewed annually."}]})
    for n, slug, title, summary, points in TRAININGS:
        docs.append({"id": f"BVT-TRN-{n}", "slug": f"Awareness_{slug}", "title": f"Security Awareness - {title}",
                     "category": CAT_TRN[0], "category_label": CAT_TRN[1],
                     "visibility": "client", "kind": "onepager", "summary": summary,
                     "sections": [
                         {"h": "What To Know", "kind": "bullets", "body": points},
                         {"h": "One Habit", "kind": "para", "body":
                          "When anything feels off - an email, a call, a prompt, a device - report it "
                          "immediately and without embarrassment. Early reports are how small events "
                          "stay small. Reporting channel: your helpdesk ticket portal or "
                          "help@bvtech.org."}]})
    for n, slug, title, _kind, fields in FORMS:
        docs.append({"id": f"BVT-FRM-{n}", "slug": slug, "title": title,
                     "category": CAT_FRM[0], "category_label": CAT_FRM[1],
                     "visibility": "internal", "kind": "form",
                     "summary": "Standard operational form - complete in full; file with the "
                                "relevant client or personnel record.",
                     "sections": [{"h": "Form", "kind": "fills", "body": fields},
                                  {"h": "Notes", "kind": "fills", "body": ["", "", ""]}]})
    for n, slug, title, steps in RUNBOOKS:
        docs.append({"id": f"BVT-SOP-{n}", "slug": slug, "title": f"Runbook - {title}",
                     "category": CAT_SOP[0], "category_label": CAT_SOP[1],
                     "visibility": "internal", "kind": "checklist",
                     "summary": "Step-by-step operating procedure. Follow in order; record "
                                "exceptions in the ticket.",
                     "sections": [{"h": "Procedure", "kind": "checks", "body": steps},
                                  {"h": "Completion", "kind": "fills",
                                   "body": ["Technician:", "Ticket #:", "Date:", "Exceptions noted:"]}]})
    for n, slug, title, pitch, feats in SERVICES:
        docs.append({"id": f"BVT-SVC-{n}", "slug": f"Service_{slug}", "title": f"Service Description - {title}",
                     "category": CAT_AGR[0], "category_label": CAT_AGR[1],
                     "visibility": "client", "kind": "onepager", "summary": pitch,
                     "sections": [
                         {"h": "What's Included", "kind": "bullets", "body": feats},
                         {"h": "How Engagements Work", "kind": "para", "body":
                          "Services are delivered under the BVTech Master Services Agreement with a "
                          "service-specific statement of work and the published Service Level "
                          "Agreement. Every engagement begins with the new-client security audit so "
                          "pricing reflects your real environment - book a 15-minute intro at "
                          "bvtech.org/book."}]})
    return docs
