#!/usr/bin/env python3
# Texas Roots Almanac — content database
# Each article: slug, title, category, icon(svg in kb/), summary, read_min, body(list of blocks)
# Block types: ('h', text) heading | ('p', text) para | ('ul', [items]) | ('ol',[items])
#              ('quote', text) | ('tip', text) callout | ('table', [headers], [rows]) | ('steps',[(title,desc)])

CATEGORIES = {
    "growing":   {"name":"Growing & Soil",       "color":"#5C8A3A", "desc":"Soil, propagation, pots, and the craft of keeping plants alive."},
    "homestead": {"name":"Homestead & Land",      "color":"#C99A3B", "desc":"Acre plans, buying land, water, and building toward self-sufficiency."},
    "survival":  {"name":"Survival & Food Security","color":"#B5552F","desc":"Victory gardens, calorie crops, and growing through hard times."},
    "animals":   {"name":"Animals & Livestock",   "color":"#8a5a3a", "desc":"Chickens, small stock, and working animals into the system."},
    "systems":   {"name":"Water, Energy & Systems","color":"#68a3c4","desc":"Catching water, closing loops, and running a farm that feeds itself."},
    "machinery": {"name":"Machinery & Repair",    "color":"#5a6b72", "desc":"Fixing your own equipment and the right to do so."},
    "community": {"name":"Community & Zoning",    "color":"#7CB342", "desc":"Shared gardens, local rules, and growing with your neighbors."},
}

ARTICLES = [
# ============================ GROWING ============================
{
"slug":"how-to-test-your-soil",
"title":"How to Test Your Soil (Without a Lab, and With One)",
"category":"growing","icon":"soil.svg","read_min":9,
"summary":"Your soil is the whole game. Here's how I read it by hand, what a real lab test tells you, and how to fix what you find — the way I do it here in El Campo.",
"body":[
("p","Everything I sell starts with soil, so this is the first thing I'd want you to understand. You can buy the best seed in the world and it'll still sulk in dead dirt. The good news is you can learn most of what you need to know about your ground with your hands and a jar before you ever spend a dollar on a test."),
("h","The jar test — texture in an afternoon"),
("p","Soil texture is the ratio of sand, silt, and clay. It decides how your soil drains, how it holds nutrients, and how often you'll be watering. You can measure it with a mason jar."),
("steps",[
("Fill a third","Put about a third of a quart jar full of soil from a few inches down. Pull out rocks and roots."),
("Top with water","Fill nearly to the top with water, add a teaspoon of dish soap to break up clumps."),
("Shake hard","Shake it for two full minutes until everything is suspended."),
("Let it settle","Sand drops in a minute, silt over a couple hours, clay over a day or two. Mark each layer."),
]),
("p","Measure the layers. Mostly sand drains fast and dries out — great for rosemary, hard on lettuce. Heavy clay holds water and nutrients but compacts and drowns roots. The sweet spot most vegetables want is loam: roughly 40% sand, 40% silt, 20% clay. Around here on the Gulf Coast you'll often find heavy clay, which is why I grow so much in raised beds and cloth pots."),
("h","Reading soil by feel and color"),
("p","Grab a handful of damp soil and squeeze. If it ribbons out between your thumb and finger like clay on a wheel, you've got clay. If it falls apart no matter what, it's sandy. If it forms a loose ball that crumbles when poked, that's loam — what you're after."),
("p","Color tells you about organic matter. Dark, near-black soil is rich in it. Pale, grayish, or yellow soil is hungry. The smell matters too: living soil smells sweet and earthy. Sour or chemical smells mean poor drainage and anaerobic conditions."),
("h","The pH test, and why it matters more than fertilizer"),
("p","pH controls whether nutrients are even available to roots. You can pour all the fertilizer you want on soil that's too acidic or alkaline and the plant still can't take it up. Most vegetables want a pH between 6.0 and 7.0. A cheap probe or a packet of test strips from any garden store gets you close."),
("table",["Result","What it means","How I fix it"],[
["Below 6.0 (acidic)","Common in high-rainfall areas","Garden lime, worked in over a season"],
["6.0–7.0","The target for most vegetables","Maintain with compost"],
["Above 7.5 (alkaline)","Common in arid/limestone soils","Elemental sulfur, peat, acidifying compost"],
]),
("h","When to spring for a real lab test"),
("p","A mail-in lab test from your state extension office is cheap — often under $20 — and worth it before you build a big garden or buy land. It tells you exact nutrient levels (nitrogen, phosphorus, potassium), pH, organic matter percentage, and often a recommendation tailored to what you want to grow. In Texas, the Texas A&M AgriLife Extension soil lab does this. Take samples from several spots, mix them, and send a cup."),
("tip","Sample at the same depth you'll be planting roots — about 6 inches for vegetables. One sample from one hole isn't representative; walk a zigzag across the plot and combine a dozen small scoops."),
("h","Fixing what you find"),
("p","Almost every soil problem improves with the same answer: organic matter. Compost buffers pH, feeds soil life, improves drainage in clay and water retention in sand. I build my own house blend — a base layer of quality potting mix, compost, Texas topsoil, and natural additives — and for my more expensive plants I'll start with a FoxFarm base and build up from there. You don't need to buy your way to good soil; you need to feed it consistently for a few seasons."),
("quote","Don't feed the plant. Feed the soil, and let the soil feed the plant."),
]
},
{
"slug":"how-to-clone-plants",
"title":"How to Clone Plants: Turning One Plant Into Ten",
"category":"growing","icon":"cloning.svg","read_min":10,
"summary":"Cloning is just taking cuttings, and it's the cheapest way to multiply a garden. This is exactly how I propagate the cuttings I sell — what works, what kills cuttings, and how to do it for free.",
"body":[
("p","A cutting is a piece of a plant that grows roots and becomes a whole new plant — genetically identical to the parent. It's not complicated, it's not new, and it's how gardeners have shared plants over the fence for centuries. It's also how I produce most of the rooted cuttings I mail out. Once you can clone, you stop buying plants you already own."),
("h","What clones well (and what doesn't)"),
("p","Soft-stemmed herbs and houseplants are the easiest entry point. Woody plants are slower but doable. Things grown from a single taproot — carrots, most trees from seed — don't clone from stem cuttings."),
("table",["Easy","Medium","Hard / not from cuttings"],[
["Mint, basil, pothos","Rosemary, lavender, tomato","Carrots, beets"],
["Spider plant, succulents","Roses, hydrangea","Most large trees"],
["Coleus, ivy","Fig, grape","Anything taprooted"],
]),
("h","The four ways to root a cutting"),
("ol",[
"Water rooting — stick the cutting in a jar of water on a windowsill. Easiest for mint, pothos, basil. Change the water every few days.",
"Soil/medium rooting — stick it in moist perlite or a light mix under a humidity dome. Stronger roots, better for the long haul.",
"Division — for clumping plants, just pull the root ball apart into pieces, each with roots and growth. Instant new plants.",
"Layering — bend a low branch to the ground, bury a section, and let it root before you cut it free. Great for woody plants that resist cuttings.",
]),
("h","My exact cutting method"),
("steps",[
("Pick the right stem","Take 4–6 inches of healthy new growth, not old woody wood and not the soft tip. Cut just below a node — the little bump where leaves attach. That's where roots form."),
("Strip the bottom","Remove leaves from the lower half. Too many leaves and the cutting loses water faster than it can drink; too few and it can't photosynthesize."),
("Dip in hormone","Dip the cut end in rooting hormone powder. It's optional for easy plants, a big help for woody ones."),
("Stick and cover","Push into moist perlite, firm gently, cover with a clear dome or a cut soda bottle to hold humidity. Bright indirect light, never direct sun — you'll cook it."),
("Wait and check","Roots come in one to three weeks depending on the plant. Tug gently; resistance means roots. Then pot up into soil."),
]),
("tip","The number one killer of cuttings isn't lack of water — it's too much. Soggy medium rots the stem before it can root. Moist, not wet. If you can squeeze water out of the medium, it's too wet."),
("h","Why I prefer cuttings over seed for some plants"),
("p","A cutting is a clone, so it's true to the parent — same flavor, same color, same vigor. Seed can vary. If I've got a basil plant with perfect flavor or a tomato that shrugged off our heat, I clone it rather than gamble on its seed. It's also faster: a rooted cutting is weeks ahead of a seedling. That head start is part of why mailed cuttings establish so well."),
("quote","Every plant in your garden is a potential ten. That's the whole secret to a cheap, abundant garden."),
]
},
{
"slug":"best-pots-for-growing",
"title":"Which Pots Are Best? Why I Grow in Organic Cloth",
"category":"growing","icon":"pots.svg","read_min":7,
"summary":"After years of trying everything, I grow most things in non-bleached cloth pots. Here's the honest rundown of every container type and when each one actually makes sense.",
"body":[
("p","People obsess over soil and seed and then plant into whatever container is cheapest. The container shapes the root system, and the root system is the plant. Here's what I've landed on after killing plenty of plants in the wrong pots."),
("h","Why cloth pots win for most of what I grow"),
("p","Fabric grow bags — I use non-bleached, organic cloth — do something rigid pots can't: they air-prune the roots. When a root hits the fabric wall and reaches air, the tip stops and the plant pushes out new feeder roots behind it. Instead of a circling, root-bound mess, you get a dense, fibrous root ball that takes up water and nutrients far better."),
("ul",[
"They breathe, so roots get oxygen and soil doesn't go anaerobic.",
"They drain freely, so it's nearly impossible to overwater.",
"They don't bake roots the way black plastic does in Texas sun.",
"They fold flat and store in nothing when the season's over.",
"Non-bleached fabric keeps chlorine-bleaching chemistry out of your root zone — it matters to me for anything I'm eating.",
]),
("p","The tradeoff: they dry out faster, so in peak summer you water more often. For me that's a fair trade for healthier roots, and a drip line solves it."),
("h","The full container rundown"),
("table",["Container","Best for","Watch out for"],[
["Organic cloth bag","Almost everything; vegetables, herbs","Dries faster; water more in heat"],
["Terracotta","Plants that like dry feet; rosemary, succulents","Heavy, breakable, wicks water"],
["Glazed ceramic","Decorative indoor plants","Heavy, pricey, often poor drainage"],
["Plastic nursery pot","Cheap propagation, short-term","Roots circle and bind; bakes in sun"],
["Self-watering","Thirsty plants, vacations","Can stay too wet for some roots"],
["Raised wood bed","In-ground-style growing without the clay","Needs more soil volume up front"],
]),
("tip","Whatever you use, drainage is non-negotiable. A pot with no drainage hole is a bucket, and a bucket drowns roots. If you love a decorative pot with no hole, plant in a cloth bag or plastic pot and set that inside the pretty one."),
("h","Sizing it right"),
("p","Too small and the plant stalls and dries out hourly; too big and the unused soil stays wet and sours. Rough guide: herbs and lettuce in 1–3 gallon, peppers and bush tomatoes in 5–7 gallon, big indeterminate tomatoes and small fruit trees in 10–20 gallon. When in doubt, size up one step from what feels right."),
]
},
{
"slug":"what-grows-best-in-texas",
"title":"What Grows Best in My Area: A Texas Gulf Coast Planting Guide",
"category":"growing","icon":"zones.svg","read_min":11,
"summary":"Knowing your zone and your real seasons is worth more than any fancy technique. Here's how to figure out what thrives where you are, with a full Texas breakdown.",
"body":[
("p","The single most common reason a garden fails is planting the right thing at the wrong time, or the wrong thing for the climate. Before you buy a single seed, learn two things about where you live: your USDA hardiness zone and your average frost dates. Everything else follows from those."),
("h","Find your zone"),
("p","The USDA hardiness zone is based on your average coldest winter temperature. It tells you what perennials will survive your winter. It does not tell you about summer heat — which in Texas is the bigger limiting factor — so treat it as half the picture."),
("table",["Texas region","Approx. zone","Character"],[
["Panhandle / North","7–8","Real winters, shorter season"],
["Central / Hill Country","8","Hot summers, mild winters"],
["Gulf Coast (El Campo)","9a","Humid, long season, rare freezes"],
["Deep South / Valley","9b–10","Nearly frost-free, brutal summers"],
]),
("h","The two-season Texas reality"),
("p","Up north people garden in one long summer push. On the Gulf Coast we really have two gardens: a spring garden that races to beat the summer heat, and a fall garden that's often better than spring because pests die back and greens love the cooling weather. The brutal middle of summer is for heat-lovers and shade cloth."),
("h","What actually thrives here"),
("p","Spring (set out after last frost, ~mid-March here):"),
("ul",["Tomatoes (choose heat-set varieties), peppers, eggplant","Squash, cucumbers, beans","Basil and warm-season herbs"]),
("p","Summer (the survivors):"),
("ul",["Okra — loves the heat and won't quit","Southern peas (black-eyed, crowder)","Sweet potatoes, Malabar spinach, hot peppers"]),
("p","Fall (sow late summer into fall — my favorite season):"),
("ul",["Greens: kale, collards, mustard, lettuce","Brassicas: broccoli, cabbage, cauliflower","Root crops: carrots, beets, radish, turnip","Cilantro and dill, which bolt instantly in spring heat but thrive in cool"]),
("tip","Your local extension office publishes a vegetable planting calendar for your exact county with sow dates. It's free and it's the best gardening document you'll ever read. Search your county name plus 'extension vegetable planting guide.'"),
("h","Microclimates: your yard isn't one zone"),
("p","A south-facing wall is a heat trap that'll ripen peppers early. A low spot collects cold air and frost. The east side of the house gets gentle morning sun; the west side gets brutal afternoon heat. Watch your own yard for a season and you'll find spots that beat your zone in both directions."),
]
},
# ============================ HOMESTEAD ============================
{
"slug":"one-acre-homestead-plan",
"title":"The 1-Acre Homestead Plan: Feeding a Family on a Single Acre",
"category":"homestead","icon":"homestead.svg","read_min":13,
"summary":"One acre is enough to feed a family most of what they eat if you lay it out right. Here's a full zone-by-zone plan for how I'd divide it.",
"body":[
("p","An acre is 43,560 square feet — about the size of a football field without the end zones. It feels small when you picture a farm and enormous when you have to maintain it by hand. The trick is intensity and layout: putting the things you touch daily close to the house and the things you visit occasionally further out. This idea — zones by frequency of visit — comes from permaculture and it's the single most useful planning concept I know."),
("h","The zone system"),
("steps",[
("Zone 0 — the house","Where you live. Everything radiates out from here."),
("Zone 1 — daily (closest)","Kitchen garden, herbs, salad greens, the things you harvest every day. Right outside the door."),
("Zone 2 — frequent","Main vegetable beds, compost, chicken coop, small fruit. You visit daily but not constantly."),
("Zone 3 — occasional","Orchard, larger crops, main forage. Weekly attention."),
("Zone 4 — rare","Pasture, woodlot, wild harvest. Occasional."),
]),
("h","A sample 1-acre allocation"),
("table",["Area","Size","Purpose"],[
["House + yard","~6,000 ft²","Living space, Zone 1 kitchen garden"],
["Main vegetable garden","~5,000 ft²","Intensive raised beds & cloth pots"],
["Orchard","~6,000 ft²","12–20 dwarf fruit & nut trees"],
["Chicken/poultry","~2,000 ft²","Coop + run for 10–15 birds"],
["Pasture/forage","~15,000 ft²","Small grazing, green manure, expansion"],
["Pond/water","~2,000 ft²","Catchment, irrigation, optional fish"],
["Paths, sheds, compost","~7,500 ft²","Infrastructure and movement"],
]),
("h","What an acre can realistically produce"),
("p","With intensive beds, a family of four can grow the majority of their vegetables on 2,000–4,000 square feet. Add a dozen fruit trees and you've got fruit through much of the year. Fifteen hens give you more eggs than you can eat. The acre's limit isn't space — it's your time and your water. Plan for both before you plant."),
("tip","Don't develop the whole acre in year one. Start with Zone 1 and the main garden. Get those producing and easy before you take on an orchard and animals. Every homestead that fails, fails from doing too much too fast."),
("h","Water is the real constraint"),
("p","Before you fall in love with a layout, map your water. Where does rain run? Where could a catchment tank sit uphill of the garden so gravity does the work? I cover this in depth in the water-capture guide, but plan it into the layout from day one — retrofitting water is miserable."),
]
},
{
"slug":"half-acre-homestead-plan",
"title":"The Half-Acre Homestead: Maximum Food in Minimum Space",
"category":"homestead","icon":"homestead.svg","read_min":10,
"summary":"You don't need acreage. On a half-acre — even a big suburban lot — you can grow serious food. Here's how I'd pack it without it becoming a full-time job.",
"body":[
("p","Half an acre is about 21,780 square feet, and a surprising number of suburban lots are close to this once you subtract the house. It's my favorite scale to recommend to beginners: big enough to feed you meaningfully, small enough that one person can keep up with it. The key is vertical growing, succession planting, and ruthless prioritization of high-value crops."),
("h","Prioritize by value per square foot"),
("p","Every square foot is precious at this scale, so grow what gives you the most return. Skip space-hungry, cheap-to-buy crops like field corn or storage potatoes unless you love them. Favor crops that are expensive to buy, productive in small space, or much better fresh."),
("table",["High value (grow these)","Low value (buy these)"],[
["Tomatoes, peppers, herbs","Field corn, wheat"],
["Salad greens, spinach","Storage onions"],
["Berries, dwarf fruit","Storage potatoes"],
["Garlic, specialty veg","Dry beans (unless you enjoy it)"],
]),
("h","A half-acre layout that works"),
("ul",[
"Intensive vegetable beds: 800–1,500 ft² of raised beds and cloth pots, close to the house.",
"Espalier and dwarf fruit: trees trained flat against fences save enormous space — a dozen along a property line.",
"A small flock: 4–6 hens fit easily and turn kitchen scraps into eggs and compost.",
"Vertical everything: trellis cucumbers, beans, melons, and squash up instead of out.",
"A greenhouse or hoop tunnel: even a small one, like the one I grow in, doubles your season.",
]),
("h","Succession is your superpower"),
("p","At this scale you can't afford a bed sitting empty. The moment one crop comes out, another goes in. Spring lettuce gives way to summer beans gives way to fall greens in the same bed. Start seedlings on the side so a replacement is always ready the day a bed opens up. Done well, succession planting can double or triple what a small space yields in a year."),
("tip","Map your sun before you build beds. Most vegetables want 6+ hours of direct sun. On a small lot, shade from the house, fences, and neighbors' trees is the limiting factor — put your beds where the sun actually lands, not where it's convenient."),
]
},
{
"slug":"best-use-of-land-per-acre",
"title":"Best Use of Land Per Acre: Matching Plan to Property",
"category":"homestead","icon":"land.svg","read_min":9,
"summary":"The best use of an acre depends entirely on what you've got. Here's how I'd think through allocating land from a quarter-acre lot up to ten acres.",
"body":[
("p","There's no single right answer to 'what should I do with my land' — it depends on your acreage, your climate, your water, and how much time you actually have. But there are reliable patterns. Here's how the math and the priorities shift as you scale up."),
("h","By the numbers"),
("table",["Land","Realistic focus","Animals"],[
["¼ acre","Intensive veg, herbs, a few dwarf fruit","Maybe a few hens"],
["½ acre","Full veg self-sufficiency, small orchard","Small flock"],
["1 acre","Veg + orchard + poultry, some forage","Poultry, maybe rabbits/goats"],
["2–5 acres","Add grazing, larger orchard, hay","Goats, sheep, pigs"],
["5–10 acres","Small-scale farm income possible","Cattle, mixed livestock"],
]),
("h","The order I'd develop, every time"),
("ol",[
"Water first — catchment, wells, ponds. Nothing works without it.",
"Soil second — compost systems, cover crops, building fertility.",
"Annual food garden third — fast return, builds skills and confidence.",
"Perennials fourth — orchard and berries take years, so plant them early but don't depend on them yet.",
"Animals fifth — they add work and complexity; earn your way to them.",
"Income/scale last — only once the system feeds you reliably.",
]),
("h","Highest-return uses of land"),
("p","If you're optimizing for food value per acre, intensive vegetables and a productive orchard beat almost everything. If you're optimizing for income, it's usually high-value specialty crops (cut flowers, herbs, nursery plants — which is exactly the lane Texas Roots sits in), not commodity crops you can't compete with at scale. If you're optimizing for resilience, diversity beats efficiency: spread your bets across many crops and a few animals so no single failure sinks you."),
("tip","Match the plan to your honest time budget, not your fantasy. A beautiful five-acre plan you can't maintain produces less than a half-acre you actually tend. Scale to the hours you really have."),
]
},
{
"slug":"how-to-buy-land",
"title":"How to Buy Land: What I'd Check Before Signing Anything",
"category":"homestead","icon":"land.svg","read_min":12,
"summary":"Buying rural land is full of expensive surprises. Here's the checklist I'd walk through before buying any property to grow on — water, access, soil, zoning, and the gotchas.",
"body":[
("p","Buying land to homestead or farm is different from buying a house. The building matters less than what's under it and around it. I've watched people fall in love with a pretty view and discover later that the land has no reliable water, no legal access, or rules that forbid the very thing they bought it for. Here's how to look before you leap. None of this is legal or financial advice — get a real attorney and agent — but it's the practical checklist I'd run."),
("h","Water rights and water access"),
("p","This is the first question, not the last. Does the property have a well, and what's its depth and flow rate? Can you legally drill one? In some western states, surface water rights are separate from land ownership and fiercely contested. Is there a creek, and are you allowed to use it? A cheap parcel with no water is worth less than an expensive one with abundant water."),
("h","Legal access"),
("p","Can you legally get to the property on a public road, or do you cross someone else's land? An easement should be in writing and recorded. 'The neighbor's always let people drive through' is not access — it's a lawsuit waiting to happen."),
("h","The checklist I'd run"),
("ul",[
"Water: well, flow rate, water rights, surface water, flood risk.",
"Access: legal recorded easement or public road frontage.",
"Soil: get a soil survey (USDA Web Soil Survey is free) and test before buying if you can.",
"Zoning & deed restrictions: is agriculture, livestock, a second dwelling, or a roadside stand allowed?",
"Utilities: power distance, septic feasibility (perc test), internet.",
"Topography: slope, drainage, sun aspect, usable vs. unusable acreage.",
"Environmental: flood zone, wetlands, easements, mineral rights (often sold separately!).",
"Taxes: current ag exemption status can save thousands; losing it can cost you.",
]),
("tip","Mineral rights are commonly severed from surface rights, especially in Texas. You can own the land and not the oil, gas, or minerals beneath it — and the mineral owner may have the right to access your surface. Always ask what mineral rights convey."),
("h","Walk it in the rain"),
("p","If you can, visit the land in bad weather. A property that looks idyllic in July can be a swamp in spring. See where water pools, where the road washes out, where the wind hits. Talk to the neighbors — they'll tell you things the listing never will."),
("h","Get the soil survey"),
("p","The USDA Web Soil Survey is a free online tool that maps the soil types of almost any parcel in the country. It'll tell you the soil's drainage class, its suitability for crops, depth to bedrock, and more before you ever set foot on the property. It's the first thing I'd pull up on any listing."),
]
},
# ============================ SURVIVAL ============================
{
"slug":"how-to-grow-a-survival-garden",
"title":"How to Grow a Survival Garden (a Modern Victory Garden)",
"category":"survival","icon":"victory.svg","read_min":14,
"summary":"In WWII, victory gardens grew 40% of America's produce. A survival garden is the same idea: growing real calories and nutrition when you need to. Here's how to plan one that could actually keep you fed.",
"body":[
("p","During both World Wars, ordinary people grew an astonishing share of their own food in 'victory gardens' — backyard plots, vacant lots, rooftops. At their peak they produced roughly 40% of the fresh vegetables in the United States. A survival garden is the same concept applied to any hard time: a deliberate, calorie-aware garden designed to feed people, not just garnish a plate. The difference between a hobby garden and a survival garden is that you plan it around calories and nutrition, not just what's fun to grow."),
("h","Calories first"),
("p","A garden full of lettuce and tomatoes is delicious and nutritious but won't keep you alive — there are almost no calories in it. A survival garden has to grow energy. The highest-calorie crops per square foot are the foundation."),
("table",["Crop","Why it matters","Stores?"],[
["Potatoes","Most calories per square foot, easy","Months in cool dark"],
["Sweet potatoes","Thrive in Texas heat, calorie-dense","Months, cured"],
["Winter squash","Huge yield, dense, long storage","All winter"],
["Dry beans","Protein + calories, store for years","Years dried"],
["Corn (flour/dent)","Calories, grindable, stores dry","Years dried"],
]),
("h","Then protein and fats"),
("p","Calories keep you going; protein keeps you strong. Beans and corn together form a complete protein — the reason that pairing anchors so many traditional diets. Add eggs from a few hens and you've covered a lot of nutritional ground. Sunflowers and pumpkins give you seeds with fat and protein."),
("h","Then the nutrition garden"),
("p","Around the calorie core, grow the vitamins: leafy greens (kale and collards are nearly year-round here and incredibly nutritious), peppers, tomatoes, herbs, and anything colorful. These are what keep a calorie diet from making you sick over the long term."),
("h","The four pillars of a survival garden"),
("ol",[
"Calories — potatoes, sweet potatoes, squash, corn.",
"Protein — beans, corn, eggs, seeds.",
"Vitamins & minerals — greens, peppers, tomatoes, herbs.",
"Seed security — open-pollinated varieties you can save and regrow.",
]),
("tip","Grow open-pollinated (heirloom) varieties, not hybrids, for anything you're depending on. Heirloom seed comes back true, so you can save your own and never need to buy again. Every packet I sell is open-pollinated for exactly this reason."),
("h","Scale and storage"),
("p","To meaningfully feed one adult, you're looking at a few hundred to over a thousand square feet of intensive growing, plus the knowledge to preserve the surplus. A survival garden isn't complete without storage: a cool dark space for roots and squash, the ability to can or dehydrate, and dry storage for beans and grain. Growing the food is half the skill; keeping it through the lean months is the other half."),
("quote","The best time to learn to grow food was years ago. The second best time is this season — while the stakes are still low and mistakes are cheap."),
]
},
{
"slug":"food-preservation-basics",
"title":"Food Preservation Basics: Keeping the Harvest",
"category":"survival","icon":"loop.svg","read_min":9,
"summary":"Growing food is only half of food security. If you can't store it, a glut in July does nothing for you in January. Here are the core preservation methods and when to use each.",
"body":[
("p","Every gardener hits the moment when everything ripens at once and you can't possibly eat it. That glut is the whole point of a survival garden — but only if you can carry it into the lean months. Here are the preservation methods worth knowing, roughly in order of how easy they are to start."),
("h","Cold storage (easiest)"),
("p","Some crops store for months with no processing at all — just the right conditions. Winter squash, potatoes, sweet potatoes, onions, garlic, and apples keep for weeks to months in a cool, dark, ventilated space. A 'root cellar' can be as simple as an insulated closet, a basement corner, or a buried tote in cold climates."),
("h","Drying / dehydrating"),
("p","The oldest preservation method. Removing water stops spoilage. Herbs, peppers, tomatoes, beans, and many fruits dry beautifully. You can use a dedicated dehydrator, an oven on its lowest setting, or in a dry climate, the sun and a screen. Dried food stores for months to years and takes almost no space."),
("h","Canning"),
("p","Canning seals food in jars and heats it to kill spoilage organisms. There are two kinds, and the distinction is a safety matter, not a preference:"),
("ul",[
"Water-bath canning — for high-acid foods only: fruits, jams, pickles, tomatoes with added acid.",
"Pressure canning — required for low-acid foods: vegetables, beans, meats. A water bath cannot reach the temperature needed to make these safe.",
]),
("tip","Never water-bath-can low-acid foods like green beans or meat. The bacterium that causes botulism survives boiling water and thrives in sealed low-acid jars. Use a tested, current recipe from a reliable source and a pressure canner for anything low-acid. This is the one place in food preservation where 'close enough' can genuinely hurt someone."),
("h","Fermenting"),
("p","Fermentation uses beneficial bacteria to preserve food and create things like sauerkraut, kimchi, and pickles, while adding gut-healthy probiotics. It's low-tech, low-energy, and forgiving once you learn the basics — salt, submersion, and patience."),
("h","Freezing"),
("p","The easiest modern method if you have reliable power: blanch vegetables briefly, cool, bag, and freeze. The catch for resilience is that it depends entirely on electricity — a long outage empties a freezer fast. Good for convenience, weaker for true self-sufficiency."),
]
},
# ============================ SYSTEMS ============================
{
"slug":"how-to-capture-rainwater",
"title":"How to Capture Rainwater: Free Water From Your Roof",
"category":"systems","icon":"water.svg","read_min":10,
"summary":"Every inch of rain on 1,000 square feet of roof is about 600 gallons of free water. Here's how to catch it, store it, and use it — the backbone of any self-reliant garden.",
"body":[
("p","Water is the constraint on almost every garden and homestead, and rain is free water falling on a collection surface you already own: your roof. The math is genuinely surprising. One inch of rainfall on 1,000 square feet of roof yields roughly 600 gallons. In a place that gets 40 inches a year, that's tens of thousands of gallons running off your roof and into the storm drain every year."),
("h","The simple math"),
("p","Catchment in gallons ≈ roof footprint (ft²) × rainfall (inches) × 0.623. So a modest 1,200 ft² roof in a 1-inch rain catches about 750 gallons. You don't need a mansion to harvest serious water — you need gutters and somewhere to put it."),
("h","The basic system"),
("steps",[
("Collection","Your roof and gutters. Metal roofs are cleanest; avoid catching from roofs treated with moss-killers if you'll use it on edibles."),
("First flush","A simple diverter that dumps the first few gallons — which carry dust, bird droppings, and debris — before clean water reaches the tank."),
("Storage","Barrels (cheap, small) or tanks/cisterns (hundreds to thousands of gallons). Opaque containers stop algae."),
("Distribution","Gravity-fed if your tank sits uphill of the garden, or a small pump. A spigot and hose is enough to start."),
]),
("h","Sizing your storage"),
("p","Match storage to your dry spells, not your rainfall. If you get regular rain, a few barrels buffer between storms. If you face long dry summers like we do, you want the biggest tank you can afford and site — because the goal is to bank the wet season's abundance to carry the garden through the drought."),
("tip","Check your local laws before building a big system. Rainwater harvesting is encouraged and even incentivized in much of Texas, but a handful of states have historically restricted it due to water-rights law. Almost everywhere allows at least rain barrels."),
("h","Beyond barrels: shaping the land"),
("p","The most advanced rainwater harvesting isn't in tanks at all — it's in the soil. Swales (level ditches on contour), berms, and mulch slow water down and let it soak into the ground where plant roots can reach it. 'Slow it, spread it, sink it' is the mantra. A well-shaped landscape stores far more water in the soil than any tank, and it does it for free."),
("h","Using it wisely"),
("p","Drip irrigation delivers stored water straight to roots with almost no waste to evaporation — it can use a fraction of the water of a sprinkler for the same result. Pair rainwater catchment with drip and mulch and you can grow through a dry summer on a tiny fraction of municipal water."),
]
},
{
"slug":"self-sufficient-farm",
"title":"How to Build a Self-Sustaining Farm: Closing the Loops",
"category":"systems","icon":"loop.svg","read_min":12,
"summary":"A truly self-sustaining farm is one where the outputs of each part feed the inputs of another. Here's how the loops connect — and how to build toward closing them.",
"body":[
("p","The dream of a self-sustaining farm isn't about buying nothing ever again — it's about closing loops. In a healthy natural system there's no waste: everything that's an output of one process is an input to another. The chicken's manure feeds the garden, the garden's scraps feed the chicken, and the sun and rain power all of it. Building a self-sustaining farm is the work of connecting these loops one at a time."),
("h","The core loops"),
("ol",[
"The fertility loop — kitchen and garden waste → compost → soil → food → waste again. Close this first; it's the foundation.",
"The animal loop — animals eat scraps and forage → produce manure and food → manure feeds the garden → garden feeds the animals.",
"The water loop — rain → catchment → garden and animals → some returns to the ground → recharges what you draw.",
"The seed loop — plants → seed you save → next year's plants. No more buying seed for your staples.",
"The energy loop — sun → plants and solar → work and food → you. The hardest to fully close, but solar and smart design get you far.",
]),
("h","Start with compost"),
("p","If you do one thing toward self-sufficiency, build a compost system. It turns your 'waste' into the fertility that grows your food, and it breaks your dependence on bought fertilizer. Everything organic — kitchen scraps, garden trimmings, leaves, animal bedding — goes in, and rich soil comes out. It's the beating heart of a closed-loop farm."),
("h","Add animals thoughtfully"),
("p","Animals are loop-multipliers: chickens turn pests and scraps into eggs and fertilizer, and clear and till ground for you. But they also add daily work and dependency — they need feed, water, and protection every single day. Add them once your plant systems are stable, and choose animals whose loops fit your land."),
("tip","No farm is an island, and chasing total self-sufficiency to the point of misery defeats the purpose. The goal is resilience and reduced dependence, not purity. Buy what's genuinely better to buy; produce what's genuinely better to produce. Trade with neighbors — that's a loop too."),
("h","Design before you build"),
("p","The most self-sufficient farms are designed, not accumulated. Before building, sketch where the water flows, where the sun falls, how you'll move between zones, and how each element's output can feed another's input. Put the compost between the kitchen and the garden. Put the chickens where their manure is easy to move to the beds. Good design means the system does more of the work for you — for years."),
]
},
# ============================ ANIMALS ============================
{
"slug":"raising-backyard-chickens",
"title":"Raising Backyard Chickens: The Beginner's Livestock",
"category":"animals","icon":"animals.svg","read_min":11,
"summary":"Chickens are the gateway livestock — eggs, meat, pest control, and fertilizer from a small space. Here's everything I'd tell a first-timer before they get birds.",
"body":[
("p","If you're adding animals to a homestead, chickens are almost always the place to start. They're small, cheap, productive, and forgiving of beginner mistakes. A handful of hens turns kitchen scraps and bugs into fresh eggs, rich manure for the garden, and pest control — all from a corner of the yard. Here's the honest beginner's rundown."),
("h","How many, and which kind"),
("p","A hen lays roughly 4–6 eggs a week in her productive years. Four to six hens keeps a small family in eggs. Don't get a rooster unless you want chicks or live somewhere it's allowed and tolerated — hens lay perfectly well without one. For beginners, hardy dual-purpose breeds (good for eggs and calm temperament) like Rhode Island Reds, Orpingtons, or Australorps are forgiving choices."),
("h","What they need, every single day"),
("ul",[
"Clean water — always, and it freezes in winter and fouls fast in summer.",
"Feed — a complete layer feed, supplemented with scraps and forage.",
"Shelter — a predator-proof coop to roost and lay in at night.",
"Space — room to move; cramped birds get sick and peck each other.",
"Protection — predators are the number-one killer. Hardware cloth, not chicken wire; lock them up at night.",
]),
("tip","'Chicken wire' keeps chickens in but does not keep predators out — raccoons reach through it and dogs tear it. Use half-inch hardware cloth for any opening a predator could exploit, and bury it a few inches at the base of the run against diggers."),
("h","The coop"),
("p","Plan for about 3–4 square feet per bird inside the coop and 8–10 in the run. Provide a roosting bar (they sleep up off the ground), nesting boxes (one per 3–4 hens), good ventilation without drafts, and easy access for you to clean and collect eggs. You can build one cheaply from salvage or buy a kit — just make sure it's genuinely predator-proof."),
("h","The garden payoff"),
("p","Chicken manure is one of the richest fertilizers there is — too rich to use fresh, as it'll burn plants. Composted first, it's garden gold. Many homesteaders run chickens through the garden in the off-season to clear pests, eat weeds, scratch up the soil, and fertilize as they go. That's a loop closing: the garden feeds the birds, the birds feed the garden."),
("h","The honest downsides"),
("p","Chickens tie you down — someone has to close the coop every night and open it every morning, rain or shine, vacation or not. They attract predators and pests if you're sloppy. And they're loud enough that close neighbors and city rules matter. Know your local ordinances on flock size and roosters before you buy birds."),
]
},
# ============================ MACHINERY ============================
{
"slug":"farm-equipment-repair-basics",
"title":"Farm Equipment Repair Basics: Fix It Yourself",
"category":"machinery","icon":"repair.svg","read_min":10,
"summary":"Equipment always breaks at the worst time. Learning to diagnose and repair your own gear saves money and downtime. Here's the mindset and the basics that cover most fixes.",
"body":[
("p","Anything with moving parts will eventually break, usually at the worst possible moment — the middle of harvest, the hottest day, the one weekend you have to get a job done. Learning to fix your own equipment is one of the highest-return skills on a homestead or farm. Most repairs aren't mysterious; they're systematic. Here's how I approach it."),
("h","The diagnostic mindset"),
("p","Before touching a wrench, think like a doctor: what changed, and what are the symptoms? Most machines fail in predictable ways, and most problems trace back to a short list of usual suspects. Don't start replacing parts at random — that's how you spend money without fixing anything."),
("steps",[
("Observe","What exactly is it doing or not doing? When did it start? Any sounds, smells, smoke, leaks?"),
("Check the basics first","The vast majority of 'won't start' problems are fuel, air, spark, or a dead battery. Check the cheap, easy things before the expensive, hard ones."),
("Isolate","Narrow it down system by system. Is it electrical? Fuel? Mechanical? Hydraulic? Test one thing at a time."),
("Source the part","Find the right part — model and serial number matter. Aftermarket is often fine and far cheaper."),
("Fix and document","Make the repair, then write down what it was and what fixed it. Next time it'll be five minutes, not five hours."),
]),
("h","Small engines: the four things to check"),
("p","Most small engines — mowers, tillers, generators, pumps — that won't run are failing on one of four fronts. Work through them in order:"),
("ol",[
"Fuel — is there fresh fuel reaching the carburetor? Old, stale gas is the single most common cause of a no-start.",
"Air — is the air filter clogged? An engine needs to breathe.",
"Spark — is the spark plug firing? Pull it, check the gap, look for fouling.",
"Compression — if fuel, air, and spark are all good and it still won't run, you may have an internal mechanical issue.",
]),
("tip","Stale fuel is the number-one killer of small engines. Ethanol-blended gas absorbs water and gums up carburetors within months. Run equipment dry before storage, use fuel stabilizer, and buy fuel fresh. Half the 'broken' mowers in America just have varnished carburetors from old gas."),
("h","Build a basic kit"),
("p","You don't need a professional shop. A solid socket and wrench set, screwdrivers, pliers, a multimeter for electrical diagnosis, a spark plug socket, a grease gun, and the service manual for your specific machines will handle the large majority of repairs. The manual is the cheapest, most valuable tool you'll own — most are findable online for any model."),
("h","Know your limits"),
("p","Some jobs — hydraulics under pressure, PTO shafts, anything that can store energy or crush you — are genuinely dangerous and worth paying a pro for, or at least learning properly before attempting. Knowing the line between 'I can fix this' and 'this can kill me' is part of the skill. There's no shame in calling someone for the dangerous ten percent."),
]
},
{
"slug":"right-to-repair-for-farmers",
"title":"The Right to Repair for Farmers: Why It Matters",
"category":"machinery","icon":"repair.svg","read_min":9,
"summary":"Modern farm equipment is increasingly locked down with software that prevents owners from fixing their own machines. Here's what right-to-repair means, why farmers are fighting for it, and where things stand.",
"body":[
("p","There's a fight happening over something that used to be obvious: if you own a machine, you should be able to fix it. For most of history, farmers were some of the best mechanics around out of pure necessity. But modern equipment — especially large tractors and combines — increasingly runs on proprietary software, and manufacturers have used that software to lock owners out of their own repairs. This is what the 'right to repair' movement is about."),
("h","What changed"),
("p","Today's high-end farm equipment is as much computer as machine. Many repairs — even simple ones — require proprietary diagnostic software and authorization codes to complete. A farmer can physically replace a part and the machine still won't run until a manufacturer-authorized technician connects and unlocks it. That can mean waiting days for a dealer tech during a narrow harvest window where every hour counts, and paying dealer rates for what used to be a do-it-yourself job."),
("h","Why farmers are pushing back"),
("ul",[
"Downtime costs money — a machine down during harvest can cost more per day than the repair itself.",
"Dealer dependence — fewer rural dealers means longer waits and less leverage.",
"It's their property — owners argue they have the right to fix what they paid for.",
"It revives old equipment — part of why decades-old tractors without software locks now sell at a premium.",
]),
("h","Where it stands"),
("p","Right-to-repair has become a genuine national issue. Some manufacturers have signed memorandums of understanding pledging to make tools, manuals, and diagnostics available to owners and independent shops. Several states have passed or proposed right-to-repair legislation, some specifically covering agricultural equipment. The details and enforcement are still being worked out, and it remains an active legal and political fight. If you farm with modern equipment, it's worth following — and worth factoring into what you buy."),
("tip","This is one reason older, simpler equipment holds its value so well among homesteaders and small farmers. A 1980s tractor you can fix in your own barn with hand tools is, for many people, more useful than a new one you can't legally repair yourself. There's real wisdom in buying repairable."),
("h","What you can do"),
("p","Favor equipment you can actually service. Buy manuals and learn your machines. Support independent repair shops, which keep the whole ecosystem honest. And if it matters to you, pay attention to right-to-repair legislation in your state — farmer voices have driven much of the progress so far. The principle is simple and old: ownership should include the right to repair."),
]
},
# ============================ COMMUNITY ============================
{
"slug":"how-to-start-a-community-garden",
"title":"How to Start a Community Garden in Your Town",
"category":"community","icon":"community.svg","read_min":12,
"summary":"A community garden turns vacant land and willing neighbors into food, friendship, and resilience. Here's the step-by-step playbook for getting one off the ground.",
"body":[
("p","A community garden is one of the highest-leverage things a neighborhood can build. It turns unused land into food, connects neighbors who'd otherwise never meet, teaches skills, and makes a place more resilient. I'm a big believer in them — it's why I built a whole hub on this site for people starting one. Here's the practical playbook, drawn from how successful gardens actually come together."),
("h","Start with people, not land"),
("p","The most common mistake is finding a plot first and hoping people show up. Do it backwards: gather a core group of committed neighbors first. A garden lives or dies on its people. You want at least a handful of reliable folks who'll show up to build, plant, weed, and organize — not just sign up and disappear. Hold a first meeting, gauge real interest, and find your two or three co-leaders."),
("steps",[
("Build the core group","Find 5–10 genuinely committed people. Hold a kickoff meeting. Identify leaders who'll carry it."),
("Find and secure land","Look for vacant lots, church or school grounds, park edges, unused city land. Get written permission or a lease — a handshake isn't enough."),
("Test the site","Sun (6+ hours), water access, and soil safety. Test for contaminants if it's an old urban lot; use raised beds if in doubt."),
("Plan the layout","Individual plots, shared areas, paths, water, storage, a gathering spot. Decide plot sizes and how many."),
("Set the rules","Membership, fees (to cover water and supplies), responsibilities, what happens to neglected plots, conflict resolution."),
("Build it","Organize work days. Build beds, run water, set up a shed. Many hands make this the fun part."),
("Sustain it","Rotate leadership, keep communicating, celebrate harvests, plan for next season."),
]),
("h","Securing land and permission"),
("p","Land is the make-or-break. Options include city-owned vacant lots (many cities have programs), churches and schools with unused grounds, park land, and private owners willing to lease cheaply for the tax and community benefit. Whatever you find, get it in writing — a lease or written agreement that protects the garden from being bulldozed the moment the land becomes valuable. Gardens that skip this step too often get evicted just as they hit their stride."),
("h","Money and structure"),
("p","Community gardens run on small money: modest membership dues, plus grants and donations. Costs are water, tools, soil, seed, and fencing. Many gardens form a simple nonprofit or operate under an existing one (a church, a neighborhood association) for liability and grant eligibility. Keep the finances transparent — nothing kills a community project faster than murky money."),
("tip","Water access is the most underestimated requirement. Hauling water by hand kills enthusiasm fast. Confirm a real water source — a spigot, a hydrant meter arrangement with the city, or substantial rainwater catchment — before you commit to a site."),
("h","Keeping it alive"),
("p","The hardest part isn't starting a community garden — it's keeping it going past year two, when the founding excitement fades. The gardens that last share leadership so it doesn't all rest on one burned-out person, communicate constantly, handle conflict fairly, and make it social: potlucks, harvest festivals, work days that feel like gatherings. A community garden is a community first and a garden second. Get the community right and the garden grows itself."),
("p","If you're starting one, I built a community hub on this site where you can post your garden, ask questions, and connect with other growers. Come share what you're building."),
]
},
{
"slug":"understanding-zoning-for-growing",
"title":"Understanding Zoning: What You're Allowed to Grow and Raise",
"category":"community","icon":"zones.svg","read_min":9,
"summary":"Before you build that coop or roadside stand, know your local rules. Here's a plain-language guide to zoning, ordinances, and how to find out what's actually allowed where you live.",
"body":[
("p","Few things are more frustrating than building out your homestead dream and then getting a notice from the city telling you to tear it down. Zoning and local ordinances govern what you can do with your land — what you can build, what animals you can keep, whether you can sell from your property. The rules vary wildly from one town to the next, so the only real answer to 'can I do this?' is 'check your local code.' But here's how to navigate it. (This is general information, not legal advice — confirm with your local authority.)"),
("h","Zoning vs. ordinances vs. deed restrictions"),
("ul",[
"Zoning — how land is classified (residential, agricultural, commercial) and what's allowed in each zone. Set by the city or county.",
"Ordinances — specific local rules: how many chickens, whether roosters are allowed, fence heights, setbacks, noise.",
"Deed restrictions / HOA rules — private rules attached to your property that can be stricter than the city's. An HOA can ban chickens even where the city allows them.",
]),
("h","Common things that are regulated"),
("table",["Activity","Often regulated by"],[
["Keeping chickens / livestock","Number, roosters, coop setbacks from property lines"],
["Selling from your property","Whether a roadside stand or home business is allowed"],
["Structures","Permits for sheds, greenhouses, fences over a height"],
["Front-yard gardens","Some towns restrict; most don't"],
["Water catchment","Generally allowed, occasionally regulated"],
["Composting","Rarely restricted, sometimes for odor/pests"],
]),
("h","How to find your rules"),
("steps",[
("Identify your jurisdiction","City limits or unincorporated county? They have different rules. Unincorporated land is usually far less restricted."),
("Find your zoning","Most cities have an online zoning map. Search '[your city] zoning map' or call the planning department."),
("Read the relevant code","Search '[your city] municipal code chickens' or 'ordinances.' Many are posted online."),
("Check for an HOA","If you have one, read its covenants — they can override looser city rules."),
("Just call","The planning or code enforcement office will usually answer plainly. A five-minute call saves a torn-down coop."),
]),
("tip","Selling plants or produce from home — like a roadside stand — can trigger home-business, cottage-food, or agricultural rules. Texas cottage food law, for example, allows certain home-produced food sales, and farm/nursery products have their own rules. If you're going to sell, confirm what your area allows before you set up the stand."),
("h","When the rules don't fit"),
("p","If your town's rules are stuck in a more restrictive era, they can change — many cities have updated chicken and front-yard-garden ordinances in recent years because residents organized and asked. Show up to a council meeting, bring neighbors, point to other towns that allow it. Local rules are more changeable than people think, and food-growing has a lot of public goodwill behind it right now."),
]
},
{
"slug":'reading-the-weather-for-your-garden',
"title":'Reading the Weather for Your Garden (Frost, Heat & the 7-Day Window)',
"category":'growing',"icon":'water.svg',"read_min":8,
"summary":'How I use the 7-day forecast to decide what to plant, when to cover, and when to just wait. The single most useful skill I can hand a new grower — and why I put a live weather tool right on this site.',
"body":[
    ('p', "People ask me what the most important tool in my greenhouse is. It isn't a fancy meter or a heated mat. It's the weather forecast, and knowing how to read it. Almost every gardening mistake I made early on came down to ignoring what the sky was about to do. So this is the habit I'd hand you first — and it's exactly why I built a live 7-day weather tool right into this site."),
    ('h', 'The two numbers that decide everything'),
    ('p', 'Forget the fancy stuff at first. Watch two things: the overnight low and the daytime high over the next seven days. The overnight low tells you about frost and cold stress. The daytime high tells you about heat stress and whether seeds will even germinate. Get in the habit of reading the week ahead, not just today, because the danger is almost always two or three days out.'),
    ('h', 'Frost: the line that kills'),
    ('p', "A light frost starts around 32°F; a hard freeze at 28°F and below will kill most tender plants outright. When I see a low in the 30s coming in the 7-day, that's my cue to act: cover tender plants with frost cloth or an old sheet in the late afternoon (trapping the day's ground heat), water the soil beforehand because moist soil holds warmth, and move anything in pots against the house or into the greenhouse. The forecast gives me a day or two of warning — that's all it takes."),
    ('tip', "On the Gulf Coast our killing frosts are few but sudden. I keep frost cloth folded and ready from November through February so a surprise low never catches me flat-footed. Watching the 7-day means I'm never surprised."),
    ('h', 'Heat: the silent crop-killer'),
    ('p', "Heat is sneakier than frost because it doesn't kill in a night — it just shuts plants down. Once daytime highs sit above the mid-90s, tomatoes drop their blossoms, lettuce bolts to seed, and newly-sown beds bake dry by noon. When I see a hot stretch coming, I hold off on transplanting, sow heat-lovers like okra and sweet potato instead, mulch heavily, and shift watering to early morning so plants go into the heat fully charged."),
    ('h', 'Germination is a temperature game'),
    ('p', "Seeds don't read the calendar; they read soil temperature. Cool-season crops like lettuce, spinach, and peas germinate in cool soil and stall in heat. Warm-season crops like beans, squash, corn, and okra rot in cold wet soil and only wake up once it's warm. Reading the coming week's lows tells you whether the soil is heading the right direction before you waste seed."),
    ('table', ['Coming 7-day pattern', 'What I plant / do'], [['Lows steady above 55°F, highs under 90°F', 'Prime window — transplant tomatoes, peppers, start most things'], ['Lows dropping into the 30s', 'Cover tender crops; hold transplants; great time to sow cool-season greens'], ['Highs climbing past 95°F', 'Switch to heat-lovers (okra, sweet potato, southern peas); mulch; water at dawn'], ['A wet stretch incoming', 'Hold off sowing seed in beds (rot risk); good time to transplant established starts']]),
    ('h', 'Why the tool is right here on the site'),
    ('p', "I added a live weather report to Texas Roots for a simple reason: the forecast is the first thing I check before I make any decision in the greenhouse, and it should be the first thing you check too. It pulls a current reading and the full 7-day outlook for wherever you are, so you can look at the week, look at what you're about to plant, and make the call the way a grower has always made it — by reading the sky first."),
    ('quote', "The best growers I know aren't the ones with the most gear. They're the ones who read the week ahead and work with it instead of against it."),
    ('p', "Start there. Check the seven-day before you plant, before you cover, before you water. Do that for one season and you'll waste less seed, lose fewer plants, and start to feel the rhythm of your own piece of ground. That's the whole game."),
],
},
]

# FAQ data — for FAQPage schema + page
FAQS = [
("Are all your seeds open-pollinated heirlooms?","Yes. Every seed packet from Texas Roots is open-pollinated, meaning you can save seed from your plants and it'll come back true year after year. No hybrids, no patented varieties, no need to ever buy that variety again."),
("Will a mailed cutting really survive shipping?","Yes — that's the whole model. Cuttings are rooted and established before they ship, then damp-wrapped so they travel well. They're packed the same day they ship and arrive in a few days. If one doesn't make it, I replace it once for free."),
("What soil do you grow in?","Most of my plants grow in a house-blend live soil — a base built up with compost, Texas topsoil, and natural additives. For more expensive plants I start from a FoxFarm base and build from there. Some plants I grow hydroponically. The goal is always living, biologically active soil for anything destined for your garden."),
("Do you really grow everything yourself in El Campo?","Yes. Everything starts in my backyard greenhouse tunnel in El Campo, Texas — no warehouse, no drop-shipping, no mystery supplier. When you order, you're ordering from plants I grew and propagated by hand."),
("How does the honor-system stand work?","If you're local to El Campo, the roadside stand is stocked from greenhouse overflow. Take what you'd like and leave what's fair — cash in the box or scan the Cash App tag, $Hydroponically. It's restocked through the growing season."),
("Is the knowledge base really free?","Completely. Every article, guide, and resource in the Almanac is free for anyone, forever. I wrote them to be the resource I wish I'd had starting out. No paywall, no email gate. Share them freely."),
("Can you ship to my state?","Seeds ship anywhere in the US as a flat letter. Live cuttings ship nationwide too, though a few states have agricultural restrictions on certain live plants — if there's ever an issue with your state, I'll let you know before charging you."),
("How can I support what you're doing?","Order seeds or cuttings, tell a friend, share the free guides, or if you're local, visit the stand. That's it. This is a small operation run by one person — every order genuinely helps it keep going."),
]

if __name__ == "__main__":
    print(f"{len(ARTICLES)} articles across {len(CATEGORIES)} categories")
    print(f"{len(FAQS)} FAQs")
    for c in CATEGORIES:
        n = len([a for a in ARTICLES if a['category']==c])
        print(f"  {c}: {n}")
