#!/usr/bin/env python3
"""Texas Roots — v9 plant expansion.

Real, structured horticultural rows in the exact plants_table tuple order:
(slug, common, latin, family, category, tags, sun, water, soil, ph, hardy,
 height, spacing, days, summary, uses, edible_parts, edible_caution,
 id1, id2, id3, companions, in_shop)

A large, honest batch: more Texas natives, fruit & nut trees, medicinal and
culinary herbs, grains/pseudocereals, perennial vegetables, and pollinator
plants. Every fact is real; edible cautions are conservative.
"""

MORE_PLANTS = [
    # ---------------- FRUIT & NUT TREES / SHRUBS ----------------
    ("pomegranate","Pomegranate","Punica granatum","Lythraceae (Loosestrife)","fruit",
     "edible perennial full-sun drought heat-lover shrub",
     "Full sun","Low once established","Well-drained, tolerates poor soil","5.5-7.2","Hardy to ~10°F",
     "6-12 ft","10-15 ft","2-3 years to fruit",
     "A jewel-boxed fruit on a tough, near-indestructible shrub that loves Texas heat and shrugs off drought once its roots go deep.",
     "Fresh arils, juice, molasses","Seeds/arils (juicy coating)","Root, bark, and peel are not for eating in quantity; enjoy the arils.",
     "Leathery glossy leaves, red-orange trumpet flowers","Round red-brown leathery-skinned fruit","Suckering multi-stem shrub habit","Underplant with herbs; good hedge","False"),
    ("jujube","Jujube (Chinese Date)","Ziziphus jujuba","Rhamnaceae (Buckthorn)","fruit",
     "edible perennial full-sun drought heat-lover tree",
     "Full sun","Very low - deeply drought tough","Almost any well-drained soil","6.0-8.0","Hardy to ~-10°F",
     "15-30 ft","15-20 ft","3-4 years to bear",
     "Maybe the most trouble-free fruit tree for Texas: it fruits in heat, ignores drought, and has almost no pests. Crisp apple-like fruit fresh, dates when dried.",
     "Fresh (apple-like), dried (date-like), tea","Fruit","Small stone inside - don't bite through it. Some cultivars have thorns.",
     "Glossy zig-zag branchlets, small waxy leaves","Oval fruit ripening green to reddish-brown","Wrinkles and sweetens like a date as it dries on the tree","Full-sun orchard corner","False"),
    ("loquat","Loquat","Eriobotrya japonica","Rosaceae (Rose)","fruit",
     "edible perennial full-sun evergreen tree",
     "Full to part sun","Moderate","Well-drained, adaptable","6.0-7.5","Hardy to ~10°F (blooms tender)",
     "15-25 ft","15-20 ft","Blooms fall, fruit late spring",
     "An evergreen with big tropical-looking leaves that fruits when little else does - sweet-tart golden fruit in April/May, and gorgeous fragrant winter flowers.",
     "Fresh, jam, poached","Fruit flesh","Seeds contain trace cyanogenic compounds - do not eat the seeds; eat only the flesh.",
     "Large fuzzy corrugated evergreen leaves","Clusters of golden oval fruit","Fragrant white flower panicles in late fall","Shade-tolerant understory edge","False"),
    ("che-fruit","Che (Chinese Mulberry)","Maclura tricuspidata","Moraceae (Mulberry)","fruit",
     "edible perennial full-sun drought tree",
     "Full sun","Low once established","Well-drained, tolerates poor","6.0-7.5","Hardy to ~-20°F",
     "15-25 ft","15-20 ft","Fruit in late summer",
     "A little-known cousin of the mulberry with sweet, watermelon-red fruit and remarkable toughness - drought-hardy and pest-free once established.",
     "Fresh, dried","Ripe fruit","Unripe fruit is bland - wait for deep red and soft. Plants may be thorny when young.",
     "Lobed young leaves maturing to oval","Round maroon-red aggregate fruit","Deep, drought-defeating root system","Orchard edge; wildlife hedge","False"),
    ("mayhaw","Mayhaw","Crataegus opaca","Rosaceae (Rose)","fruit",
     "native edible perennial full-sun wet-tolerant tree",
     "Full to part sun","Moderate to high - tolerates wet feet","Moist, acidic bottomland","4.5-6.5","Native, hardy",
     "20-30 ft","15-20 ft","Fruit in May",
     "A Gulf Coast native hawthorn that turns swampy low ground into famous ruby jelly - one of the few fruit trees that thrives where it stays wet.",
     "Jelly, syrup, wine","Fruit","Thorny branches - site away from paths. Best cooked into jelly.",
     "Small lobed hawthorn leaves, white spring flowers","Clusters of small red apple-like fruit","Thorny, thicket-forming near water","Wet or low spots; bees love the bloom","False"),
    ("american-plum","American Plum","Prunus americana","Rosaceae (Rose)","fruit",
     "native edible perennial full-sun wildlife thicket tree",
     "Full sun","Low to moderate","Adaptable, well-drained","6.0-7.5","Native, very hardy",
     "10-20 ft","10-15 ft","Fruit in mid-summer",
     "A native thicket-forming plum that clouds white in spring, feeds pollinators, and drops tart red plums perfect for jelly - tough, spreading, and wildlife-friendly.",
     "Jelly, preserves, fresh (tart)","Fruit flesh","Do not eat the pits/seeds (cyanogenic). Suckers freely - give it room.",
     "Toothed oval leaves, fragrant white spring flowers","Small red-to-yellow plums with a bloom","Suckering thorny thicket habit","Wildlife hedgerow; pollinator strip","False"),
    ("texas-persimmon","Texas Persimmon","Diospyros texana","Ebenaceae (Ebony)","fruit",
     "native edible perennial full-sun drought wildlife tree",
     "Full sun to part shade","Very low - drought native","Rocky, well-drained, limestone OK","6.5-8.0","Native, hardy",
     "10-15 ft","10 ft","Fruit late summer",
     "A gorgeous small native tree with smooth gray peeling bark and small, intensely sweet black fruit that wildlife (and people) prize - built for dry Texas ground.",
     "Fresh (when fully ripe/soft), preserves","Fully ripe fruit","Eat only fully soft-ripe fruit; unripe is astringent. Fruit stains everything black.",
     "Smooth pale-gray peeling bark","Small round black fruit when ripe","Tidy multi-trunk small tree","Rock gardens; dry wildlife corners","False"),
    ("chinquapin","Allegheny Chinquapin","Castanea pumila","Fagaceae (Beech)","native",
     "native edible perennial full-sun drought tree wildlife",
     "Full sun","Low once established","Well-drained, acidic","4.5-6.5","Native, hardy",
     "6-20 ft","15 ft","Nuts in fall (3-5 yrs)",
     "A native, blight-resistant cousin of the chestnut that bears sweet single nuts on a manageable small tree - a resilient nut crop for acidic Texas soils.",
     "Roasted or raw nuts","Nut kernel","Nuts sit in a spiny burr - wear gloves to husk. Avoid confusing with inedible buckeyes.",
     "Toothed oblong leaves, silvery underneath","Spiny burrs holding single glossy nuts","Suckering small tree/large shrub","Woodland edge; wildlife planting","False"),
    ("black-walnut","Black Walnut","Juglans nigra","Juglandaceae (Walnut)","native",
     "native edible perennial full-sun tree",
     "Full sun","Moderate","Deep, rich, well-drained","6.0-7.5","Native, very hardy",
     "50-75 ft","40-60 ft","Nuts in fall (mature tree)",
     "A towering native hardwood giving rich, bold-flavored nuts and prized timber - a legacy tree, though its roots discourage many plants nearby.",
     "Nut meats, baking","Nut kernel","Roots release juglone that harms tomatoes, apples, and many plants - site with care. Hulls stain deeply.",
     "Large pinnately compound leaves","Round green husks over hard-shelled nuts","Deeply furrowed dark bark, tall canopy","Keep away from juglone-sensitive crops","False"),
    ("goumi","Goumi","Elaeagnus multiflora","Elaeagnaceae (Oleaster)","fruit",
     "edible perennial full-sun drought nitrogen-fixer shrub",
     "Full sun to part shade","Low - drought tough","Poor to average, tolerant","6.0-8.0","Hardy to ~-20°F",
     "5-8 ft","6-8 ft","Fruit early summer (2-3 yrs)",
     "A nitrogen-fixing shrub that feeds the soil AND you: tart-sweet speckled red berries in early summer, with silver-flecked leaves and fragrant spring flowers.",
     "Fresh, jam, fruit leather","Ripe fruit","Best fully ripe (deep red, soft) - underripe is astringent. Single soft seed.",
     "Silver-speckled red berries","Leaves silvery-scaled underneath","Fixes nitrogen via root nodules","Plant near fruit trees as a fertility shrub","False"),

    # ---------------- MEDICINAL & CULINARY HERBS ----------------
    ("echinacea","Purple Coneflower (Echinacea)","Echinacea purpurea","Asteraceae (Aster)","herb",
     "native medicinal perennial full-sun drought pollinator",
     "Full sun to part sun","Low once established","Well-drained, average","6.0-8.0","Native, hardy",
     "2-4 ft","18 in","Blooms year 1-2",
     "The classic prairie coneflower - a pollinator magnet whose roots and flowers have a long herbal tradition, and a tough, self-sowing native that thrives on neglect.",
     "Herbal tea/tincture (traditional immune support)","Flowers, leaves, roots (traditional)","Traditional herbal use; not a substitute for medical care. Avoid if allergic to the daisy family.",
     "Bristly cone-shaped orange center","Drooping purple-pink ray petals","Coarse lance-shaped leaves","Pollinator beds; native meadow","True"),
    ("yarrow","Yarrow","Achillea millefolium","Asteraceae (Aster)","herb",
     "native medicinal perennial full-sun drought pollinator",
     "Full sun","Very low - drought tough","Lean, well-drained (poor is fine)","5.5-8.0","Native, very hardy",
     "1-3 ft","12-18 in","Blooms late spring on",
     "A feathery-leaved workhorse: ancient wound herb, tough pollinator plant, and a groundcover that laughs at drought and poor soil. Named for Achilles.",
     "Herbal tea, poultice (traditional first-aid)","Leaves, flowers (traditional)","Traditional external use for minor wounds; not medical advice. Can cause skin sensitivity in some.",
     "Fern-like finely divided leaves","Flat-topped white flower clusters","Spreads by rhizome into mats","Beneficial-insect strips; lawn alternative","True"),
    ("calendula","Calendula (Pot Marigold)","Calendula officinalis","Asteraceae (Aster)","herb",
     "edible medicinal annual full-sun beginner pollinator container",
     "Full sun","Moderate","Average, well-drained","6.0-7.0","Cool-season annual",
     "12-24 in","10-12 in","45-60 to bloom",
     "Cheerful edible-flowered herb that blooms through cool weather - petals brighten salads and its infused oil is a classic skin-soothing remedy.",
     "Edible petals, infused oil/salve (traditional)","Flower petals","Petals are edible; the healing-salve use is traditional, not medical advice. Avoid if allergic to daisies.",
     "Bright orange-to-yellow daisy flowers","Sticky aromatic light-green leaves","Blooms hard in cool seasons","Edge of the veg bed; pollinator lure","True"),
    ("chamomile","German Chamomile","Matricaria chamomilla","Asteraceae (Aster)","herb",
     "edible medicinal annual full-sun pollinator",
     "Full sun to part sun","Moderate","Light, well-drained","5.6-7.5","Cool-season annual (self-sows)",
     "8-24 in","6-8 in","60-70 to flower",
     "The apple-scented tea flower - tiny daisies you dry for a calming brew, and a self-sowing pollinator favorite that returns on its own each year.",
     "Dried-flower tea","Flowers","Traditional calming tea; avoid if allergic to ragweed/daisy family. Not medical advice.",
     "Feathery thread-like foliage","Small white daisies with domed yellow centers","Sweet apple scent when brushed","Scatter among vegetables; bees love it","True"),
    ("lemon-balm","Lemon Balm","Melissa officinalis","Lamiaceae (Mint)","herb",
     "edible medicinal perennial part-shade beginner container pollinator",
     "Part sun to part shade","Moderate","Average, moist","6.0-7.5","Hardy perennial",
     "1-2 ft","18 in","Harvest year 1",
     "A lemon-scented mint-family herb for calming teas and cooking - vigorous, shade-tolerant, and beloved by bees (Melissa means honeybee).",
     "Tea, cooking, garnishes","Leaves","Spreads readily - contain it. Traditional calming tea, not medical advice.",
     "Crinkled lemon-scented heart-shaped leaves","Square mint-family stems","Small white flowers bees adore","Contain like mint; pollinator corner","True"),
    ("feverfew","Feverfew","Tanacetum parthenium","Asteraceae (Aster)","herb",
     "medicinal perennial full-sun drought pollinator",
     "Full sun to part sun","Low","Well-drained, average","6.0-7.5","Hardy perennial (self-sows)",
     "1-2 ft","12 in","Blooms year 1",
     "A cheerful self-sowing daisy with a long folk reputation for headaches - easy, drought-tough, and a steady source of little white blooms.",
     "Traditional herbal use","Leaves (traditional)","Traditional use only - not medical advice; can irritate mouth and is avoided in pregnancy. Bitter.",
     "Small white daisies, yellow centers","Feathery yellow-green pungent leaves","Bushy, freely self-seeding","Pollinator border; cottage garden","False"),
    ("holy-basil","Holy Basil (Tulsi)","Ocimum tenuiflorum","Lamiaceae (Mint)","herb",
     "edible medicinal annual full-sun heat-lover pollinator container",
     "Full sun","Moderate","Rich, well-drained","6.0-7.5","Warm-season (tender)",
     "12-24 in","12 in","60-90",
     "A revered, clove-scented basil for teas and cooking that adores Texas heat - a nonstop pollinator magnet humming with bees all summer.",
     "Tea, cooking","Leaves, flowers","Culinary and traditional tea use; not medical advice. Frost-tender.",
     "Aromatic clove-and-pepper scented leaves","Purple-tinged flower spikes","Bees swarm the blooms","Warm-season herb bed; near tomatoes","True"),

    # ---------------- GRAINS / PSEUDOCEREALS / STAPLES ----------------
    ("sorghum-grain","Grain Sorghum (Milo)","Sorghum bicolor","Poaceae (Grass)","survival",
     "edible annual full-sun drought heat-lover staple",
     "Full sun","Very low - drought staple","Adaptable, well-drained","5.5-8.5","Warm-season annual",
     "3-5 ft","6-8 in","100-120",
     "The drought grain: a heat-proof cereal that yields when corn fails, giving gluten-free grain to cook like rice or grind to flour. A Texas dryland staple.",
     "Cooked grain, flour, syrup (sweet types)","Grain","Ensure grain is fully mature/dried. Do not graze frost-damaged sorghum forage (prussic acid) - grain use is fine.",
     "Corn-like grassy plant","Dense seed head atop the stalk","Waxy leaves conserve water","Dryland staple bed; rotate with legumes","False"),
    ("pearl-millet","Pearl Millet","Cenchrus americanus","Poaceae (Grass)","survival",
     "edible annual full-sun drought heat-lover staple",
     "Full sun","Very low","Poor, sandy, well-drained","5.5-7.5","Warm-season annual",
     "3-8 ft","4-6 in","70-90",
     "A fast, heat-and-drought-proof grain that produces on poor sandy soil where little else will - nutritious flour, porridge, and forage in one tough plant.",
     "Flour, porridge, forage","Grain","Fully dry the grain before storage. Generally trouble-free.",
     "Tall cattail-like seed spike","Coarse upright grass","Thrives on marginal sandy ground","Sandy dryland patch; poultry forage","False"),
    ("buckwheat","Buckwheat","Fagopyrum esculentum","Polygonaceae (Knotweed)","survival",
     "edible annual full-sun beginner cover-crop pollinator fast",
     "Full sun","Moderate","Poor to average, well-drained","5.0-7.0","Warm-season annual",
     "2-4 ft","broadcast","30 to bloom, 70-90 seed",
     "The fastest soil-builder in the garden - a 30-day cover crop that smothers weeds, feeds bees, then gives gluten-free groats and flour. Not a true grass.",
     "Flour, groats, honey plant","Seed (groats)","Gluten-free. Some people are allergic to buckwheat. Reseeds if left.",
     "Heart-shaped leaves, hollow reddish stems","Clusters of small white flowers","Blooms fast, dies with frost","Cover crop between plantings; bee lure","True"),
    ("quinoa","Quinoa","Chenopodium quinoa","Amaranthaceae (Amaranth)","survival",
     "edible annual full-sun cool-season staple",
     "Full sun","Low to moderate","Well-drained, average","6.0-8.5","Cool-season annual",
     "3-6 ft","12-18 in","90-120",
     "A protein-rich pseudocereal with striking magenta-to-gold seed heads - best in the cool shoulder seasons; the young leaves are edible too.",
     "Cooked grain, young greens","Seed, young leaves","RINSE seed well before cooking to remove bitter saponins. Best in cool weather.",
     "Goosefoot-shaped dusty green leaves","Large plume-like colorful seed heads","Colors up brilliantly as seed matures","Cool-season staple bed; near beans","False"),
    ("chia","Chia","Salvia hispanica","Lamiaceae (Mint)","survival",
     "edible annual full-sun drought heat-lover pollinator",
     "Full sun","Low","Well-drained, sandy-loam","6.0-8.5","Warm-season (frost-tender)",
     "3-6 ft","12-18 in","120-150 to seed",
     "The omega-rich seed on a tall blue-flowered sage that thrives in heat and drought - a pollinator favorite that needs a long warm season to set seed.",
     "Seed (soaked or ground)","Seed","Needs a long frost-free season to mature seed. Culinary use is well established.",
     "Aromatic mint-family foliage","Whorled blue flower spikes","Bees work the blooms heavily","Warm dryland herb/grain bed","False"),

    # ---------------- PERENNIAL & UNUSUAL VEGETABLES ----------------
    ("chayote","Chayote","Sicyos edulis","Cucurbitaceae (Gourd)","vegetable",
     "edible perennial full-sun heat-lover vine",
     "Full sun","Moderate to high","Rich, well-drained","6.0-7.5","Tender perennial (mulch roots)",
     "Vining 15-30 ft","Give a big trellis","120-150",
     "A wildly productive heat-loving squash relative - plant one whole sprouting fruit and get a vine that buries a fence in mild-flavored squash, plus edible shoots and tubers.",
     "Fruit (raw or cooked), shoots, tubers","Fruit, young shoots, tuberous roots","Sap can dry/irritate hands - peel under water or wear gloves. Needs a long season.",
     "Big grape-like leaves on a rampant vine","Pear-shaped pale-green wrinkled fruit","Single large seed inside each fruit","Give a strong fence/arbor; mulch roots to overwinter","False"),
    ("malabar-spinach","Malabar Spinach","Basella alba","Basellaceae (Basella)","vegetable",
     "edible annual full-sun heat-lover vine container",
     "Full sun to part sun","Moderate to high","Rich, moist, well-drained","6.0-7.0","Warm-season (tender)",
     "Vining 6-10 ft","12 in","55-70",
     "The summer 'spinach' that loves the heat true spinach hates - a glossy climbing green (often red-stemmed) that produces lush thick leaves through the worst of a Texas July.",
     "Cooked or raw leaves","Leaves, tender stems","Mucilaginous (thickens when cooked) - good in soups. Berries stain; not commonly eaten.",
     "Thick glossy heart-shaped leaves","Red or green succulent climbing stems","Small clustered flowers, purple berries","Trellis in summer heat; near beans","True"),
    ("moringa","Moringa (Drumstick Tree)","Moringa oleifera","Moringaceae (Moringa)","vegetable",
     "edible perennial full-sun drought heat-lover fast",
     "Full sun","Low once established","Sandy, well-drained","6.3-7.5","Tender (dies back in frost, regrows)",
     "10-30 ft (cut back yearly)","4-8 ft","Leaves in ~months",
     "One of the most nutritious plants known - a fast tropical tree grown as a cut-back shrub in Texas for its protein-rich leaves and edible young pods. Frost kills the top; roots often resprout.",
     "Cooked leaves, young pods","Leaves, young pods, flowers","Eat leaves/young pods; the ROOT and bark contain compounds to avoid, especially in pregnancy. Frost-tender top.",
     "Fine feathery compound leaves","Long slender drumstick seed pods","Grows astonishingly fast in heat","Cut-back shrub in a warm corner; mulch roots","False"),
    ("cassava","Cassava (Yuca)","Manihot esculenta","Euphorbiaceae (Spurge)","vegetable",
     "edible perennial full-sun heat-lover drought staple",
     "Full sun","Low to moderate","Loose, well-drained, sandy","5.5-7.0","Tender (frost-sensitive)",
     "6-10 ft","3 ft","8-12 months to tubers",
     "A tropical staple root that stores calories underground through drought and heat - grown from stem cuttings, it feeds much of the world. Needs correct preparation.",
     "Cooked root (never raw)","Tuberous root (properly prepared)","IMPORTANT: cassava must be peeled and thoroughly COOKED - raw root contains cyanogenic compounds. Never eat raw. Frost-tender.",
     "Deeply palmate lobed leaves","Woody cane-like stems","Swollen starchy tuberous roots","Warm-season staple corner; grow from cuttings","False"),
    ("sunchoke","Sunchoke (Jerusalem Artichoke)","Helianthus tuberosus","Asteraceae (Aster)","vegetable",
     "native edible perennial full-sun drought beginner",
     "Full sun","Low once established","Almost any, well-drained","5.8-7.5","Native, very hardy",
     "6-10 ft","18-24 in","Tubers in fall",
     "A native perennial sunflower that stores knobby, nutty tubers underground and returns forever - nearly impossible to kill, and a cheerful late pollinator bloom on top.",
     "Tubers (roasted, raw, soups)","Tubers","Inulin can cause gas until your gut adjusts - start small. Spreads aggressively; contain it.",
     "Tall rough sunflower stalks","Small yellow sunflowers in late summer","Knobby tan tubers underground","Give it a contained bed - it will spread","True"),
    ("groundnut","American Groundnut","Apios americana","Fabaceae (Legume)","vegetable",
     "native edible perennial part-shade nitrogen-fixer vine",
     "Part sun to part shade","Moderate to high","Moist, rich","5.0-7.0","Native, hardy",
     "Vining 3-10 ft","12-18 in","Tubers in 2nd year",
     "A native nitrogen-fixing vine that strings together protein-rich tubers like beads underground - a forgotten staple of Indigenous and early-American diets.",
     "Cooked tubers, seeds","Tubers, seeds (cooked)","Cook tubers before eating. A small number of people react to them - try a little first.",
     "Compound leaves on a twining vine","Fragrant maroon-brown pea flowers","Chains of small tubers on the roots","Let it climb a native shrub; enriches soil","False"),
    ("okinawa-spinach","Okinawa Spinach","Gynura crepioides","Asteraceae (Aster)","vegetable",
     "edible perennial part-shade heat-lover container",
     "Part sun to part shade","Moderate","Rich, well-drained","6.0-7.0","Tender perennial",
     "1-2 ft","12-18 in","Cut leaves ongoing",
     "A handsome purple-backed perennial green that thrives in heat and shade and roots from any cutting - a cut-and-come-again leaf for stir-fries and salads.",
     "Cooked or raw young leaves","Leaves","Eat young leaves in moderation, mostly cooked. Roots from cuttings instantly. Frost-tender.",
     "Green leaves with deep purple undersides","Succulent sprawling stems","Roots readily from any cutting","Shady edible groundcover; containers","False"),

    # ---------------- POLLINATOR / NATIVE / UTILITY ----------------
    ("mexican-sunflower","Mexican Sunflower (Tithonia)","Tithonia rotundifolia","Asteraceae (Aster)","native",
     "edible-adjacent annual full-sun heat-lover pollinator fast",
     "Full sun","Low to moderate","Average, well-drained (lean is fine)","6.0-7.5","Warm-season annual",
     "4-6 ft","18-24 in","70-90 to bloom",
     "A butterfly and hummingbird superstar - blazing orange daisies on a big, fast, heat-loving plant that also makes excellent chop-and-drop mulch.",
     "Pollinator forage; chop-and-drop mulch","Not for eating","Grown for pollinators and biomass, not food. Can self-sow.",
     "Big velvety triangular leaves","Vivid orange daisy flowers","Hollow stems, very fast growth","Back of the pollinator bed; mulch source","True"),
    ("partridge-pea","Partridge Pea","Chamaecrista fasciculata","Fabaceae (Legume)","native",
     "native annual full-sun drought nitrogen-fixer pollinator",
     "Full sun","Low - drought native","Sandy, poor, well-drained","5.5-7.5","Native, warm-season annual",
     "1-3 ft","broadcast","60-80 to bloom",
     "A cheerful native legume that fixes nitrogen, feeds bees and quail, and self-sows to cover poor ground in yellow blooms - a soil-builder that asks for nothing.",
     "Nitrogen fixer; wildlife/pollinator plant","Not a food crop","Wildlife/soil use, not for eating (seeds can be a mild laxative). Reseeds freely.",
     "Sensitive fern-like leaves that fold when touched","Bright yellow flowers with red centers","Fixes nitrogen; self-sows on poor soil","Cover crop / pollinator strip on poor ground","True"),
    ("crimson-clover","Crimson Clover","Trifolium incarnatum","Fabaceae (Legume)","cover",
     "annual full-sun cool-season nitrogen-fixer pollinator cover-crop",
     "Full sun","Moderate","Well-drained, average","6.0-7.0","Cool-season annual",
     "12-18 in","broadcast","Bloom in spring",
     "A gorgeous cool-season cover crop that blankets the winter garden green, fixes nitrogen, then throws deep-crimson blooms bees love before you turn it under.",
     "Green manure; bee forage","Not a table crop","Grown to enrich soil and feed pollinators; turn under before it sets hard seed.",
     "Soft fuzzy three-part clover leaves","Deep crimson elongated flower heads","Fixes nitrogen over winter","Sow after summer crops; precede heavy feeders","True"),
    ("comfrey","Comfrey (Bocking 14)","Symphytum x uplandicum","Boraginaceae (Borage)","herb",
     "medicinal perennial part-shade pollinator utility",
     "Full sun to part shade","Moderate","Rich, deep, moist","6.0-7.5","Hardy perennial",
     "2-4 ft","2-3 ft","Cut leaves several times/yr",
     "The permaculture powerhouse: deep roots mine minerals into big leaves you chop for mulch and compost 'tea', while bees mob the bell flowers. The sterile Bocking 14 won't seed everywhere.",
     "Chop-and-drop mulch, compost activator, traditional poultice","Traditional external use only","Do NOT eat comfrey - it contains liver-harmful alkaloids. Use for mulch/compost and traditional external poultices only.",
     "Large coarse hairy leaves","Nodding pink-purple bell flowers","Deep taproot mines subsoil minerals","Under fruit trees as a fertility plant","False"),
    ("borage","Borage","Borago officinalis","Boraginaceae (Borage)","herb",
     "edible annual full-sun beginner pollinator fast self-sows",
     "Full sun to part sun","Moderate","Average, well-drained","6.0-7.5","Warm-season annual (self-sows)",
     "1-3 ft","18 in","50-60 to bloom",
     "The bee plant - brilliant blue star flowers that pollinators can't resist, with cucumber-flavored edible blooms and a knack for self-sowing near your tomatoes and squash.",
     "Edible flowers, young leaves (garnish)","Flowers, young leaves","Eat flowers and only young leaves, in moderation (contains trace alkaloids). Hairy mature leaves aren't pleasant.",
     "Bristly gray-green leaves","Five-pointed sky-blue star flowers","Self-sows generously","Classic companion to tomatoes, squash, strawberries","True"),
    ("anise-hyssop-blue","Blue Anise Sage","Salvia guaranitica","Lamiaceae (Mint)","native",
     "perennial full-sun part-shade pollinator hummingbird drought",
     "Full sun to part shade","Low to moderate","Well-drained, average","6.0-7.5","Root-hardy perennial",
     "3-5 ft","2-3 ft","Blooms summer to frost",
     "A hummingbird magnet with deep cobalt-blue tubular flowers all summer - vigorous, heat-tough, and root-hardy so it returns each spring bigger than before.",
     "Pollinator/hummingbird forage","Ornamental (not a food crop)","Grown for pollinators, not eating. Spreads by roots - give it room.",
     "Anise-scented triangular leaves","Deep blue tubular flowers on spikes","Root-hardy; returns each spring","Hummingbird/pollinator border","False"),
    ("prickly-pear","Prickly Pear (Nopal)","Opuntia ficus-indica","Cactaceae (Cactus)","vegetable",
     "native edible perennial full-sun drought heat-lover xeric",
     "Full sun","Very low - true xeric","Sandy, gritty, sharp-drained","6.0-8.5","Hardy (species vary)",
     "3-8 ft","4-6 ft","Pads year 1; fruit summer",
     "The ultimate Texas survival food - flat pads (nopales) and sweet red fruit (tunas) from a cactus that needs almost no water and grows from a single pad laid on the ground.",
     "Young pads (nopales), fruit (tunas)","Young pads, ripe fruit","Remove ALL spines and tiny glochids carefully (singe or scrape) before eating. Handle with tongs and gloves.",
     "Flat paddle-shaped green pads","Showy yellow-orange flowers","Red-purple pear-shaped fruit","Xeric bed; edible living fence","True"),
    ("agarita-native","Agarita","Mahonia trifoliolata","Berberidaceae (Barberry)","fruit",
     "native edible perennial full-sun drought evergreen wildlife",
     "Full sun to part shade","Very low - drought native","Rocky, well-drained, limestone OK","6.5-8.0","Native, hardy",
     "3-6 ft","4-6 ft","Berries in late spring",
     "A spiny blue-gray native evergreen that shrugs off drought and deer, blooms fragrant yellow in late winter, and drops tart red berries famous for jelly.",
     "Jelly, wine, fresh (tart)","Ripe berries","Sharp, holly-like spined leaves - harvest by beating berries onto a sheet. Berries are the edible part.",
     "Stiff blue-gray holly-like spiny leaflets","Fragrant yellow late-winter flowers","Small translucent red berries","Xeric wildlife hedge; deer-resistant","False"),
    ("turks-cap","Turk's Cap","Malvaviscus arboreus","Malvaceae (Mallow)","native",
     "native edible perennial part-shade shade drought hummingbird",
     "Part shade to shade","Low to moderate","Adaptable, well-drained","6.0-7.5","Native, root-hardy",
     "2-4 ft","2-3 ft","Blooms summer to fall",
     "The go-to native for shade AND hummingbirds - whorled red 'fez' flowers all summer, edible mild fruit and flowers, and cheerful toughness where little else blooms.",
     "Edible flowers and fruit (mild), tea","Flowers, ripe fruit","Mild, edible in moderation. A reliable shade bloomer that's hard to misidentify.",
     "Bright red turban-shaped never-fully-open flowers","Soft maple-like leaves","Small apple-flavored red fruit","Shady spots; hummingbird garden","True"),
    ("frostweed","Frostweed","Verbesina virginica","Asteraceae (Aster)","native",
     "native perennial part-shade pollinator wildlife tall",
     "Part sun to shade","Moderate","Rich, moist, adaptable","6.0-7.5","Native, hardy",
     "3-6 ft","2-3 ft","Blooms fall",
     "A native fall nectar station - broad white flower clusters feed monarchs and late pollinators, and on the first freeze its stems split to make curls of 'ice flowers'.",
     "Late-season pollinator forage","Not a food crop","Grown for pollinators/wildlife, not eating. The winged stems are distinctive.",
     "Winged stems, large rough leaves","Flat white clusters of small flowers","Splits into ribbon 'ice' on first freeze","Shady fall pollinator patch","False"),
]
