#!/usr/bin/env python3
"""Texas Roots — v5 new almanac articles.

Long-form, genuinely useful how-to guides in Jordan's voice, focused on
propagation, seed saving, cuttings, and cultivation craft — the requests for
this release. Same block grammar as content.ARTICLES so build.py renders them
with zero changes: blocks are tuples ("p", str) / ("h", str) /
("steps", [(title, desc), ...]) / ("ul", [..]) / ("tip", str) /
("quote", str) / ("table", [headers], [[cells], ...]).
"""

NEW_ARTICLES = [
    {
        "slug": "how-to-take-plant-cuttings",
        "title": "How to Take Plant Cuttings That Actually Root",
        "category": "growing",
        "icon": "cloning.svg",
        "read_min": 11,
        "summary": "The single most useful skill in the garden: turning one plant into ten for free. Here's exactly how I take softwood, hardwood, and root cuttings — and why some take and some rot.",
        "body": [
            ("p", "If I could teach a new gardener only one thing, it'd be this. Learning to root a cutting is the moment plants stop costing money and start multiplying themselves. One rosemary bush becomes a hedge. One fig becomes an orchard. A friend's tomato becomes yours. It's the closest thing to a superpower the garden offers, and almost anyone can do it on a windowsill."),
            ("p", "The whole trick is understanding that a cutting is a piece of plant racing to grow roots before it runs out of stored energy and rots. Everything you do is about tipping that race in the plant's favor: keep it alive, keep it humid, keep it from drying out, and give it the right kind of wood for the season."),
            ("h", "The three kinds of cuttings"),
            ("p", "Most propagation falls into three buckets, and knowing which one you're taking matters more than any rooting powder."),
            ("table", ["Type", "When", "Best for", "How it looks"],
             [["Softwood", "Spring–early summer", "Mints, sages, basil, coleus, most herbs", "New, flexible green growth that snaps cleanly"],
              ["Semi-hardwood", "Late summer", "Rosemary, lavender, many shrubs", "This year's growth, firming up but not woody"],
              ["Hardwood", "Winter dormancy", "Figs, mulberries, grapes, currants", "Bare, leafless, pencil-thick mature wood"]]),
            ("h", "Taking a softwood cutting, step by step"),
            ("p", "This is where to start, because softwood roots the fastest and the most forgivingly. Pick a healthy parent plant in the morning when it's full of water, and work fast so the cutting doesn't wilt."),
            ("steps", [
                ("Cut a 4–6 inch tip", "Choose a non-flowering shoot. Cut just below a leaf node (the little bump where a leaf meets the stem) — that node is where roots will form. A flowering shoot spends its energy on blooms instead of roots, so skip those."),
                ("Strip the lower leaves", "Remove leaves from the bottom half. Bare stem goes into the medium; any leaf buried in soil just rots. Leave two to four leaves up top to keep a little photosynthesis going."),
                ("Pinch big leaves in half", "If the remaining leaves are large, cut each one in half across. The cutting can't support a lot of leaf surface before it has roots, and less leaf means less water lost."),
                ("Set it in water or mix", "Either stand it in a glass of water on a bright windowsill, or push it two inches into damp, gritty potting mix. Water is easier to watch; mix gives sturdier roots. Both work."),
                ("Keep it humid and bright", "Out of direct hot sun. A clear bag or dome over a pot holds humidity. Change the water every couple days if you went that route."),
                ("Pot up when roots are an inch long", "Water-rooted cuttings move to soil once roots reach about an inch. Be gentle — water roots are brittle and need a week to toughen into soil."),
            ]),
            ("tip", "More is free. Take five cuttings when you need one. They cost nothing but a few minutes, and the failures don't matter when three of five take. This is the mindset that turns propagation from nerve-wracking to fun."),
            ("h", "Hardwood cuttings: the winter trick for fruit"),
            ("p", "Figs, mulberries, and grapes are some of the most valuable plants you can own, and they clone almost effortlessly in winter while they're dormant and leafless. There's no leaf to wilt and no rush — just patience."),
            ("steps", [
                ("Cut pencil-thick dormant wood", "In winter, take a length of last year's growth about as thick as a pencil and 8–10 inches long, with several buds along it."),
                ("Note which end is up", "Cut the bottom flat and the top at a slant so you don't accidentally plant it upside down — a cutting planted inverted will not grow."),
                ("Bury two-thirds", "Push it into a deep pot of gritty soil or straight into a nursery bed, leaving just the top bud or two above the surface."),
                ("Wait through spring", "Keep it barely moist and leave it alone. It will look like a dead stick for weeks. By spring it leafs out and roots underground at the same time."),
            ]),
            ("h", "Root cuttings and division — the other free plants"),
            ("p", "Some plants don't bother with stem cuttings at all. Comfrey, horseradish, and many natives grow from a chunk of root: a two-inch piece with a bit of crown will become a whole new plant. And clumping perennials — chives, lemongrass, asparagus, sorrel, many native grasses — simply get dug up in cool weather and split apart with a spade, each division replanted as its own plant."),
            ("quote", "A plant you can divide is a plant you'll never have to buy twice."),
            ("h", "Why cuttings fail (and how to stop it)"),
            ("ul", ["Rot before roots: too wet, too warm, or buried leaves. Use gritty mix and strip lower leaves.",
                    "Wilt and crisp: too dry or too much sun. Add a humidity dome and move out of direct heat.",
                    "Nothing happens for months: that can be normal for hardwood — be patient — but for softwood, you probably took it from old wood. Use fresh, flexible tips.",
                    "Flowers instead of roots: you used a flowering shoot. Pinch off any buds and choose vegetative growth."]),
            ("p", "Rooting hormone helps with stubborn woody plants but is completely optional for herbs and easy rooters. Honey or willow water are old folk versions if you want a kitchen substitute; plain clean water and the right cutting do most of the work."),
            ("tip", "Practice on mint or coleus first. They root so eagerly you'll build confidence in a week, and that confidence carries straight over to the plants you actually care about."),
            ("h", "What to clone first"),
            ("p", "Walk the database and you'll see which of your plants are cutting-friendly — nearly everything in the mint family, the figs and mulberries, grapes, prickly pear, and most of the tender houseplants. Start there, keep one healthy mother plant of each, and you'll never need to buy those varieties again. That's the whole Texas Roots idea in miniature: grow once, multiply forever."),
        ],
    },
    {
        "slug": "how-to-save-seeds",
        "title": "How to Save Seeds So You Never Buy Them Again",
        "category": "growing",
        "icon": "victory.svg",
        "read_min": 12,
        "summary": "Every heirloom seed is a promise: save it and it comes back true. Here's how to harvest, dry, clean, and store seed from your own garden — wet seeds, dry seeds, and the crossing rules that keep them honest.",
        "body": [
            ("p", "The entire reason I sell open-pollinated heirlooms and not hybrids comes down to one sentence: you can save the seed and it'll grow true next year. Buy a packet once, grow it well, save seed from your best plants, and that variety is yours for life. It's the most quietly radical thing a gardener can do — step off the buy-it-again treadmill entirely."),
            ("p", "Seed saving has a reputation for being fussy and scientific. It isn't. Plants have been handing humans their seed for ten thousand years and want to keep doing it. You just need to know two things: whether a seed is 'wet' or 'dry,' and which plants cross with their neighbors."),
            ("h", "Heirloom vs. hybrid — why it matters"),
            ("p", "An open-pollinated (heirloom) variety breeds true: its seed grows into the same plant. A hybrid (often labeled F1) is a one-time cross of two parents, and its seed scatters into a grab-bag of the grandparents — usually worse than either. You can save hybrid seed, but you can't count on what comes up. Every seed Texas Roots sends out is open-pollinated for exactly this reason."),
            ("tip", "If you only remember one rule: save seed from your best plants, never your worst. The biggest fruit, the plant that resisted disease, the one that didn't bolt in the heat. You're a breeder now — choose accordingly, and your strain gets tougher every year."),
            ("h", "Dry seeds: the easy ones"),
            ("p", "Beans, peas, lettuce, grains, okra, sunflowers, most herbs and flowers — these dry right on the plant and ask almost nothing of you. The technique is mostly patience."),
            ("steps", [
                ("Let it go past eating stage", "Leave pods, heads, or seed stalks on the plant until they're brown, dry, and rattly. A green bean you'd eat is far too young to save; let those pods turn papery."),
                ("Harvest on a dry day", "Pick when there's no dew or rain. Damp seed molds in storage faster than anything."),
                ("Thresh and winnow", "Crush dry pods or rub seed heads between your hands to free the seed, then pour it back and forth between bowls in a light breeze to blow off the chaff."),
                ("Dry a week more indoors", "Spread on a plate or screen out of sun for another week to drive off the last moisture. Seed should be hard enough that it doesn't dent under a fingernail."),
            ]),
            ("h", "Wet seeds: tomatoes, cucumbers, melons, squash"),
            ("p", "Seeds packed in wet flesh need that flesh removed, and tomatoes and cucumbers actually benefit from a short fermentation that mimics a fruit rotting on the ground. It smells bad for a few days and works beautifully."),
            ("steps", [
                ("Scoop seeds and pulp into a jar", "Add a splash of water. For tomatoes and cucumbers, this gel-coated seed is what you'll ferment."),
                ("Ferment 2–4 days", "Leave the jar on the counter, loosely covered. A mold raft forms on top — that's the point. It dissolves the germination-blocking gel and kills some seed-borne disease."),
                ("Rinse clean", "Add water, stir, and pour off the floating pulp and dead seeds. The good, heavy seed sinks. Repeat until what's left is clean."),
                ("Dry hard on a plate", "Spread on a ceramic plate (not paper — they stick) out of sun for a week or two until bone dry."),
            ]),
            ("p", "Melons, squash, and peppers skip the fermentation — just scoop, rinse the seeds clean of pulp, and dry them well. Easy."),
            ("h", "The crossing problem — and how to dodge it"),
            ("p", "Here's the one thing that trips people up. Many plants cross-pollinate, so if two varieties of the same species flower near each other, the seed you save is a mix. Some families are worse than others."),
            ("table", ["Crossing risk", "Plants", "What to do"],
             [["Low — self-pollinating", "Tomatoes, beans, peas, lettuce", "Save freely; minimal separation needed"],
              ["High — insect/wind crossed", "Squash, cucumbers, melons, corn, brassicas", "Grow one variety, or separate widely, or hand-pollinate and bag"],
              ["Crosses across the garden", "Brassicas (kale, cabbage, broccoli are one species)", "Let only one of the group flower for seed each year"]]),
            ("p", "For the beginner, the move is simple: start by saving the self-pollinators (tomatoes, beans, peas, lettuce). They come true with no effort and build your confidence. Tackle the cross-happy squash and corn once you understand the dance."),
            ("h", "Storing seed so it lasts"),
            ("p", "Three enemies kill stored seed: heat, moisture, and light. Beat all three and most seed stays viable for years."),
            ("ul", ["Cool, dark, and dry — a closet, not a sunny shelf. The fridge is excellent if seed is fully dry first.",
                    "Paper envelopes inside an airtight jar. Paper lets seed breathe; the jar keeps humidity out.",
                    "A packet of rice or silica gel in the jar pulls down moisture.",
                    "Label everything with variety and year. You will not remember. Nobody remembers."]),
            ("tip", "A simple viability test before spring: fold ten seeds in a damp paper towel, bag it, keep it warm, and count how many sprout in a week. Seven of ten means a 70% germination rate — sow a little thicker and you're fine."),
            ("quote", "Saved seed is the original heirloom. It carries your soil, your weather, and your choices forward into next year's garden."),
            ("h", "The bigger picture"),
            ("p", "Seed saving is the backbone of real food security. A pantry of stored seed you grew yourself, adapted to your own ground, is worth more than any amount you could buy in a panic. Pair it with the rest of the skills in this almanac — soil building, water catching, preservation — and you've built something that doesn't depend on anyone else's supply chain. That's the whole point. And it's why I keep a copy of all this knowledge offline too, on a home server, so the how-to survives even if the internet doesn't."),
        ],
    },
    {
        "slug": "propagation-by-plant-type",
        "title": "Every Way to Propagate a Plant, by Plant Type",
        "category": "growing",
        "icon": "soil.svg",
        "read_min": 10,
        "summary": "Seed, cutting, division, layering, grafting, slips, cloves, runners — a field guide to which method works for which plant, so you always know the cheapest way to make more.",
        "body": [
            ("p", "Plants reproduce in more ways than most people realize, and the cheapest, fastest route is different for every kind. Knowing which method matches which plant is the difference between buying nursery stock forever and filling your whole garden for free. This is the map I wish I'd had early on."),
            ("h", "From seed"),
            ("p", "The default for most annuals — vegetables, grains, many flowers and herbs. Cheap, abundant, and how you save your own stock from heirlooms. The catch is that hybrids and most tree fruit won't come true from seed, so seed is for annuals and for open-pollinated varieties you want to keep going."),
            ("ul", ["Best for: tomatoes, beans, peas, lettuce, squash, corn, most herbs and flowers.",
                    "Direct sow (no transplanting) for taprooted crops: carrots, beans, beets, dill.",
                    "Start in trays for slow or frost-tender crops: tomatoes, peppers, brassicas."]),
            ("h", "From cuttings"),
            ("p", "A piece of stem grows its own roots — an exact clone of the parent. The fastest way to multiply herbs, soft perennials, and many shrubs. Softwood in spring, hardwood in winter for woody plants."),
            ("ul", ["Softwood: mint, basil, sage, oregano, coleus, rosemary.",
                    "Hardwood: figs, mulberries, grapes, currants.",
                    "Stem-in-water: pothos, philodendron, monstera, many houseplants."]),
            ("h", "From division"),
            ("p", "Dig up a mature clumping plant in cool weather and split it into pieces, each with roots and shoots. Instant established plants, and it keeps the parent young by clearing out the dying center."),
            ("ul", ["Herbs: chives, lemongrass, French tarragon, mint runners.",
                    "Perennials: asparagus crowns, rhubarb, sorrel, daylilies.",
                    "Native grasses and many wildflowers in spring."]),
            ("h", "From layering"),
            ("p", "Bend a low branch to the ground, pin and bury a section, and it roots while still attached to and fed by the mother plant. Slow but nearly foolproof — the cutting can't dry out because it's still connected. Once rooted, cut it free."),
            ("ul", ["Brambles: blackberry and dewberry tip-root naturally where canes touch soil.",
                    "Grapes, figs, and many shrubs layer easily.",
                    "Strawberries do it for you, throwing rooting runners all season."]),
            ("h", "From specialized parts"),
            ("p", "Some plants offer their own purpose-built propagation organ, and these are among the easiest of all."),
            ("table", ["Part", "Plant", "Method"],
             [["Cloves", "Garlic, shallots", "Break the bulb apart, plant each clove in fall"],
              ["Sets / bulbs", "Onions, perennial onions", "Plant the little bulbs directly"],
              ["Tubers", "Potatoes", "Plant chunks with an eye each"],
              ["Slips", "Sweet potatoes", "Sprout shoots off a stored tuber, root and plant"],
              ["Rhizomes", "Ginger, turmeric, mint", "Plant a piece with a visible bud"],
              ["Pads", "Prickly pear", "Snap a pad, callus it, lay it on dry soil"],
              ["Crowns / offsets", "Asparagus, agave, aloe", "Plant crowns or detach 'pups'"]]),
            ("h", "From grafting"),
            ("p", "The advanced one, and the only way to reliably propagate tree fruit. A bud or shoot of the variety you want is joined onto a hardy rootstock. It's how every apple, peach, plum, pear, and citrus tree in a nursery is made, because their seed won't come true. Worth learning eventually, but not where a beginner needs to start."),
            ("tip", "Match the method to the plant and propagation gets dramatically easier. Trying to grow a fig from seed is a years-long gamble; a hardwood cutting gives you the same tree in one season. The plant is telling you how it wants to be multiplied — listen to it."),
            ("h", "A quick decision guide"),
            ("ol", ["Annual vegetable or herb? Seed (save your own from heirlooms).",
                    "Soft-stemmed herb or houseplant? Cutting.",
                    "Woody fruit like fig, grape, mulberry? Hardwood cutting.",
                    "Tree fruit (peach, apple, citrus)? Grafted nursery stock.",
                    "Clumping perennial? Division.",
                    "Low flexible branches? Layering.",
                    "Has cloves, tubers, slips, pads, or rhizomes? Use those — they're built for it."]),
            ("p", "Every plant page in the database tells you which of these applies, with the specifics for that species. Once this map is in your head, you'll never look at a plant the same way — you'll see ten future plants where there used to be one."),
        ],
    },
    {
        "slug": "growing-from-grocery-store",
        "title": "Plants You Can Grow Straight From the Grocery Store",
        "category": "survival",
        "icon": "victory.svg",
        "read_min": 9,
        "summary": "Before you spend a dime on seed, look in your kitchen. Ginger, garlic, green onions, potatoes, sweet potatoes and more will grow from what's already in the produce drawer. The cheapest garden there is.",
        "body": [
            ("p", "Here's a fun secret that's also a serious survival skill: a surprising amount of the produce aisle is alive and willing to grow. You don't always need a seed packet — sometimes you need a forgotten garlic head that's started to sprout. It's the cheapest possible way to start a garden, a great project with kids, and a genuine fallback if seed is ever hard to come by."),
            ("p", "The reason it works is that these foods are propagation organs — bulbs, tubers, rhizomes, roots — that the plant designed to start the next generation. The grocery store is just selling them as food. Plant them instead and they do what they were built to do."),
            ("h", "The sure things"),
            ("steps", [
                ("Green onions", "Save the white root ends, stand them in a glass of water on the windowsill, and they regrow tops in days. Plant them in soil and they keep going for months. The single easiest one."),
                ("Garlic", "A head that's begun to sprout is perfect. Break it into cloves and plant each one pointy-end up in fall; each becomes a whole new head by summer. Save your biggest for replanting and never buy it again."),
                ("Ginger and turmeric", "A knobby piece with a small bud (an 'eye') will sprout. Lay it just under warm, rich soil, keep it humid, and it sends up shoots. Containers are ideal so you can chase the warmth."),
                ("Sweet potatoes", "Suspend one half-in-water or bury it in damp sand; it pushes out leafy 'slips' you snap off and root. One sweet potato makes a dozen plants."),
                ("Potatoes", "A potato with eyes, cut into chunks with an eye or two each (let the cuts dry a day first), grows a whole hill of new potatoes."),
                ("Lemongrass", "Stalks with the base intact will root in a glass of water, then grow into a big clump in the ground."),
            ]),
            ("tip", "Buy organic where you can for this. Some conventional produce is treated with sprout inhibitors to extend shelf life, which is exactly the opposite of what you want. Organic ginger and potatoes sprout much more reliably."),
            ("h", "The 'worth a try' list"),
            ("ul", ["Celery and lettuce: stand the cut base in water and the center regrows a small second harvest of leaves.",
                    "Bok choy and cabbage: same trick — the base resprouts a flush of greens.",
                    "Pineapple: twist off the top, dry it a few days, root it. A multi-year project but a fun one.",
                    "Dried beans, peas, and popcorn from the bulk aisle: often perfectly viable seed for pennies a pound.",
                    "Herbs sold as living potted plants or fresh-cut stems (basil, mint): pot the plant, or root the cuttings."]),
            ("h", "Where this stops working"),
            ("p", "Be realistic about the limits. Most grocery tomatoes and peppers are hybrids, so their seed won't come true — fine for a fun experiment, not for a dependable crop. Citrus and apple seeds will sprout but take many years and won't match the parent fruit. And anything treated to not sprout simply won't. For a garden you can rely on, open-pollinated seed and proper starts are still the backbone. But as a free head start, a teaching tool, and a backstop, the kitchen garden is real."),
            ("quote", "A sprouting onion in the back of the drawer isn't waste. It's a plant asking to be planted."),
            ("h", "Why this belongs in a survival plan"),
            ("p", "Think about what this means if a supply chain ever stutters. The ability to look at ordinary food and see next season's crop is exactly the kind of knowledge that doesn't depend on anything. It costs nothing to practice now, while it's just a fun windowsill project — and the skill is there if you ever need it for real. Pair it with saved seed and the rest of the survival-garden skills in this almanac, and you've got a food system that starts in your own kitchen."),
        ],
    },
    {
        "slug": "extending-the-texas-growing-season",
        "title": "Extending the Growing Season on the Texas Gulf Coast",
        "category": "growing",
        "icon": "zones.svg",
        "read_min": 10,
        "summary": "Our problem isn't winter — it's summer. Here's how I push harvests through brutal heat and mild frost both, with shade, timing, succession, and a few cheap tricks to keep food coming nearly year-round.",
        "body": [
            ("p", "Gardeners in most of the country fight the cold. Down here on the Gulf Coast, our real enemy is the opposite — a wall of summer heat that shuts plants down as hard as any freeze. Understanding that flips the whole calendar. Our 'off season' is July and August, and our winters are mild enough to grow straight through. Once that clicks, you can keep food coming almost all year."),
            ("h", "We have two springs and a long fall"),
            ("p", "The single most important thing to internalize: in our climate, fall is the best growing season of the year. The brutal heat breaks, the soil is still warm, and cool-season crops planted in September and October thrive right through our gentle winters while the rest of the country is frozen out. Many people garden hard in spring, give up in summer, and miss the easiest, most productive window entirely."),
            ("table", ["Window", "Months", "What to grow"],
             [["Spring", "Feb–Apr", "Warm-season starts: tomatoes, peppers, squash, beans"],
              ["Summer", "May–Aug", "Only the heat-lovers: okra, southern peas, sweet potato, malabar spinach"],
              ["Fall (the best one)", "Sep–Nov", "Brassicas, greens, root crops, peas, a second tomato run"],
              ["Winter", "Dec–Jan", "Hardy greens, garlic, onions, cover crops; light frost protection"]]),
            ("h", "Beating the summer: shade and the right crops"),
            ("p", "Fighting summer is mostly about accepting it. Don't try to grow lettuce in July — grow the plants that love it instead. Okra, southern peas, sweet potato, malabar spinach, and the hot peppers actively thrive in heat that flattens everything else. For the crops that merely tolerate it, 30–40% shade cloth on a simple frame buys real relief, dropping leaf temperature enough to keep things producing."),
            ("tip", "Afternoon shade is worth more than morning shade here. If you can site summer crops where a fence or tree blocks the killer 3–6 p.m. sun, you've extended their season without spending a thing."),
            ("h", "Succession planting: the steady-supply trick"),
            ("p", "Instead of sowing a whole row of lettuce at once and drowning in it for two weeks, sow a short row every two to three weeks. You get a continuous trickle instead of a glut and famine. It's the difference between a garden that feeds you and a garden that overwhelms you and then quits."),
            ("ul", ["Fast crops to succession-sow: lettuce, radish, arugula, bush beans, cilantro, spinach.",
                    "Sow a little, often, through each crop's season.",
                    "Keep a few transplants coming in trays to fill gaps the moment something finishes."]),
            ("h", "Beating the cold: easy frost protection"),
            ("p", "Our frosts are usually light and brief, which makes protection cheap and easy. You rarely need a real greenhouse — you need to get a tender plant through a handful of cold nights."),
            ("steps", [
                ("Watch the forecast", "A radiational-freeze night — clear, calm, dry — is the dangerous kind. The live weather tool on this site flags the cold nights so you can act."),
                ("Cover before sunset", "Throw an old sheet, row cover, or even cardboard over tender plants in the evening to trap the day's ground heat. Take it off in the morning."),
                ("Water the day before", "Moist soil holds and releases more heat overnight than dry soil. A well-watered bed shrugs off a light frost better."),
                ("Use containers' mobility", "Anything in a pot can simply move to the porch or against a south wall for the night. That's half the reason I grow so much in containers."),
            ]),
            ("h", "Cold frames, low tunnels, and the greenhouse question"),
            ("p", "If you want to push further, a low tunnel — hoops of PVC or wire with row cover or plastic over them — turns a winter bed into a season-long salad factory for a few dollars. A cold frame (a bottomless box with a clear lid) does the same on a small scale. A full greenhouse is wonderful but rarely necessary on the Gulf Coast; our climate does most of the work if you simply plant with the seasons instead of against them."),
            ("quote", "Stop fighting the calendar and start reading it. In Texas, the gardener who plants in October eats all winter."),
            ("h", "Putting it together"),
            ("p", "Year-round harvest here isn't about heroic equipment. It's about timing your plantings to the real seasons, leaning into fall, choosing heat-lovers for summer, succession-sowing for a steady supply, and keeping a sheet handy for the few cold nights. Do that and the Texas Gulf Coast becomes one of the most productive places in the country to feed yourself. Check each plant's page for its specific best window, and let the weather tool handle the timing."),
        ],
    },
    {
        "slug": "container-growing-in-texas",
        "title": "Growing Food in Containers: The Texas Patio Garden",
        "category": "growing",
        "icon": "soil.svg",
        "read_min": 10,
        "summary": "No yard? No problem. A patio, balcony, or driveway can feed you — and in Texas, containers give you something priceless: the power to move a plant out of the killer afternoon sun or away from a freeze.",
        "body": [
            ("p", "You do not need land to grow real food in Texas. Some of the most productive growing I've seen happens on apartment balconies and bare concrete driveways, in pots. And here, containers aren't a compromise — they're a genuine advantage. When you can pick a plant up and move it, you can chase the shade in August and dodge the frost in January. A pot is a plant on wheels."),
            ("p", "The trade-off is that a container is a small, exposed world you're fully responsible for. It dries faster, heats faster, and runs out of food faster than the open ground. Get three things right — size, soil, and water — and the rest is easy."),
            ("h", "Size: bigger is more forgiving"),
            ("p", "The single most common mistake is too small a pot. A tiny container dries out by noon on a hot day and cooks the roots. <strong>When in doubt, size up.</strong> More soil means more water held, more root room, and a far more forgiving plant."),
            ("table", ["Crop", "Minimum pot", "Notes"],
             [["Herbs, lettuce, greens", "1–3 gallon", "Shallow-rooted; happy in window boxes"],
              ["Peppers, bush beans, chard", "3–5 gallon", "Steady producers in a 5-gallon bucket"],
              ["Tomatoes, eggplant, okra", "7–15 gallon", "The bigger the better — 15 gal for big tomatoes"],
              ["Dwarf fruit, potatoes", "15–25 gallon", "Half-barrels and grow bags shine here"]]),
            ("tip", "A cheap 5-gallon bucket with a few holes drilled in the bottom grows a fantastic tomato or pepper. Light-colored pots stay cooler than black ones in our sun — a real difference for the roots in July."),
            ("h", "Soil: never use dirt from the yard"),
            ("p", "Garden soil packs down like concrete in a pot and suffocates roots. Containers need a light, fluffy <strong>potting mix</strong> that holds water but still drains. A good mix is roughly equal parts quality potting soil, compost for fertility, and something gritty (perlite or coarse sand) for drainage. The compost matters — it's the slow-release engine that feeds the plant for months."),
            ("p", "Because every watering washes a little fertility out the bottom, container plants are hungrier than ground plants. Top-dress with compost or feed lightly and regularly through the season; a worm-castings tea or a balanced organic fertilizer keeps them cranking."),
            ("h", "Water: the make-or-break"),
            ("p", "This is where container gardens live or die in Texas. On a hot patio, a pot can need water <strong>every single day</strong>, sometimes twice. Check the top inch with your finger — if it's dry, water until it runs out the bottom. Don't water on a fixed schedule; water on what the soil tells you."),
            ("ul", ["Group pots together so they shade each other's sides and hold humidity.",
                    "Mulch the top of each pot — yes, even a pot — to slash evaporation.",
                    "Saucers help in peak summer but remove them in wet spells so roots don't sit in water.",
                    "Self-watering containers (with a reservoir) are worth it if you travel or forget."]),
            ("h", "The Texas superpower: mobility"),
            ("p", "Here's what makes container growing genuinely better than ground beds in our climate. A tender plant facing a rare hard freeze? Carry it to the porch or garage for the night. A young transplant wilting in a brutal late-June sun? Slide it into afternoon shade for a week to establish. A pepper that wants more sun? Move it. You're no longer stuck with where you planted — you garden the weather in real time. Pair that with our <a class='inline' href='weather.html'>live weather tool</a> and you can stay one step ahead of every cold snap and heat spike."),
            ("h", "What to grow first in pots"),
            ("p", "Start with the willing: herbs (basil, mint, rosemary, chives), leafy greens and lettuce, peppers, cherry tomatoes, bush beans, and green onions all thrive in containers. Many perennials on this site — garlic chives, Mexican oregano, sweet marjoram, even moringa kept coppiced — do beautifully in big pots too. Check any plant's page for its container suitability and root needs."),
            ("quote", "A balcony with ten good pots can put fresh food on your table every week of the year in Texas. Land is optional. Attention is not."),
        ],
    },
    {
        "slug": "how-to-make-compost",
        "title": "How to Make Compost: Turning Waste Into Black Gold",
        "category": "growing",
        "icon": "soil.svg",
        "read_min": 11,
        "summary": "The cheapest, most important soil amendment there is — and you're probably throwing the ingredients away. Here's how to turn kitchen scraps and yard waste into the rich, free compost that powers every great garden.",
        "body": [
            ("p", "If good gardening is really good soil-building, then compost is the single most valuable thing you can make. It loosens our heavy clay, helps sandy soil hold water, feeds the underground life that feeds your plants, and turns a waste stream you're already paying to haul away into the best amendment money can't buy. Gardeners call finished compost 'black gold' for a reason."),
            ("p", "And it's genuinely simple. Nature composts everything eventually whether you help or not — a pile of leaves in the woods becomes soil on its own. All you're doing is speeding it up and steering it. Don't overthink it."),
            ("h", "The only rule that matters: greens and browns"),
            ("p", "Composting is a balance of two things. <strong>Greens</strong> are wet, nitrogen-rich materials. <strong>Browns</strong> are dry, carbon-rich materials. Roughly two to three parts brown to one part green, by volume, gives you a pile that breaks down fast and never stinks."),
            ("table", ["Greens (nitrogen)", "Browns (carbon)"],
             [["Vegetable & fruit scraps", "Dry leaves"],
              ["Coffee grounds & filters", "Shredded cardboard & paper"],
              ["Fresh grass clippings", "Straw or dried hay"],
              ["Spent plants, trimmings", "Wood chips, sawdust"],
              ["Eggshells (crushed)", "Dry stalks & twigs"]]),
            ("tip", "If your pile smells bad, it's too wet and green — add browns and turn it. If nothing's happening, it's too dry and brown — add greens and water. That's 90% of all compost troubleshooting right there."),
            ("h", "What to keep OUT"),
            ("ul", ["Meat, fish, dairy, and grease — they smell and draw pests. (Worms and specialized systems can handle some, but skip them in a basic pile.)",
                    "Dog and cat waste — can carry pathogens; never on food-crop compost.",
                    "Diseased plants and seeding weeds — you'll spread problems.",
                    "Anything treated with herbicide — including some grass clippings and store-bought manures; persistent herbicides survive composting and damage gardens."]),
            ("h", "Building your pile, step by step"),
            ("steps", [
                ("Pick a spot and a method", "A simple 3-foot heap in a corner works. So does a wire ring, a wooden bin, or a tumbler. Bigger piles (around a cubic yard) heat up and finish faster; small ones still work, just slower."),
                ("Layer browns and greens", "Start with a layer of browns for drainage, then alternate — a thick layer of browns, a thinner layer of greens, and so on, like a lasagna. Moisten dry layers as you go."),
                ("Keep it as moist as a wrung-out sponge", "Damp, not soggy. In our summers you'll need to water the pile occasionally; in wet spells, cover it so it doesn't drown."),
                ("Turn it to speed things up", "Every week or two, fork the outside into the middle. This adds air (the microbes need oxygen) and mixes everything. More turning = faster compost. No turning still works — it just takes longer."),
                ("Harvest the black gold", "In a few months (faster if you turn and balance it well) the bottom of the pile becomes dark, crumbly, sweet-smelling compost. Screen out the chunks, return them to the pile, and spread the finished stuff on your beds and into your pots."),
            ]),
            ("h", "Texas-specific notes"),
            ("p", "Our heat is an advantage — piles cook fast here. But that same heat dries a pile out quickly, so moisture management is the main job in summer. In the heaviest heat, a pile in part shade holds water better. And because so much of our soil is alkaline clay, the organic matter compost adds is exactly what our ground is hungriest for."),
            ("h", "No room for a pile? You still have options"),
            ("ul", ["Worm bin (vermicompost): a tote of red wigglers under the sink or on a shaded porch turns kitchen scraps into the richest amendment of all. Perfect for apartments.",
                    "Trench composting: bury scraps a foot deep directly in an empty bed and let them break down in place.",
                    "Chop-and-drop: cut spent plants and lay them right on the bed as mulch — the laziest composting there is, and it works."]),
            ("quote", "Stop buying soil and start building it. Every scrap you compost is next season's harvest, for free."),
            ("p", "Once you're making your own compost, you've closed a loop: your garden feeds you, the scraps feed the pile, and the pile feeds the garden. That self-reliant cycle is the whole heart of what we do here — and it's the foundation under every other skill in this almanac."),
        ],
    },
]
