#!/usr/bin/env python3
"""Texas Roots — v5 new plant entries.

Real, structured horticultural rows in the exact plants_table tuple order:
(slug, common, latin, family, category, tags, sun, water, soil, ph, hardy,
 height, spacing, days, summary, uses, edible_parts, edible_caution,
 id1, id2, id3, companions, in_shop)

Chosen to fill genuine gaps and to show off the propagation engine: perennials
that divide, woody plants that root from cuttings, Texas natives, and a few
permaculture staples. All facts are real.
"""

NEW_PLANTS = [
    # ---------------- PERENNIAL VEGETABLES / PERMACULTURE ----------------
    ("egyptian-walking-onion","Egyptian Walking Onion","Allium ×proliferum","Amaryllidaceae (Amaryllis)","vegetable",
     "edible perennial full-sun beginner drought low-water container",
     "Full sun","Low once established","Well-drained","6.0–7.0","Hardy perennial",
     "2–3 ft","8–12 in","Year-round greens; bulbs in 2nd year",
     "A plant-it-once onion that replants itself by toppling over and rooting its top bulbils — the ultimate set-and-forget allium.",
     "Green onion tops, small bulbs","Whole plant","None of note.",
     "Hollow blue-green tubular leaves like a green onion","Clusters of tiny bulbils form on top of the stalk","Stalk bends and 'walks' the bulbils to new ground","Carrots; Beets; Lettuce","True"),
    ("potato-onion","Potato Onion","Allium cepa var. aggregatum","Amaryllidaceae (Amaryllis)","vegetable",
     "edible perennial full-sun beginner storage-crop",
     "Full sun","Moderate","Loose, well-drained","6.0–7.0","Hardy perennial",
     "12–18 in","6–8 in","90–120; replant largest",
     "An heirloom multiplier onion: plant one bulb, harvest a clump, save the biggest to replant forever. Stores beautifully.",
     "Bulbs and greens","Bulbs, greens","None of note.",
     "Onion-like clump dividing underground","Forms a nest of 4–12 bulbs from one","Long-storing dry bulbs","Carrots; Chamomile","False"),
    ("tree-collard","Tree Collard","Brassica oleracea (perennial)","Brassicaceae (Mustard)","vegetable",
     "edible perennial part-shade cut-and-come-again nutrient-dense",
     "Full sun to part shade","Even moisture","Rich, well-drained","6.0–7.5","Tender perennial",
     "4–8 ft","24–36 in","Greens within weeks; lives for years",
     "A collard that never quits — a woody perennial brassica you propagate from cuttings and harvest leaves from for years.",
     "Cooked greens","Leaves","None of note.",
     "Tall woody stalk topped with collard-like leaves","Often purple-tinged foliage","Rarely flowers; grown from cuttings","Beans; Onion; Dill","False"),
    ("sunchoke","Sunchoke (Jerusalem Artichoke)","Helianthus tuberosus","Asteraceae (Aster)","survival",
     "edible perennial full-sun drought low-water staple-calorie storage-crop vigorous native-adjacent",
     "Full sun","Low — very drought-tough","Almost any soil","5.5–7.5","Hardy perennial",
     "6–10 ft","18–24 in","120–150 to tubers",
     "A native sunflower that stores its calories underground as crisp, nutty tubers — nearly impossible to kill, and it feeds you every fall.",
     "Roasted, raw, mashed tubers","Tubers","Contains inulin — eat modest amounts at first to avoid gas.",
     "Tall sunflower stalks with rough leaves","Small yellow sunflowers in fall","Knobby tubers cluster at the base","Plant where it can spread; corral it","False"),
    ("scarlet-runner-bean","Scarlet Runner Bean","Phaseolus coccineus","Fabaceae (Legume)","vegetable",
     "edible perennial full-sun pollinator nitrogen-fixer beginner",
     "Full sun","Even moisture","Rich, well-drained","6.0–7.0","Tender perennial",
     "Vining 8–12 ft","6 in","60–70 for beans",
     "Brilliant red flowers hummingbirds fight over, edible beans, and tuberous roots that can overwinter — beauty and calories on one vine.",
     "Young pods, shelled beans, flowers","Pods, beans, flowers","Cook dry beans fully — raw beans contain lectins.",
     "Large heart-shaped leaflets in threes","Vivid scarlet pea flowers","Big speckled purple-black seeds","Corn; Squash; Sunflower","False"),

    # ---------------- HERBS ----------------
    ("garlic-chives","Garlic Chives","Allium tuberosum","Amaryllidaceae (Amaryllis)","herb",
     "edible perennial full-sun beginner drought pollinator container cut-and-come-again",
     "Full sun to part shade","Low to moderate","Average, well-drained","6.0–7.0","Hardy perennial",
     "12–18 in","8 in","Cut greens within weeks",
     "Flat-leaved chives with a true garlic flavor, white edible flowers, and the toughness to divide into a lifetime supply.",
     "Greens, flowers","Leaves, flowers","None of note.",
     "Flat, grass-like leaves (not hollow)","White star flowers in late summer","Mild garlic scent when crushed","Carrots; Roses; Tomato","False"),
    ("mexican-oregano","Mexican Oregano","Poliomintha longifolia","Lamiaceae (Mint)","herb",
     "edible perennial full-sun drought low-water heat-lover pollinator native-adjacent",
     "Full sun","Low — drought-tough","Lean, well-drained","6.5–8.0","Hardy perennial",
     "2–4 ft","24 in","Harvest leaves anytime",
     "Not true oregano but better for Tex-Mex cooking, and a tough flowering shrub that roots from cuttings and laughs at heat.",
     "Leaves dried or fresh","Leaves, flowers","None of note.",
     "Small narrow aromatic leaves","Tubular lavender-pink flowers loved by bees","Woody-based mounding shrub","Peppers; Tomatillo","False"),
    ("perilla","Perilla (Shiso)","Perilla frutescens","Lamiaceae (Mint)","herb",
     "edible annual part-shade heat-lover beginner pollinator",
     "Full sun to part shade","Even moisture","Average","6.0–7.0","Warm-season annual; self-sows",
     "18–36 in","12 in","Leaves in 60–70",
     "An aromatic Asian herb that self-sows once planted and thrives in Texas heat — purple or green leaves with a unique anise-mint flavor.",
     "Leaves, seeds","Leaves, seeds","None of note for the culinary type.",
     "Broad toothed leaves, often deep purple","Square mint-family stems","Tiny flower spikes; reseeds freely","Reseeds — let a few flower","False"),
    ("sweet-marjoram","Sweet Marjoram","Origanum majorana","Lamiaceae (Mint)","herb",
     "edible perennial full-sun drought container beginner pollinator",
     "Full sun","Low to moderate","Light, well-drained","6.5–8.0","Tender perennial",
     "12–24 in","10 in","Harvest leaves in 60",
     "Oregano's gentler, sweeter cousin — a tidy aromatic that roots from cuttings and earns a pot by any sunny door.",
     "Leaves fresh or dried","Leaves, flowers","None of note.",
     "Tiny gray-green oval leaves","Knot-like flower buds (the 'knotted marjoram')","Low mounding habit","Most vegetables; near roses","False"),
    ("yarrow","Yarrow","Achillea millefolium","Asteraceae (Aster)","herb",
     "medicinal perennial full-sun drought low-water pollinator native-tx",
     "Full sun","Low — very drought-tough","Lean, well-drained","5.5–8.0","Hardy perennial",
     "1–3 ft","12–18 in","Blooms first summer from spring sow",
     "An ancient first-aid herb and pollinator magnet that spreads by runners and divides endlessly — tough as any Texas native.",
     "Leaves and flowers (traditional medicinal)","Leaves, flowers — medicinal use","Some people get skin sensitivity; avoid in pregnancy. Not a food crop.",
     "Feathery, fern-like soft leaves","Flat clusters of tiny white flowers","Aromatic when crushed","Spreads by rhizome — divides easily","False"),

    # ---------------- FRUIT & WOODY (cutting/grafting showcase) ----------------
    ("american-persimmon","American Persimmon","Diospyros virginiana","Ebenaceae (Ebony)","fruit",
     "edible perennial full-sun drought low-water native-tx staple-calorie storage-crop",
     "Full sun","Low once established","Adaptable, well-drained","6.0–7.5","Hardy native tree",
     "30–60 ft","20+ ft","Fruit after 3–6 years",
     "A tough native tree dropping intensely sweet fruit after frost — wildlife loves it, and so will you once it's dead ripe.",
     "Ripe fruit fresh, dried, baked","Fully ripe fruit only","Unripe fruit is mouth-puckeringly astringent — wait until soft and frost-touched.",
     "Blocky dark 'alligator-skin' bark","Glossy oval leaves","Orange fruit clings after leaf drop","Plant male + female for fruit","False"),
    ("moringa","Moringa (Drumstick Tree)","Moringa oleifera","Moringaceae","survival",
     "edible perennial full-sun drought heat-lover nutrient-dense staple-calorie vigorous",
     "Full sun","Low — drought-tough","Sandy, well-drained","6.3–7.0","Tender perennial (root-hardy)",
     "10–30 ft (cut back yearly)","8–10 ft","Edible leaves in one season",
     "One of the most nutritious plants on earth and astonishingly fast — grows from a cutting or seed and gives leaves the first summer.",
     "Leaves, young pods, flowers","Leaves, young pods, flowers","Avoid the root and bark; eat leaves and young pods.",
     "Fern-like compound leaves","Long bean-like 'drumstick' pods","Soft, fast-growing trunk","Coppice it low to keep leaves in reach","False"),
    ("roselle","Roselle (Florida Cranberry)","Hibiscus sabdariffa","Malvaceae (Mallow)","fruit",
     "edible annual full-sun heat-lover pollinator container",
     "Full sun","Moderate","Rich, well-drained","6.0–6.8","Warm-season annual",
     "5–7 ft","36 in","Calyces in ~120; harvest before frost",
     "The hibiscus behind agua de jamaica — a stunning heat-lover whose tart red calyces make tea, jam, and syrup all summer.",
     "Calyces for tea, jam, syrup; young leaves","Calyces, young leaves","Eat the fleshy red calyx, not the seed pod inside.",
     "Deeply lobed reddish leaves","Pale yellow hibiscus flowers","Swollen red calyx after the bloom","Okra; Peppers","False"),

    # ---------------- TEXAS NATIVES ----------------
    ("texas-mountain-laurel","Texas Mountain Laurel","Dermatophyllum secundiflorum","Fabaceae (Legume)","native",
     "perennial full-sun drought low-water pollinator native-tx",
     "Full sun","Very low — xeric","Rocky, alkaline, sharp drainage","7.0–8.5","Hardy native evergreen",
     "10–25 ft","10+ ft","Slow; blooms when mature",
     "An evergreen native that perfumes early spring with grape-soda-scented purple flowers — bulletproof once established, but its seeds are toxic.",
     "Not for eating","Not a food plant — seeds are highly toxic","WARNING: the red 'mescal beans' are poisonous. Grown for beauty and pollinators only.",
     "Glossy evergreen compound leaves","Drooping purple wisteria-like flower clusters","Hard woody pods with bright red seeds","Pollinator plant; keep seeds from kids/pets","False"),
    ("desert-willow","Desert Willow","Chilopsis linearis","Bignoniaceae (Trumpet-creeper)","native",
     "perennial full-sun drought low-water pollinator native-tx",
     "Full sun","Very low — xeric","Lean, well-drained","6.5–8.5","Hardy native",
     "15–25 ft","12+ ft","Blooms first or second year",
     "Not a true willow but a small native tree covered all summer in orchid-like pink trumpets that hummingbirds can't resist.",
     "Not for eating","Not a food plant","Grown for pollinators and shade, not food.",
     "Long, narrow willow-like leaves","Frilly pink-lavender trumpet flowers","Long slender seed pods","Hummingbird and bee magnet","False"),
    ("frogfruit","Frogfruit","Phyla nodiflora","Verbenaceae (Verbena)","native",
     "perennial full-sun part-shade drought low-water pollinator native-tx",
     "Full sun to part shade","Low — tough","Almost any soil","6.0–8.0","Hardy native groundcover",
     "2–4 in tall, spreading","Spreads to fill","Fills in within a season",
     "A native lawn alternative — a tough, mat-forming groundcover dotted with tiny flowers that feed pollinators and shrug off foot traffic.",
     "Not a food crop","Not for eating — pollinator groundcover","Grown as living groundcover, not food.",
     "Low mat of small toothed leaves","Tiny white-to-pink flower heads on stalks","Roots at every node as it spreads","Lawn alternative; erosion control","False"),
    ("horsemint","Horsemint (Spotted Beebalm)","Monarda punctata","Lamiaceae (Mint)","native",
     "medicinal perennial full-sun drought low-water pollinator native-tx",
     "Full sun","Low — drought-tough","Sandy, well-drained","6.0–7.5","Hardy native",
     "1–3 ft","12–18 in","Blooms first summer",
     "A wildly architectural native beebalm with stacked pink bracts — a pollinator powerhouse, thymol-scented, and tough as Texas sand.",
     "Leaves for tea (traditional)","Leaves — herbal tea","Strong; medicinal/tea use, not a vegetable. Avoid large amounts in pregnancy.",
     "Square stems, narrow aromatic leaves","Stacked tiers of pink-purple bracts","Spotted yellow tubular flowers","Pollinator and beneficial-insect plant","False"),

    # ---------------- WILD & FORAGED ----------------
    ("wild-garlic","Wild Garlic / Wild Onion","Allium canadense","Amaryllidaceae (Amaryllis)","wild",
     "edible perennial wild forage native-tx beginner-forage drought",
     "Full sun to part shade","Low — tough","Most soils","6.0–7.5","Hardy native perennial",
     "8–18 in","Wild clumps","Forage spring greens & bulbs",
     "A common native onion of Texas fields and lawns — every part is edible, and the smell is the foolproof safety test.",
     "Greens, bulbs, flowers","Leaves, bulb, bulbils, flowers","SAFETY: only eat it if it smells distinctly of onion or garlic. If there's no allium smell, it is NOT this plant — some toxic lookalikes exist.",
     "Grass-like leaves smelling strongly of onion","Cluster of pink-white flowers or bulbils on top","Small bulb underground","Forage from clean, unsprayed ground only","False"),
    ("plantain-broadleaf","Broadleaf Plantain","Plantago major","Plantaginaceae (Plantain)","wild",
     "edible medicinal perennial wild forage beginner-forage drought nutrient-dense",
     "Full sun to part shade","Low — very tough","Compacted, poor, or rich","5.5–7.5","Hardy perennial weed",
     "4–10 in","Wild","Forage leaves anytime",
     "The 'band-aid plant' growing in every driveway crack — young leaves are edible greens and the crushed leaf is a famous field poultice.",
     "Young leaves, seeds","Young leaves, seeds","Mature leaves get stringy; eat young. The famous first-aid use is topical.",
     "Broad oval ribbed leaves in a flat rosette","Parallel veins run leaf to stalk","Stiff seed spikes like a rat's tail","Thrives in compacted soil","False"),
    ("chufa","Chufa (Tiger Nut)","Cyperus esculentus var. sativus","Cyperaceae (Sedge)","survival",
     "edible perennial full-sun staple-calorie storage-crop nutrient-dense",
     "Full sun","Moderate to high","Loose, sandy","5.5–7.5","Tender perennial (grown as annual)",
     "1–2 ft grass-like","6 in","90–120 to tubers",
     "A grass-like sedge that makes sweet, nutty underground tubers — the original ingredient in horchata, and a calorie crop that stores dry for years.",
     "Tubers raw, dried, milk (horchata)","Tubers","The cultivated chufa is the edible one; wild yellow nutsedge is an aggressive weed.",
     "Triangular grass-like stems (sedge)","Clumps of slender leaves","Small sweet tubers on the roots","Containers recommended — can spread","False"),

    # ---------------- v6.5 additions ----------------
    ("borage","Borage","Borago officinalis","Boraginaceae (Borage)","herb",
     "edible annual full-sun pollinator beginner drought self-sows",
     "Full sun","Low to moderate","Average, well-drained","6.0–7.5","Annual; self-sows",
     "18–36 in","18 in","Edible flowers in 8 weeks",
     "A pollinator magnet with cucumber-flavored leaves and brilliant blue star flowers — plant it once and it reseeds itself forever.",
     "Young leaves, flowers","Young leaves, flowers","Eat young leaves in moderation; older leaves are fuzzy. Flowers are a lovely garnish.",
     "Bristly gray-green leaves","Five-pointed blue star flowers","Whole plant smells of cucumber","Tomatoes; Squash; Strawberries","False"),
    ("nasturtium","Nasturtium","Tropaeolum majus","Tropaeolaceae (Nasturtium)","herb",
     "edible annual full-sun beginner pollinator container drought",
     "Full sun","Low — lean soil","Poor, well-drained (rich soil = all leaves)","6.0–7.5","Warm-season annual",
     "Mounding or trailing 1–6 ft","10–12 in","Flowers in 50–60",
     "A peppery edible flower that thrives on neglect — every part is edible, it lures aphids away from your crops, and kids love it.",
     "Leaves, flowers, seed pods","Leaves, flowers, green seed pods","Peppery like watercress; green pods can be pickled as 'poor man's capers'.",
     "Round shield-shaped leaves","Spurred orange, yellow, red flowers","Trails or mounds","Squash; Cucumber; Tomato (trap crop)","False"),
    ("chiltepin","Chiltepin (Bird Pepper)","Capsicum annuum var. glabriusculum","Solanaceae (Nightshade)","native",
     "edible perennial full-sun part-shade heat-lover drought native-tx pollinator",
     "Full sun to part shade","Low once established","Well-drained","6.0–7.5","Tender perennial (root-hardy)",
     "2–4 ft","24 in","Peppers in 90–120",
     "The wild mother of all peppers — a tiny, fiery native chile that birds spread, beloved across South Texas and shrugs off heat and drought.",
     "Ripe red peppers","Ripe fruit","Very hot — use sparingly. Wear gloves if processing a lot.",
     "Small leaves on a wiry bush","Tiny white flowers","Pea-sized round red peppers","Tomatoes; Basil; under mesquite","False"),
    ("chaya","Chaya (Tree Spinach)","Cnidoscolus aconitifolius","Euphorbiaceae (Spurge)","survival",
     "edible perennial full-sun heat-lover drought nutrient-dense vigorous staple-calorie",
     "Full sun to part shade","Low — drought-tough","Adaptable","6.0–7.5","Tender perennial (root-hardy)",
     "6–10 ft","6 ft","Leaves year-round once established",
     "A Maya superfood shrub that pumps out nutritious greens through the worst heat, roots from a stick, and outlives nearly everything.",
     "Cooked leaves only","Leaves — must be cooked","IMPORTANT: leaves must be cooked 5+ minutes before eating (raw leaves contain cyanogenic compounds). Never eat raw. Then perfectly safe and very nutritious.",
     "Large maple-like lobed leaves","Milky sap when cut","Woody shrub, grows from cuttings","Coppice for tender leaves","False"),
    ("cranberry-hibiscus","Cranberry Hibiscus","Hibiscus acetosella","Malvaceae (Mallow)","herb",
     "edible perennial full-sun heat-lover pollinator drought container",
     "Full sun","Moderate","Rich, well-drained","6.0–7.0","Tender perennial",
     "4–6 ft","36 in","Leaves all season",
     "Deep-maroon edible foliage with a tangy cranberry bite — ornamental enough for the front bed, productive enough for the salad bowl.",
     "Young leaves, flowers","Leaves, flowers","Tart, lemony; great raw young or cooked. Roots easily from cuttings.",
     "Burgundy maple-like leaves","Yellow-to-pink hibiscus flowers","Striking dark foliage","Okra; Roselle; Peppers","False"),
    ("molokhia","Molokhia (Egyptian Spinach)","Corchorus olitorius","Malvaceae (Mallow)","vegetable",
     "edible annual full-sun heat-lover nutrient-dense beginner",
     "Full sun","Moderate","Rich, well-drained","6.0–7.5","Warm-season annual",
     "3–6 ft","8 in","Leaves in 60",
     "A heat-loving leafy green that grows when summer kills everything else — the silky base of Egypt's famous green soup.",
     "Leaves","Leaves","Cook the leaves; they thicken stews beautifully. Loves the hottest months.",
     "Narrow toothed bright-green leaves","Small yellow flowers","Tall upright stalks","Okra; Peppers; Roselle","False"),
    ("jicama","Jícama","Pachyrhizus erosus","Fabaceae (Legume)","vegetable",
     "edible annual full-sun heat-lover nitrogen-fixer storage-crop",
     "Full sun","Moderate","Loose, deep, well-drained","6.0–7.0","Warm-season annual",
     "Vining 10–15 ft","12 in","150–180 (long season)",
     "A crisp, sweet, apple-like root you grow on a vine — a tropical legume that loves our long hot summers.",
     "Root only","The root (tuber)","WARNING: only the root is edible. The pods, seeds, and foliage are toxic — never eat them.",
     "Bean-like trifoliate leaves","Blue-violet pea flowers","Large round tan tuber underground","Corn; Squash (long season)","False"),
    ("pigeon-pea","Pigeon Pea","Cajanus cajan","Fabaceae (Legume)","survival",
     "edible perennial full-sun drought low-water nitrogen-fixer staple-calorie heat-lover",
     "Full sun","Very low — drought-tough","Almost any soil","5.0–8.0","Tender perennial (short-lived)",
     "6–12 ft","4 ft","Green pods ~120; dry peas later",
     "A drought-proof shrubby legume giving protein-rich peas, firewood, and nitrogen all at once — a backbone crop of the tropics.",
     "Green or dried peas","Peas (seeds)","Cook like any dry pea/bean. Fixes nitrogen and makes great chop-and-drop mulch.",
     "Trifoliate leaves on a tall shrub","Yellow-and-red pea flowers","Flat pods of round peas","Plant as a windbreak/support row","False"),
    ("orach","Orach (Mountain Spinach)","Atriplex hortensis","Amaranthaceae (Amaranth)","vegetable",
     "edible annual full-sun beginner drought self-sows heat-tolerant",
     "Full sun","Low to moderate","Average; tolerates salty/alkaline","6.5–8.0","Cool-to-warm annual",
     "4–6 ft","12 in","Leaves in 40–60",
     "An old-world spinach substitute that handles heat and alkaline soil far better than spinach — and the red type is gorgeous.",
     "Young leaves","Leaves","Use like spinach raw or cooked; harvest young. Self-sows readily.",
     "Arrowhead leaves, green or deep red","Tall seed spikes","Tolerates poor, salty soil","Beans; Corn","False"),
    ("salsify","Salsify (Oyster Plant)","Tragopogon porrifolius","Asteraceae (Aster)","vegetable",
     "edible biennial full-sun storage-crop beginner",
     "Full sun","Moderate","Deep, loose, stone-free","6.0–7.5","Biennial (grown as annual)",
     "2–3 ft","3 in","120–150 to roots",
     "An old-fashioned root vegetable with a faint oyster flavor — sow it, forget it, and dig sweet roots after the first frost.",
     "Roots, young shoots","Root, young spring shoots","Mild oyster-like taste; roots sweeten after frost.",
     "Grass-like leaves","Purple dandelion-like flower","Long tapering pale root","Carrots; Beets","False"),
    ("aronia","Aronia (Chokeberry)","Aronia melanocarpa","Rosaceae (Rose)","fruit",
     "edible perennial full-sun part-shade drought low-water pollinator nutrient-dense storage-crop",
     "Full sun to part shade","Low once established","Adaptable, tolerates wet","5.0–7.0","Hardy shrub",
     "3–6 ft","4–5 ft","Fruit in 2–3 years",
     "One of the highest-antioxidant fruits there is — a tough, pest-free native-type shrub whose dark berries make superb juice, jam, and wine.",
     "Berries (usually processed)","Berries","Astringent fresh ('choke'berry) but excellent juiced, dried, or in jam. Roots from suckers.",
     "Glossy leaves, red fall color","White spring flower clusters","Clusters of near-black berries","Pollinator shrub border","False"),
    ("elderberry","Elderberry","Sambucus canadensis","Adoxaceae (Moschatel)","fruit",
     "edible medicinal perennial full-sun part-shade pollinator native-tx storage-crop vigorous",
     "Full sun to part shade","Moderate to high","Rich, moist","5.5–6.5","Hardy native",
     "6–12 ft","6 ft","Fruit in 2–3 years",
     "A vigorous native shrub famous for immune-supporting berries and elderflower — and it roots from a bare winter stick almost every time.",
     "Cooked ripe berries, flowers","Ripe cooked berries; flowers","IMPORTANT: eat only ripe berries and only cooked. Raw berries, leaves, stems, and roots are toxic. Flowers are safe for cordial/tea.",
     "Compound leaves, hollow stems","Flat white flower umbels","Clusters of tiny dark-purple berries","Native pollinator shrub; near water","False"),
]

# ---------------- v8: TEXAS NATIVES / HOMESTEAD ADDITIONS ----------------
V8_PLANTS = [
    ("pecan","Pecan","Carya illinoinensis","Juglandaceae (Walnut)","fruit",
     "edible perennial full-sun native-tx storage-crop staple-calorie shade-tree",
     "Full sun","Deep, infrequent; needs water in nut fill","Deep, well-drained alluvial","6.0-7.0","Hardy native tree",
     "70-100 ft","35-50 ft","Nuts in 6-10 years from transplant",
     "The Texas state tree and the finest native calorie crop we have - a well-sited pecan feeds a family every fall for a century.",
     "Raw or roasted nuts, baking","Nut kernels","None of note. Plant two cultivars (type I + type II) for reliable pollination.",
     "Long compound leaves with 9-17 curved leaflets","Green husks split into 4 sections in fall","Smooth brown nut with darker mottling","Give it room - allelopathic to some plants under the canopy","False"),
    ("texas-persimmon","Texas Persimmon","Diospyros texana","Ebenaceae (Ebony)","native",
     "edible perennial full-sun drought low-water native-tx wildlife",
     "Full sun to part shade","Very low - drought-proof once established","Rocky, alkaline-tolerant","6.5-8.0","Hardy native",
     "10-25 ft","10-15 ft","Fruit in 4-6 years",
     "A sculptural little native tree with peeling silver bark and sweet black fruit - built for Texas heat, caliche, and neglect.",
     "Fresh ripe fruit, jam","Fully ripe black fruit","Only fully ripe (soft, black) fruit - unripe is mouth-puckering astringent. Stains everything.",
     "Smooth gray bark peeling to reveal white/pink underbark","Small leathery leaves, fuzzy underneath","Black 1-inch fruit on female trees only","Wildlife hedge; pairs with agarita and cenizo","False"),
    ("maypop","Maypop (Passionflower)","Passiflora incarnata","Passifloraceae (Passionflower)","native",
     "edible medicinal perennial full-sun pollinator native-tx vigorous vine",
     "Full sun to part shade","Moderate; drought-tolerant once set","Any well-drained","6.0-7.5","Hardy native perennial",
     "Vining 10-25 ft","4-6 ft","Fruit 70-80 days after flowering",
     "The native passionfruit - an outrageous purple flower, egg-sized fruit, and the host plant for gulf fritillary butterflies, all on one unkillable vine.",
     "Fresh fruit pulp, juice; leaves as calming tea","Ripe fruit pulp; leaves (tea)","Ripe fruit only - green fruit and rind can upset the stomach. Dies to the ground each winter and returns from the root.",
     "Deeply 3-lobed leaves on a climbing vine","Intricate purple-and-white fringed flower","Green egg-shaped fruit that wrinkles when ripe","Fences and arbors; expect it to sucker and spread","False"),
    ("texas-redbud","Texas Redbud","Cercis canadensis var. texensis","Fabaceae (Legume)","native",
     "edible perennial full-sun part-shade drought native-tx pollinator ornamental",
     "Full sun to part shade","Low once established","Well-drained, limestone-loving","6.5-8.0","Hardy native",
     "15-25 ft","15 ft","Flowers in 3-4 years",
     "Spring's first fireworks - magenta flowers on bare branches, and yes, those flowers are edible. The glossy-leaf Texas variety laughs at limestone and drought.",
     "Flowers in salads; young pods cooked","Flowers, very young pods","Eat in modest amounts; a garnish and forage nibble, not a staple.",
     "Heart-shaped glossy leaves (Texas var. is waxier than eastern)","Magenta pea-flowers straight from the bark in early spring","Flat brown seed pods hang into winter","Understory tree; fixes a little nitrogen","False"),
    ("wax-myrtle","Wax Myrtle","Morella cerifera","Myricaceae (Bayberry)","native",
     "perennial full-sun part-shade native-tx evergreen hedge wildlife nitrogen-fixer",
     "Full sun to part shade","Adaptable - wet or dry","Any; tolerates poor soil","5.0-7.5","Hardy native evergreen",
     "10-20 ft","6-10 ft","Fast - 2-3 ft/year",
     "The Gulf Coast's workhorse evergreen screen: fragrant bayberry foliage, waxy berries for candles, bird habitat, and it even fixes its own nitrogen.",
     "Leaves as a bay-like seasoning; berry wax for candles","Leaves (seasoning, remove before serving)","Seasoning leaf like bay - flavor, don't eat the leaf itself.",
     "Aromatic narrow olive-green leaves, crushed smell of bayberry","Clusters of tiny gray-blue waxy berries on female plants","Multi-trunked, dense evergreen habit","Privacy hedge; windbreak around the garden","False"),
    ("mustang-grape","Mustang Grape","Vitis mustangensis","Vitaceae (Grape)","wild",
     "edible perennial full-sun drought native-tx vigorous foraging vine",
     "Full sun","None needed - fully wild-adapted","Any","6.0-8.0","Hardy native",
     "Climbing 30+ ft","N/A - foraged","Ripe mid-June to August",
     "The fence-line grape of Texas - ferociously acidic raw, but the backbone of generations of jelly and country wine. If a grapevine is swallowing a fence in July, it's probably this.",
     "Jelly, juice, wine (sweetened)","Ripe purple-black fruit, processed","Raw fruit is harshly acidic and can irritate skin and mouth - wear gloves when picking volume; always process. Verify it is a true grape (see lookalikes on the ID page).",
     "Leaves whitish and woolly underneath - the giveaway","Forked tendrils opposite the leaves (true grapes)","Loose clusters of large purple-black grapes","Forage plant - manage on fences, don't plant near trees you love","False"),
    ("flameleaf-sumac","Flameleaf Sumac","Rhus lanceolata","Anacardiaceae (Cashew)","wild",
     "edible perennial full-sun drought low-water native-tx foraging pollinator",
     "Full sun","Very low","Poor, rocky, sandy","6.0-8.0","Hardy native",
     "15-25 ft","10 ft","Berries late summer",
     "Blazing red fall color and fuzzy red berry clusters that make sumac-ade - a lemony trail drink Texans have brewed for generations.",
     "Berry clusters steeped for 'sumac-ade'; spice","Red berry clusters (steeped, strained)","RED fuzzy upright berries only. Poison sumac has WHITE drooping berries and grows in swamps - it does not overlap with this plant's dry habitat. Strain the fine hairs before drinking.",
     "Compound leaves with winged midrib between leaflets","Upright cone-shaped clusters of fuzzy dark-red berries","Brilliant scarlet fall foliage","Erosion control on slopes; thicket-former","False"),
    ("sugar-hackberry","Sugar Hackberry","Celtis laevigata","Cannabaceae (Hemp)","wild",
     "edible perennial full-sun drought native-tx foraging wildlife shade-tree",
     "Full sun to part shade","None needed","Any - famously unfussy","6.0-8.0","Hardy native",
     "40-60 ft","30 ft","Berries in fall",
     "The tree Texans love to hate is secretly a survival food: hackberry drupes are a crunchy natural trail mix - thin sweet skin over an edible protein-rich seed.",
     "Whole ripe berries eaten crunched, seed and all","Ripe orange-red to purple drupes","Hard seed - crunch carefully or grind; a nibble food, not a bushel crop.",
     "Warty gray bark ridges on a smooth trunk","Asymmetrical sandpapery leaves","Pea-sized orange-to-purple berries in fall","Volunteer tree - keep the good ones for shade and birds","False"),
    ("live-oak-acorn","Live Oak (Acorns)","Quercus virginiana","Fagaceae (Beech)","survival",
     "edible perennial full-sun drought native-tx staple-calorie foraging shade-tree",
     "Full sun","None needed once established","Any deep soil","5.5-7.5","Hardy native evergreen",
     "40-80 ft, wider than tall","40+ ft","Acorns every fall; heavy mast years cycle",
     "Every live oak on your land is a flour mill waiting on you: leached acorn meal fed every culture that ever lived under oaks, and Texas is covered in them.",
     "Leached acorn flour for baking; roasted nibbles","Acorn kernels AFTER leaching","MUST be leached: soak shelled, ground acorns in several changes of water until the bitterness (tannin) is gone. Unleached acorns are astringent and hard on the stomach.",
     "Evergreen leathery leaves, dark above and pale below","Sprawling horizontal limbs that touch the ground with age","Slender acorns in clusters, caps cover 1/3","The homestead anchor tree - build the garden around its afternoon shade","False"),
    ("lemon-beebalm","Lemon Beebalm (Horsemint)","Monarda citriodora","Lamiaceae (Mint)","herb",
     "edible medicinal full-sun drought low-water native-tx pollinator reseeding annual",
     "Full sun","Low","Sandy, well-drained","6.0-8.0","Native annual - reseeds",
     "12-30 in","12 in","Blooms 60-75 days from seed",
     "The purple pagoda-flowered mint that covers Texas roadsides in May - citrusy tea leaves, a pollinator magnet, and it plants itself for free every year after.",
     "Herbal tea, seasoning; pollinator plant","Leaves and flowers","Oregano-thyme-citrus flavor - strong, use a light hand. Reseeds enthusiastically.",
     "Square stems (mint family)","Stacked whorls of pink-purple flowers in tiers","Citrus-oregano smell when crushed","Between vegetable rows to pull in pollinators","False"),
    ("maximilian-sunflower","Maximilian Sunflower","Helianthus maximiliani","Asteraceae (Aster)","native",
     "edible perennial full-sun drought native-tx pollinator wildlife tall",
     "Full sun","Low","Any - clay to sand","6.0-8.0","Hardy native perennial",
     "5-10 ft","24-36 in","Blooms Sept-Oct; established year 2",
     "A wall of gold every October, from a native perennial sunflower that never needs replanting - seeds for the birds, tubers-adjacent roots for the soil, and armloads of cut flowers.",
     "Seeds (small but edible); young shoots cooked","Seeds, young spring shoots","Small seeds - more of a wildlife and forage plant than a crop. Spreads by rhizome; give it a back fence.",
     "Narrow folded gray-green leaves on tall stalks","Dozens of 3-inch gold flowers up the top third of each stem","Fall bloom when little else flowers","Back-border windbreak; quail and songbird cover","False"),
    ("winecup","Winecup","Callirhoe involucrata","Malvaceae (Mallow)","native",
     "edible perennial full-sun drought low-water native-tx groundcover ornamental",
     "Full sun","Very low","Well-drained; hates wet feet","6.0-8.0","Hardy native perennial",
     "6-12 in tall, trailing 3 ft","18-24 in","Blooms spring to early summer",
     "Magenta chalices rolling across the ground all spring, from a drought-proof native with a starchy edible taproot - a groundcover that earns its keep twice.",
     "Root cooked like a small parsnip; leaves in moderation","Taproot, young leaves","Mallow family - benign, but harvest roots sparingly; the plant IS the root.",
     "Deeply cut rounded leaves on trailing stems","2-inch wine-red cup flowers that close at night","Dies back in summer heat, returns in fall","Rock gardens, slopes, the strip nothing else survives","False"),
    ("bluebonnet","Texas Bluebonnet","Lupinus texensis","Fabaceae (Legume)","native",
     "full-sun drought low-water native-tx pollinator nitrogen-fixer reseeding annual ornamental",
     "Full sun","Low - overwatering kills more than drought","Poor, well-drained, alkaline","7.0-8.5","Native winter annual",
     "12-18 in","8-12 in","Sow Oct-Nov; blooms March-April",
     "The state flower, and a soil-builder in disguise - bluebonnets fix nitrogen in the worst caliche you own, then reseed themselves forever if you let the pods dry.",
     "Ornamental; pollinator; nitrogen fixer","Not a food plant","NOT edible - seeds and foliage are toxic if eaten. Enjoy with your eyes; scarify seed for planting.",
     "Palm-shaped leaves of 5 leaflets","Blue flower spikes with white tips (the 'bonnet')","Fuzzy pea-like seed pods that pop when dry","Overseed thin lawns and ditches; mow AFTER pods dry","False"),
    ("bay-laurel","Bay Laurel","Laurus nobilis","Lauraceae (Laurel)","herb",
     "edible perennial full-sun part-shade drought low-water container evergreen",
     "Full sun to part shade","Low; well-drained is the rule","Well-drained; great in pots","6.0-7.5","Evergreen; protect below ~15F",
     "Shrub 6-15 ft (smaller in pots)","4-6 ft","Harvest leaves year-round after year 1",
     "The bay leaf in every pot of beans, growing fresh outside your kitchen door - a tough evergreen that thrives in Texas heat and shrugs at drought once established.",
     "Dried or fresh leaves in cooking","Leaves (flavoring - remove before serving)","Remove whole leaves before serving; stiff edges are a hazard swallowed whole. True Laurus nobilis only - ornamental 'cherry laurel' is NOT edible.",
     "Stiff glossy aromatic leaves, classic bay smell when torn","Leathery evergreen shrub habit","Small yellow flower clusters in spring","By the kitchen door; anchors the herb bed","False"),
]
NEW_PLANTS = NEW_PLANTS + V8_PLANTS
